// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: aivision/v1/engine.proto

package aivisionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 检测规则角色（对齐 C ABI av_rule_role，0 为未指定占位）
type DetectionRuleRole int32

const (
	DetectionRuleRole_DETECTION_RULE_ROLE_UNSPECIFIED DetectionRuleRole = 0
	DetectionRuleRole_DETECTION_RULE_ROLE_ROI         DetectionRuleRole = 1 // 布防/检测区域：只在此区域内检测
	DetectionRuleRole_DETECTION_RULE_ROLE_MASK        DetectionRuleRole = 2 // 屏蔽/遮罩区域：此区域内目标忽略
	DetectionRuleRole_DETECTION_RULE_ROLE_LINE        DetectionRuleRole = 3 // 分界线：目标跨线触发
)

// Enum value maps for DetectionRuleRole.
var (
	DetectionRuleRole_name = map[int32]string{
		0: "DETECTION_RULE_ROLE_UNSPECIFIED",
		1: "DETECTION_RULE_ROLE_ROI",
		2: "DETECTION_RULE_ROLE_MASK",
		3: "DETECTION_RULE_ROLE_LINE",
	}
	DetectionRuleRole_value = map[string]int32{
		"DETECTION_RULE_ROLE_UNSPECIFIED": 0,
		"DETECTION_RULE_ROLE_ROI":         1,
		"DETECTION_RULE_ROLE_MASK":        2,
		"DETECTION_RULE_ROLE_LINE":        3,
	}
)

func (x DetectionRuleRole) Enum() *DetectionRuleRole {
	p := new(DetectionRuleRole)
	*p = x
	return p
}

func (x DetectionRuleRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DetectionRuleRole) Descriptor() protoreflect.EnumDescriptor {
	return file_aivision_v1_engine_proto_enumTypes[0].Descriptor()
}

func (DetectionRuleRole) Type() protoreflect.EnumType {
	return &file_aivision_v1_engine_proto_enumTypes[0]
}

func (x DetectionRuleRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DetectionRuleRole.Descriptor instead.
func (DetectionRuleRole) EnumDescriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{0}
}

// 分界线方向（对齐 C ABI av_line_dir，仅 LINE 规则使用）
type DetectionLineDirection int32

const (
	DetectionLineDirection_DETECTION_LINE_DIRECTION_BOTH   DetectionLineDirection = 0 // 双向跨越
	DetectionLineDirection_DETECTION_LINE_DIRECTION_A_TO_B DetectionLineDirection = 1 // 沿折线方向跨越
	DetectionLineDirection_DETECTION_LINE_DIRECTION_B_TO_A DetectionLineDirection = 2 // 逆折线方向跨越
)

// Enum value maps for DetectionLineDirection.
var (
	DetectionLineDirection_name = map[int32]string{
		0: "DETECTION_LINE_DIRECTION_BOTH",
		1: "DETECTION_LINE_DIRECTION_A_TO_B",
		2: "DETECTION_LINE_DIRECTION_B_TO_A",
	}
	DetectionLineDirection_value = map[string]int32{
		"DETECTION_LINE_DIRECTION_BOTH":   0,
		"DETECTION_LINE_DIRECTION_A_TO_B": 1,
		"DETECTION_LINE_DIRECTION_B_TO_A": 2,
	}
)

func (x DetectionLineDirection) Enum() *DetectionLineDirection {
	p := new(DetectionLineDirection)
	*p = x
	return p
}

func (x DetectionLineDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DetectionLineDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_aivision_v1_engine_proto_enumTypes[1].Descriptor()
}

func (DetectionLineDirection) Type() protoreflect.EnumType {
	return &file_aivision_v1_engine_proto_enumTypes[1]
}

func (x DetectionLineDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DetectionLineDirection.Descriptor instead.
func (DetectionLineDirection) EnumDescriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{1}
}

// 对账项类型
type ReconcileItemKind int32

const (
	ReconcileItemKind_RECONCILE_ITEM_KIND_UNSPECIFIED ReconcileItemKind = 0
	ReconcileItemKind_RECONCILE_ITEM_KIND_TASK        ReconcileItemKind = 1 // 摄像头任务
	ReconcileItemKind_RECONCILE_ITEM_KIND_INSTANCE    ReconcileItemKind = 2 // 算法实例
	ReconcileItemKind_RECONCILE_ITEM_KIND_PACKAGE     ReconcileItemKind = 3 // 算法包版本
)

// Enum value maps for ReconcileItemKind.
var (
	ReconcileItemKind_name = map[int32]string{
		0: "RECONCILE_ITEM_KIND_UNSPECIFIED",
		1: "RECONCILE_ITEM_KIND_TASK",
		2: "RECONCILE_ITEM_KIND_INSTANCE",
		3: "RECONCILE_ITEM_KIND_PACKAGE",
	}
	ReconcileItemKind_value = map[string]int32{
		"RECONCILE_ITEM_KIND_UNSPECIFIED": 0,
		"RECONCILE_ITEM_KIND_TASK":        1,
		"RECONCILE_ITEM_KIND_INSTANCE":    2,
		"RECONCILE_ITEM_KIND_PACKAGE":     3,
	}
)

func (x ReconcileItemKind) Enum() *ReconcileItemKind {
	p := new(ReconcileItemKind)
	*p = x
	return p
}

func (x ReconcileItemKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReconcileItemKind) Descriptor() protoreflect.EnumDescriptor {
	return file_aivision_v1_engine_proto_enumTypes[2].Descriptor()
}

func (ReconcileItemKind) Type() protoreflect.EnumType {
	return &file_aivision_v1_engine_proto_enumTypes[2]
}

func (x ReconcileItemKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReconcileItemKind.Descriptor instead.
func (ReconcileItemKind) EnumDescriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{2}
}

// 对账单项结果状态
type ReconcileItemStatus int32

const (
	ReconcileItemStatus_RECONCILE_ITEM_STATUS_UNSPECIFIED ReconcileItemStatus = 0
	ReconcileItemStatus_RECONCILE_ITEM_STATUS_OK          ReconcileItemStatus = 1
	ReconcileItemStatus_RECONCILE_ITEM_STATUS_FAILED      ReconcileItemStatus = 2
)

// Enum value maps for ReconcileItemStatus.
var (
	ReconcileItemStatus_name = map[int32]string{
		0: "RECONCILE_ITEM_STATUS_UNSPECIFIED",
		1: "RECONCILE_ITEM_STATUS_OK",
		2: "RECONCILE_ITEM_STATUS_FAILED",
	}
	ReconcileItemStatus_value = map[string]int32{
		"RECONCILE_ITEM_STATUS_UNSPECIFIED": 0,
		"RECONCILE_ITEM_STATUS_OK":          1,
		"RECONCILE_ITEM_STATUS_FAILED":      2,
	}
)

func (x ReconcileItemStatus) Enum() *ReconcileItemStatus {
	p := new(ReconcileItemStatus)
	*p = x
	return p
}

func (x ReconcileItemStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReconcileItemStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_aivision_v1_engine_proto_enumTypes[3].Descriptor()
}

func (ReconcileItemStatus) Type() protoreflect.EnumType {
	return &file_aivision_v1_engine_proto_enumTypes[3]
}

func (x ReconcileItemStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReconcileItemStatus.Descriptor instead.
func (ReconcileItemStatus) EnumDescriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{3}
}

// 能力可用性（对齐 platform-guidelines 的 Availability）
type CapabilityStatus int32

const (
	CapabilityStatus_CAPABILITY_STATUS_UNSPECIFIED CapabilityStatus = 0
	CapabilityStatus_CAPABILITY_STATUS_AVAILABLE   CapabilityStatus = 1
	CapabilityStatus_CAPABILITY_STATUS_DEGRADED    CapabilityStatus = 2
	CapabilityStatus_CAPABILITY_STATUS_UNSUPPORTED CapabilityStatus = 3
)

// Enum value maps for CapabilityStatus.
var (
	CapabilityStatus_name = map[int32]string{
		0: "CAPABILITY_STATUS_UNSPECIFIED",
		1: "CAPABILITY_STATUS_AVAILABLE",
		2: "CAPABILITY_STATUS_DEGRADED",
		3: "CAPABILITY_STATUS_UNSUPPORTED",
	}
	CapabilityStatus_value = map[string]int32{
		"CAPABILITY_STATUS_UNSPECIFIED": 0,
		"CAPABILITY_STATUS_AVAILABLE":   1,
		"CAPABILITY_STATUS_DEGRADED":    2,
		"CAPABILITY_STATUS_UNSUPPORTED": 3,
	}
)

func (x CapabilityStatus) Enum() *CapabilityStatus {
	p := new(CapabilityStatus)
	*p = x
	return p
}

func (x CapabilityStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CapabilityStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_aivision_v1_engine_proto_enumTypes[4].Descriptor()
}

func (CapabilityStatus) Type() protoreflect.EnumType {
	return &file_aivision_v1_engine_proto_enumTypes[4]
}

func (x CapabilityStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CapabilityStatus.Descriptor instead.
func (CapabilityStatus) EnumDescriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{4}
}

// 摄像头拉流任务配置
type CameraTaskConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CameraId      string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	RtspUrl       string                 `protobuf:"bytes,2,opt,name=rtsp_url,json=rtspUrl,proto3" json:"rtsp_url,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraTaskConfig) Reset() {
	*x = CameraTaskConfig{}
	mi := &file_aivision_v1_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraTaskConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraTaskConfig) ProtoMessage() {}

func (x *CameraTaskConfig) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraTaskConfig.ProtoReflect.Descriptor instead.
func (*CameraTaskConfig) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{0}
}

func (x *CameraTaskConfig) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *CameraTaskConfig) GetRtspUrl() string {
	if x != nil {
		return x.RtspUrl
	}
	return ""
}

func (x *CameraTaskConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// 归一化检测点（原点为有效画面左上角，[0.0, 1.0]）
type DetectionPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionPoint) Reset() {
	*x = DetectionPoint{}
	mi := &file_aivision_v1_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionPoint) ProtoMessage() {}

func (x *DetectionPoint) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionPoint.ProtoReflect.Descriptor instead.
func (*DetectionPoint) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{1}
}

func (x *DetectionPoint) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *DetectionPoint) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// 检测规则（ROI / Mask / 分界线）——任务级配置，由 Engine 从 DesiredState 校验后下发，
// 不进入算法 params_json（对齐 manifest-schema §3 与 algo-package-spec §3.4）
type DetectionRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          DetectionRuleRole      `protobuf:"varint,1,opt,name=role,proto3,enum=aivision.v1.DetectionRuleRole" json:"role,omitempty"`
	LineDirection DetectionLineDirection `protobuf:"varint,2,opt,name=line_direction,json=lineDirection,proto3,enum=aivision.v1.DetectionLineDirection" json:"line_direction,omitempty"` // 仅 role=LINE 有效；区域规则忽略
	Points        []*DetectionPoint      `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`                                                                             // 区域 >=3 首尾相连多边形；线 >=2 折线顶点
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionRule) Reset() {
	*x = DetectionRule{}
	mi := &file_aivision_v1_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionRule) ProtoMessage() {}

func (x *DetectionRule) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionRule.ProtoReflect.Descriptor instead.
func (*DetectionRule) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{2}
}

func (x *DetectionRule) GetRole() DetectionRuleRole {
	if x != nil {
		return x.Role
	}
	return DetectionRuleRole_DETECTION_RULE_ROLE_UNSPECIFIED
}

func (x *DetectionRule) GetLineDirection() DetectionLineDirection {
	if x != nil {
		return x.LineDirection
	}
	return DetectionLineDirection_DETECTION_LINE_DIRECTION_BOTH
}

func (x *DetectionRule) GetPoints() []*DetectionPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

// 算法实例运行配置
type AlgorithmInstanceConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InstanceId       string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	CameraId         string                 `protobuf:"bytes,2,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	AlgorithmId      string                 `protobuf:"bytes,3,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	AlgorithmVersion string                 `protobuf:"bytes,4,opt,name=algorithm_version,json=algorithmVersion,proto3" json:"algorithm_version,omitempty"`
	AnalysisFps      int32                  `protobuf:"varint,5,opt,name=analysis_fps,json=analysisFps,proto3" json:"analysis_fps,omitempty"` // 任务级采样 FPS（对齐 manifest 的 analysis_fps），
	// 资源按 manifest fps_tiers 就近档位结算
	ParamsJson    string           `protobuf:"bytes,6,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"` // 算法自有参数（仅含 config.schema.json 声明字段）
	Enabled       bool             `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Rules         []*DetectionRule `protobuf:"bytes,8,rep,name=rules,proto3" json:"rules,omitempty"` // 任务级检测规则；空表示不过滤
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlgorithmInstanceConfig) Reset() {
	*x = AlgorithmInstanceConfig{}
	mi := &file_aivision_v1_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlgorithmInstanceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlgorithmInstanceConfig) ProtoMessage() {}

func (x *AlgorithmInstanceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlgorithmInstanceConfig.ProtoReflect.Descriptor instead.
func (*AlgorithmInstanceConfig) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{3}
}

func (x *AlgorithmInstanceConfig) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *AlgorithmInstanceConfig) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *AlgorithmInstanceConfig) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *AlgorithmInstanceConfig) GetAlgorithmVersion() string {
	if x != nil {
		return x.AlgorithmVersion
	}
	return ""
}

func (x *AlgorithmInstanceConfig) GetAnalysisFps() int32 {
	if x != nil {
		return x.AnalysisFps
	}
	return 0
}

func (x *AlgorithmInstanceConfig) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

func (x *AlgorithmInstanceConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AlgorithmInstanceConfig) GetRules() []*DetectionRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

// 算法包版本信息
type ActivePackageVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlgorithmId   string                 `protobuf:"bytes,1,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivePackageVersion) Reset() {
	*x = ActivePackageVersion{}
	mi := &file_aivision_v1_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivePackageVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivePackageVersion) ProtoMessage() {}

func (x *ActivePackageVersion) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivePackageVersion.ProtoReflect.Descriptor instead.
func (*ActivePackageVersion) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{4}
}

func (x *ActivePackageVersion) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *ActivePackageVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// 全量期望状态定义
type DesiredState struct {
	state                 protoimpl.MessageState     `protogen:"open.v1"`
	DeviceId              string                     `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Revision              uint64                     `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Tasks                 []*CameraTaskConfig        `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Instances             []*AlgorithmInstanceConfig `protobuf:"bytes,4,rep,name=instances,proto3" json:"instances,omitempty"`
	ActivePackageVersions []*ActivePackageVersion    `protobuf:"bytes,5,rep,name=active_package_versions,json=activePackageVersions,proto3" json:"active_package_versions,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DesiredState) Reset() {
	*x = DesiredState{}
	mi := &file_aivision_v1_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredState) ProtoMessage() {}

func (x *DesiredState) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredState.ProtoReflect.Descriptor instead.
func (*DesiredState) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{5}
}

func (x *DesiredState) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DesiredState) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *DesiredState) GetTasks() []*CameraTaskConfig {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *DesiredState) GetInstances() []*AlgorithmInstanceConfig {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *DesiredState) GetActivePackageVersions() []*ActivePackageVersion {
	if x != nil {
		return x.ActivePackageVersions
	}
	return nil
}

// 下发期望状态请求
type ApplyDesiredStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DesiredState  *DesiredState          `protobuf:"bytes,1,opt,name=desired_state,json=desiredState,proto3" json:"desired_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyDesiredStateRequest) Reset() {
	*x = ApplyDesiredStateRequest{}
	mi := &file_aivision_v1_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyDesiredStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyDesiredStateRequest) ProtoMessage() {}

func (x *ApplyDesiredStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyDesiredStateRequest.ProtoReflect.Descriptor instead.
func (*ApplyDesiredStateRequest) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{6}
}

func (x *ApplyDesiredStateRequest) GetDesiredState() *DesiredState {
	if x != nil {
		return x.DesiredState
	}
	return nil
}

// 对账单项结果（全量对账逐项报告，避免谎报整个 revision 成功）
type ReconcileItemResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ReconcileItemKind      `protobuf:"varint,1,opt,name=kind,proto3,enum=aivision.v1.ReconcileItemKind" json:"kind,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"` // task 为 camera_id；instance 为 instance_id；package 为 algorithm_id
	Status        ReconcileItemStatus    `protobuf:"varint,3,opt,name=status,proto3,enum=aivision.v1.ReconcileItemStatus" json:"status,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`                                     // 失败时的稳定机器码，如 RESOURCE_LIMIT_EXCEEDED；成功为空
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 诊断信息，客户端不得解析其文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileItemResult) Reset() {
	*x = ReconcileItemResult{}
	mi := &file_aivision_v1_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileItemResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileItemResult) ProtoMessage() {}

func (x *ReconcileItemResult) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileItemResult.ProtoReflect.Descriptor instead.
func (*ReconcileItemResult) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{7}
}

func (x *ReconcileItemResult) GetKind() ReconcileItemKind {
	if x != nil {
		return x.Kind
	}
	return ReconcileItemKind_RECONCILE_ITEM_KIND_UNSPECIFIED
}

func (x *ReconcileItemResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReconcileItemResult) GetStatus() ReconcileItemStatus {
	if x != nil {
		return x.Status
	}
	return ReconcileItemStatus_RECONCILE_ITEM_STATUS_UNSPECIFIED
}

func (x *ReconcileItemResult) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ReconcileItemResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ApplyDesiredStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 最近成功应用的 revision；本次失败时保持旧值
	AppliedRevision uint64                 `protobuf:"varint,1,opt,name=applied_revision,json=appliedRevision,proto3" json:"applied_revision,omitempty"`
	Results         []*ReconcileItemResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"` // 逐项对账结果
	// 整体稳定机器码；空串表示成功，否则如 STALE_REVISION / CONFIG_INVALID
	Code          string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	ErrorMessage  string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 诊断信息，客户端不得解析其文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyDesiredStateResponse) Reset() {
	*x = ApplyDesiredStateResponse{}
	mi := &file_aivision_v1_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyDesiredStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyDesiredStateResponse) ProtoMessage() {}

func (x *ApplyDesiredStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyDesiredStateResponse.ProtoReflect.Descriptor instead.
func (*ApplyDesiredStateResponse) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{8}
}

func (x *ApplyDesiredStateResponse) GetAppliedRevision() uint64 {
	if x != nil {
		return x.AppliedRevision
	}
	return 0
}

func (x *ApplyDesiredStateResponse) GetResults() []*ReconcileItemResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ApplyDesiredStateResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ApplyDesiredStateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 单任务更新请求
type UpsertTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *CameraTaskConfig      `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertTaskRequest) Reset() {
	*x = UpsertTaskRequest{}
	mi := &file_aivision_v1_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTaskRequest) ProtoMessage() {}

func (x *UpsertTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTaskRequest.ProtoReflect.Descriptor instead.
func (*UpsertTaskRequest) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{9}
}

func (x *UpsertTaskRequest) GetTask() *CameraTaskConfig {
	if x != nil {
		return x.Task
	}
	return nil
}

type UpsertTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                     // 空串表示成功
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 诊断信息，客户端不得解析其文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertTaskResponse) Reset() {
	*x = UpsertTaskResponse{}
	mi := &file_aivision_v1_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTaskResponse) ProtoMessage() {}

func (x *UpsertTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTaskResponse.ProtoReflect.Descriptor instead.
func (*UpsertTaskResponse) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{10}
}

func (x *UpsertTaskResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpsertTaskResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 实例状态设置请求
type SetInstanceStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInstanceStateRequest) Reset() {
	*x = SetInstanceStateRequest{}
	mi := &file_aivision_v1_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInstanceStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInstanceStateRequest) ProtoMessage() {}

func (x *SetInstanceStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInstanceStateRequest.ProtoReflect.Descriptor instead.
func (*SetInstanceStateRequest) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{11}
}

func (x *SetInstanceStateRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SetInstanceStateRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SetInstanceStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                     // 空串表示成功
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 诊断信息，客户端不得解析其文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetInstanceStateResponse) Reset() {
	*x = SetInstanceStateResponse{}
	mi := &file_aivision_v1_engine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInstanceStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInstanceStateResponse) ProtoMessage() {}

func (x *SetInstanceStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInstanceStateResponse.ProtoReflect.Descriptor instead.
func (*SetInstanceStateResponse) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{12}
}

func (x *SetInstanceStateResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SetInstanceStateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 实例配置热更新请求
type UpdateInstanceConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ParamsJson    string                 `protobuf:"bytes,2,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInstanceConfigRequest) Reset() {
	*x = UpdateInstanceConfigRequest{}
	mi := &file_aivision_v1_engine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInstanceConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInstanceConfigRequest) ProtoMessage() {}

func (x *UpdateInstanceConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInstanceConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateInstanceConfigRequest) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateInstanceConfigRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *UpdateInstanceConfigRequest) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

type UpdateInstanceConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                     // 空串表示成功
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 诊断信息，客户端不得解析其文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInstanceConfigResponse) Reset() {
	*x = UpdateInstanceConfigResponse{}
	mi := &file_aivision_v1_engine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInstanceConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInstanceConfigResponse) ProtoMessage() {}

func (x *UpdateInstanceConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInstanceConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateInstanceConfigResponse) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateInstanceConfigResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateInstanceConfigResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 算法包生命周期管理
type InstallPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackagePath   string                 `protobuf:"bytes,1,opt,name=package_path,json=packagePath,proto3" json:"package_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallPackageRequest) Reset() {
	*x = InstallPackageRequest{}
	mi := &file_aivision_v1_engine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPackageRequest) ProtoMessage() {}

func (x *InstallPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallPackageRequest.ProtoReflect.Descriptor instead.
func (*InstallPackageRequest) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{15}
}

func (x *InstallPackageRequest) GetPackagePath() string {
	if x != nil {
		return x.PackagePath
	}
	return ""
}

type InstallPackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                     // 空串表示成功，否则如 PACKAGE_CHECKSUM_MISMATCH
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 诊断信息，客户端不得解析其文本
	AlgorithmId   string                 `protobuf:"bytes,3,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallPackageResponse) Reset() {
	*x = InstallPackageResponse{}
	mi := &file_aivision_v1_engine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPackageResponse) ProtoMessage() {}

func (x *InstallPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallPackageResponse.ProtoReflect.Descriptor instead.
func (*InstallPackageResponse) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{16}
}

func (x *InstallPackageResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *InstallPackageResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *InstallPackageResponse) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *InstallPackageResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type UpgradePackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackagePath   string                 `protobuf:"bytes,1,opt,name=package_path,json=packagePath,proto3" json:"package_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradePackageRequest) Reset() {
	*x = UpgradePackageRequest{}
	mi := &file_aivision_v1_engine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradePackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradePackageRequest) ProtoMessage() {}

func (x *UpgradePackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradePackageRequest.ProtoReflect.Descriptor instead.
func (*UpgradePackageRequest) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{17}
}

func (x *UpgradePackageRequest) GetPackagePath() string {
	if x != nil {
		return x.PackagePath
	}
	return ""
}

type UpgradePackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                     // 空串表示成功，否则如 PACKAGE_CHECKSUM_MISMATCH
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 诊断信息，客户端不得解析其文本
	AlgorithmId   string                 `protobuf:"bytes,3,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradePackageResponse) Reset() {
	*x = UpgradePackageResponse{}
	mi := &file_aivision_v1_engine_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradePackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradePackageResponse) ProtoMessage() {}

func (x *UpgradePackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradePackageResponse.ProtoReflect.Descriptor instead.
func (*UpgradePackageResponse) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{18}
}

func (x *UpgradePackageResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpgradePackageResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *UpgradePackageResponse) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *UpgradePackageResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RollbackPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlgorithmId   string                 `protobuf:"bytes,1,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	TargetVersion string                 `protobuf:"bytes,2,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackPackageRequest) Reset() {
	*x = RollbackPackageRequest{}
	mi := &file_aivision_v1_engine_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackPackageRequest) ProtoMessage() {}

func (x *RollbackPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackPackageRequest.ProtoReflect.Descriptor instead.
func (*RollbackPackageRequest) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{19}
}

func (x *RollbackPackageRequest) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *RollbackPackageRequest) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

type RollbackPackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                     // 空串表示成功
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 诊断信息，客户端不得解析其文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackPackageResponse) Reset() {
	*x = RollbackPackageResponse{}
	mi := &file_aivision_v1_engine_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackPackageResponse) ProtoMessage() {}

func (x *RollbackPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackPackageResponse.ProtoReflect.Descriptor instead.
func (*RollbackPackageResponse) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{20}
}

func (x *RollbackPackageResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RollbackPackageResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UninstallPackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlgorithmId   string                 `protobuf:"bytes,1,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallPackageRequest) Reset() {
	*x = UninstallPackageRequest{}
	mi := &file_aivision_v1_engine_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallPackageRequest) ProtoMessage() {}

func (x *UninstallPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallPackageRequest.ProtoReflect.Descriptor instead.
func (*UninstallPackageRequest) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{21}
}

func (x *UninstallPackageRequest) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *UninstallPackageRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type UninstallPackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                     // 空串表示成功，否则如 PACKAGE_IN_USE
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 诊断信息，客户端不得解析其文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallPackageResponse) Reset() {
	*x = UninstallPackageResponse{}
	mi := &file_aivision_v1_engine_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallPackageResponse) ProtoMessage() {}

func (x *UninstallPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallPackageResponse.ProtoReflect.Descriptor instead.
func (*UninstallPackageResponse) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{22}
}

func (x *UninstallPackageResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UninstallPackageResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 图片删除与对账请求
type DeleteImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageIds      []string               `protobuf:"bytes,1,rep,name=image_ids,json=imageIds,proto3" json:"image_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteImagesRequest) Reset() {
	*x = DeleteImagesRequest{}
	mi := &file_aivision_v1_engine_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteImagesRequest) ProtoMessage() {}

func (x *DeleteImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteImagesRequest.ProtoReflect.Descriptor instead.
func (*DeleteImagesRequest) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteImagesRequest) GetImageIds() []string {
	if x != nil {
		return x.ImageIds
	}
	return nil
}

type DeleteImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*DeleteImageResult   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`                                     // 空串表示成功
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 诊断信息，客户端不得解析其文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteImagesResponse) Reset() {
	*x = DeleteImagesResponse{}
	mi := &file_aivision_v1_engine_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteImagesResponse) ProtoMessage() {}

func (x *DeleteImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteImagesResponse.ProtoReflect.Descriptor instead.
func (*DeleteImagesResponse) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteImagesResponse) GetResults() []*DeleteImageResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *DeleteImagesResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DeleteImagesResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 图片对账请求：Go 推送其权威保留的图片 ID 集合，Engine 对本地 image catalog 对账，
// 删除不在保留集合中、且非 unreported 的孤儿图片并逐项返回结果（与 ReportOrphanImages
// 方向互补：Engine 主动上报走 ReportOrphanImages，Go 主动对账走本 RPC）
type ReconcileImagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RetainImageIds []string               `protobuf:"bytes,1,rep,name=retain_image_ids,json=retainImageIds,proto3" json:"retain_image_ids,omitempty"` // Go 权威保留的已引用图片 ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReconcileImagesRequest) Reset() {
	*x = ReconcileImagesRequest{}
	mi := &file_aivision_v1_engine_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileImagesRequest) ProtoMessage() {}

func (x *ReconcileImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileImagesRequest.ProtoReflect.Descriptor instead.
func (*ReconcileImagesRequest) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{25}
}

func (x *ReconcileImagesRequest) GetRetainImageIds() []string {
	if x != nil {
		return x.RetainImageIds
	}
	return nil
}

type ReconcileImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*DeleteImageResult   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`                                     // 空串表示成功
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 诊断信息，客户端不得解析其文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileImagesResponse) Reset() {
	*x = ReconcileImagesResponse{}
	mi := &file_aivision_v1_engine_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileImagesResponse) ProtoMessage() {}

func (x *ReconcileImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileImagesResponse.ProtoReflect.Descriptor instead.
func (*ReconcileImagesResponse) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{26}
}

func (x *ReconcileImagesResponse) GetResults() []*DeleteImageResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ReconcileImagesResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ReconcileImagesResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 性能指标与能力档案查询
type QueryProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryProfileRequest) Reset() {
	*x = QueryProfileRequest{}
	mi := &file_aivision_v1_engine_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryProfileRequest) ProtoMessage() {}

func (x *QueryProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryProfileRequest.ProtoReflect.Descriptor instead.
func (*QueryProfileRequest) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{27}
}

// 单能力可用性
type CapabilityState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // 如 inference_runtime / image_ops / jpeg / media_backend
	Status        CapabilityStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=aivision.v1.CapabilityStatus" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // degraded/unsupported 时非空
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityState) Reset() {
	*x = CapabilityState{}
	mi := &file_aivision_v1_engine_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityState) ProtoMessage() {}

func (x *CapabilityState) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityState.ProtoReflect.Descriptor instead.
func (*CapabilityState) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{28}
}

func (x *CapabilityState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CapabilityState) GetStatus() CapabilityStatus {
	if x != nil {
		return x.Status
	}
	return CapabilityStatus_CAPABILITY_STATUS_UNSPECIFIED
}

func (x *CapabilityState) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 平台能力档案（控制面视图，对齐 PlatformProfile 的关键字段）
type PlatformProfileInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion    string                 `protobuf:"bytes,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	PlatformId       string                 `protobuf:"bytes,2,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	AdapterVersion   string                 `protobuf:"bytes,3,opt,name=adapter_version,json=adapterVersion,proto3" json:"adapter_version,omitempty"`
	Arch             string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	OsOrBsp          string                 `protobuf:"bytes,5,opt,name=os_or_bsp,json=osOrBsp,proto3" json:"os_or_bsp,omitempty"`
	MediaBackend     string                 `protobuf:"bytes,6,opt,name=media_backend,json=mediaBackend,proto3" json:"media_backend,omitempty"`                                  // 媒体后端名称+版本，如 "ZLMediaKit 6.0"
	FrameCaps        []FramePixelFormat     `protobuf:"varint,7,rep,packed,name=frame_caps,json=frameCaps,proto3,enum=aivision.v1.FramePixelFormat" json:"frame_caps,omitempty"` // 支持的像素格式
	InferenceRuntime string                 `protobuf:"bytes,8,opt,name=inference_runtime,json=inferenceRuntime,proto3" json:"inference_runtime,omitempty"`                      // 推理运行时，如 "coreml"
	Capabilities     []*CapabilityState     `protobuf:"bytes,9,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	MaxCameras       int32                  `protobuf:"varint,10,opt,name=max_cameras,json=maxCameras,proto3" json:"max_cameras,omitempty"` // 资源账本导出的容量上限
	MaxInstances     int32                  `protobuf:"varint,11,opt,name=max_instances,json=maxInstances,proto3" json:"max_instances,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlatformProfileInfo) Reset() {
	*x = PlatformProfileInfo{}
	mi := &file_aivision_v1_engine_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformProfileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformProfileInfo) ProtoMessage() {}

func (x *PlatformProfileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformProfileInfo.ProtoReflect.Descriptor instead.
func (*PlatformProfileInfo) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{29}
}

func (x *PlatformProfileInfo) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *PlatformProfileInfo) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

func (x *PlatformProfileInfo) GetAdapterVersion() string {
	if x != nil {
		return x.AdapterVersion
	}
	return ""
}

func (x *PlatformProfileInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *PlatformProfileInfo) GetOsOrBsp() string {
	if x != nil {
		return x.OsOrBsp
	}
	return ""
}

func (x *PlatformProfileInfo) GetMediaBackend() string {
	if x != nil {
		return x.MediaBackend
	}
	return ""
}

func (x *PlatformProfileInfo) GetFrameCaps() []FramePixelFormat {
	if x != nil {
		return x.FrameCaps
	}
	return nil
}

func (x *PlatformProfileInfo) GetInferenceRuntime() string {
	if x != nil {
		return x.InferenceRuntime
	}
	return ""
}

func (x *PlatformProfileInfo) GetCapabilities() []*CapabilityState {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PlatformProfileInfo) GetMaxCameras() int32 {
	if x != nil {
		return x.MaxCameras
	}
	return 0
}

func (x *PlatformProfileInfo) GetMaxInstances() int32 {
	if x != nil {
		return x.MaxInstances
	}
	return 0
}

type QueryProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *PlatformProfileInfo   `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`                                     // 空串表示成功
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 诊断信息，客户端不得解析其文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryProfileResponse) Reset() {
	*x = QueryProfileResponse{}
	mi := &file_aivision_v1_engine_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryProfileResponse) ProtoMessage() {}

func (x *QueryProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryProfileResponse.ProtoReflect.Descriptor instead.
func (*QueryProfileResponse) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{30}
}

func (x *QueryProfileResponse) GetProfile() *PlatformProfileInfo {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *QueryProfileResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *QueryProfileResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type QueryMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMetricsRequest) Reset() {
	*x = QueryMetricsRequest{}
	mi := &file_aivision_v1_engine_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMetricsRequest) ProtoMessage() {}

func (x *QueryMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMetricsRequest.ProtoReflect.Descriptor instead.
func (*QueryMetricsRequest) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{31}
}

type QueryMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Telemetry     *DeviceTelemetry       `protobuf:"bytes,1,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`                                     // 空串表示成功
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 诊断信息，客户端不得解析其文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMetricsResponse) Reset() {
	*x = QueryMetricsResponse{}
	mi := &file_aivision_v1_engine_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMetricsResponse) ProtoMessage() {}

func (x *QueryMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMetricsResponse.ProtoReflect.Descriptor instead.
func (*QueryMetricsResponse) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{32}
}

func (x *QueryMetricsResponse) GetTelemetry() *DeviceTelemetry {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

func (x *QueryMetricsResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *QueryMetricsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 摄像头测活请求（RTSP MVP；protocol 当前固定为 "rtsp"）
type ProbeCameraRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"` // 当前固定 "rtsp"
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`           // 完整 RTSP URL（可含百分号编码 userinfo）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeCameraRequest) Reset() {
	*x = ProbeCameraRequest{}
	mi := &file_aivision_v1_engine_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeCameraRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeCameraRequest) ProtoMessage() {}

func (x *ProbeCameraRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeCameraRequest.ProtoReflect.Descriptor instead.
func (*ProbeCameraRequest) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{33}
}

func (x *ProbeCameraRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ProbeCameraRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// 单次传输尝试（TCP/UDP）
type ProbeAttempt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transport     string                 `protobuf:"bytes,1,opt,name=transport,proto3" json:"transport,omitempty"`                        // tcp | udp
	FailureCode   string                 `protobuf:"bytes,2,opt,name=failure_code,json=failureCode,proto3" json:"failure_code,omitempty"` // 空串表示该次成功
	ElapsedMs     uint64                 `protobuf:"varint,3,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeAttempt) Reset() {
	*x = ProbeAttempt{}
	mi := &file_aivision_v1_engine_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeAttempt) ProtoMessage() {}

func (x *ProbeAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeAttempt.ProtoReflect.Descriptor instead.
func (*ProbeAttempt) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{34}
}

func (x *ProbeAttempt) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *ProbeAttempt) GetFailureCode() string {
	if x != nil {
		return x.FailureCode
	}
	return ""
}

func (x *ProbeAttempt) GetElapsedMs() uint64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

type ProbeCameraResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Code              string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                                    // 空串表示 RPC 处理成功（非测活结果）
	ErrorMessage      string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                // 仅诊断，客户端不得解析其文本
	Status            string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                                // success | failed
	FailureCode       string                 `protobuf:"bytes,4,opt,name=failure_code,json=failureCode,proto3" json:"failure_code,omitempty"`                   // RTSP_* 稳定码（status=failed 时有值）
	Attempts          []*ProbeAttempt        `protobuf:"bytes,5,rep,name=attempts,proto3" json:"attempts,omitempty"`                                            // 每次尝试（tcp/udp）
	SelectedTransport string                 `protobuf:"bytes,6,opt,name=selected_transport,json=selectedTransport,proto3" json:"selected_transport,omitempty"` // 实际成功传输方式
	Codec             string                 `protobuf:"bytes,7,opt,name=codec,proto3" json:"codec,omitempty"`                                                  // H264/H265/...（可获得时）
	Width             uint32                 `protobuf:"varint,8,opt,name=width,proto3" json:"width,omitempty"`
	Height            uint32                 `protobuf:"varint,9,opt,name=height,proto3" json:"height,omitempty"`
	Fps               float64                `protobuf:"fixed64,10,opt,name=fps,proto3" json:"fps,omitempty"`
	ElapsedMs         uint64                 `protobuf:"varint,11,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProbeCameraResponse) Reset() {
	*x = ProbeCameraResponse{}
	mi := &file_aivision_v1_engine_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeCameraResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeCameraResponse) ProtoMessage() {}

func (x *ProbeCameraResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_engine_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeCameraResponse.ProtoReflect.Descriptor instead.
func (*ProbeCameraResponse) Descriptor() ([]byte, []int) {
	return file_aivision_v1_engine_proto_rawDescGZIP(), []int{35}
}

func (x *ProbeCameraResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ProbeCameraResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ProbeCameraResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProbeCameraResponse) GetFailureCode() string {
	if x != nil {
		return x.FailureCode
	}
	return ""
}

func (x *ProbeCameraResponse) GetAttempts() []*ProbeAttempt {
	if x != nil {
		return x.Attempts
	}
	return nil
}

func (x *ProbeCameraResponse) GetSelectedTransport() string {
	if x != nil {
		return x.SelectedTransport
	}
	return ""
}

func (x *ProbeCameraResponse) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *ProbeCameraResponse) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ProbeCameraResponse) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ProbeCameraResponse) GetFps() float64 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *ProbeCameraResponse) GetElapsedMs() uint64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

var File_aivision_v1_engine_proto protoreflect.FileDescriptor

const file_aivision_v1_engine_proto_rawDesc = "" +
	"\n" +
	"\x18aivision/v1/engine.proto\x12\vaivision.v1\x1a\x18aivision/v1/common.proto\"d\n" +
	"\x10CameraTaskConfig\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12\x19\n" +
	"\brtsp_url\x18\x02 \x01(\tR\artspUrl\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\",\n" +
	"\x0eDetectionPoint\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\"\xc4\x01\n" +
	"\rDetectionRule\x122\n" +
	"\x04role\x18\x01 \x01(\x0e2\x1e.aivision.v1.DetectionRuleRoleR\x04role\x12J\n" +
	"\x0eline_direction\x18\x02 \x01(\x0e2#.aivision.v1.DetectionLineDirectionR\rlineDirection\x123\n" +
	"\x06points\x18\x03 \x03(\v2\x1b.aivision.v1.DetectionPointR\x06points\"\xb7\x02\n" +
	"\x17AlgorithmInstanceConfig\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1b\n" +
	"\tcamera_id\x18\x02 \x01(\tR\bcameraId\x12!\n" +
	"\falgorithm_id\x18\x03 \x01(\tR\valgorithmId\x12+\n" +
	"\x11algorithm_version\x18\x04 \x01(\tR\x10algorithmVersion\x12!\n" +
	"\fanalysis_fps\x18\x05 \x01(\x05R\vanalysisFps\x12\x1f\n" +
	"\vparams_json\x18\x06 \x01(\tR\n" +
	"paramsJson\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\x120\n" +
	"\x05rules\x18\b \x03(\v2\x1a.aivision.v1.DetectionRuleR\x05rules\"S\n" +
	"\x14ActivePackageVersion\x12!\n" +
	"\falgorithm_id\x18\x01 \x01(\tR\valgorithmId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x9b\x02\n" +
	"\fDesiredState\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x123\n" +
	"\x05tasks\x18\x03 \x03(\v2\x1d.aivision.v1.CameraTaskConfigR\x05tasks\x12B\n" +
	"\tinstances\x18\x04 \x03(\v2$.aivision.v1.AlgorithmInstanceConfigR\tinstances\x12Y\n" +
	"\x17active_package_versions\x18\x05 \x03(\v2!.aivision.v1.ActivePackageVersionR\x15activePackageVersions\"Z\n" +
	"\x18ApplyDesiredStateRequest\x12>\n" +
	"\rdesired_state\x18\x01 \x01(\v2\x19.aivision.v1.DesiredStateR\fdesiredState\"\xcc\x01\n" +
	"\x13ReconcileItemResult\x122\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1e.aivision.v1.ReconcileItemKindR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x128\n" +
	"\x06status\x18\x03 \x01(\x0e2 .aivision.v1.ReconcileItemStatusR\x06status\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\xbb\x01\n" +
	"\x19ApplyDesiredStateResponse\x12)\n" +
	"\x10applied_revision\x18\x01 \x01(\x04R\x0fappliedRevision\x12:\n" +
	"\aresults\x18\x02 \x03(\v2 .aivision.v1.ReconcileItemResultR\aresults\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"F\n" +
	"\x11UpsertTaskRequest\x121\n" +
	"\x04task\x18\x01 \x01(\v2\x1d.aivision.v1.CameraTaskConfigR\x04task\"M\n" +
	"\x12UpsertTaskResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"T\n" +
	"\x17SetInstanceStateRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"S\n" +
	"\x18SetInstanceStateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"_\n" +
	"\x1bUpdateInstanceConfigRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1f\n" +
	"\vparams_json\x18\x02 \x01(\tR\n" +
	"paramsJson\"W\n" +
	"\x1cUpdateInstanceConfigResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\":\n" +
	"\x15InstallPackageRequest\x12!\n" +
	"\fpackage_path\x18\x01 \x01(\tR\vpackagePath\"\x8e\x01\n" +
	"\x16InstallPackageResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12!\n" +
	"\falgorithm_id\x18\x03 \x01(\tR\valgorithmId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\":\n" +
	"\x15UpgradePackageRequest\x12!\n" +
	"\fpackage_path\x18\x01 \x01(\tR\vpackagePath\"\x8e\x01\n" +
	"\x16UpgradePackageResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12!\n" +
	"\falgorithm_id\x18\x03 \x01(\tR\valgorithmId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"b\n" +
	"\x16RollbackPackageRequest\x12!\n" +
	"\falgorithm_id\x18\x01 \x01(\tR\valgorithmId\x12%\n" +
	"\x0etarget_version\x18\x02 \x01(\tR\rtargetVersion\"R\n" +
	"\x17RollbackPackageResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"V\n" +
	"\x17UninstallPackageRequest\x12!\n" +
	"\falgorithm_id\x18\x01 \x01(\tR\valgorithmId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"S\n" +
	"\x18UninstallPackageResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"2\n" +
	"\x13DeleteImagesRequest\x12\x1b\n" +
	"\timage_ids\x18\x01 \x03(\tR\bimageIds\"\x89\x01\n" +
	"\x14DeleteImagesResponse\x128\n" +
	"\aresults\x18\x01 \x03(\v2\x1e.aivision.v1.DeleteImageResultR\aresults\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"B\n" +
	"\x16ReconcileImagesRequest\x12(\n" +
	"\x10retain_image_ids\x18\x01 \x03(\tR\x0eretainImageIds\"\x8c\x01\n" +
	"\x17ReconcileImagesResponse\x128\n" +
	"\aresults\x18\x01 \x03(\v2\x1e.aivision.v1.DeleteImageResultR\aresults\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x15\n" +
	"\x13QueryProfileRequest\"p\n" +
	"\x0fCapabilityState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.aivision.v1.CapabilityStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xce\x03\n" +
	"\x13PlatformProfileInfo\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\tR\rschemaVersion\x12\x1f\n" +
	"\vplatform_id\x18\x02 \x01(\tR\n" +
	"platformId\x12'\n" +
	"\x0fadapter_version\x18\x03 \x01(\tR\x0eadapterVersion\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\x12\x1a\n" +
	"\tos_or_bsp\x18\x05 \x01(\tR\aosOrBsp\x12#\n" +
	"\rmedia_backend\x18\x06 \x01(\tR\fmediaBackend\x12<\n" +
	"\n" +
	"frame_caps\x18\a \x03(\x0e2\x1d.aivision.v1.FramePixelFormatR\tframeCaps\x12+\n" +
	"\x11inference_runtime\x18\b \x01(\tR\x10inferenceRuntime\x12@\n" +
	"\fcapabilities\x18\t \x03(\v2\x1c.aivision.v1.CapabilityStateR\fcapabilities\x12\x1f\n" +
	"\vmax_cameras\x18\n" +
	" \x01(\x05R\n" +
	"maxCameras\x12#\n" +
	"\rmax_instances\x18\v \x01(\x05R\fmaxInstances\"\x8b\x01\n" +
	"\x14QueryProfileResponse\x12:\n" +
	"\aprofile\x18\x01 \x01(\v2 .aivision.v1.PlatformProfileInfoR\aprofile\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x15\n" +
	"\x13QueryMetricsRequest\"\x8b\x01\n" +
	"\x14QueryMetricsResponse\x12:\n" +
	"\ttelemetry\x18\x01 \x01(\v2\x1c.aivision.v1.DeviceTelemetryR\ttelemetry\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"B\n" +
	"\x12ProbeCameraRequest\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"n\n" +
	"\fProbeAttempt\x12\x1c\n" +
	"\ttransport\x18\x01 \x01(\tR\ttransport\x12!\n" +
	"\ffailure_code\x18\x02 \x01(\tR\vfailureCode\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x03 \x01(\x04R\telapsedMs\"\xe4\x02\n" +
	"\x13ProbeCameraResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\ffailure_code\x18\x04 \x01(\tR\vfailureCode\x125\n" +
	"\battempts\x18\x05 \x03(\v2\x19.aivision.v1.ProbeAttemptR\battempts\x12-\n" +
	"\x12selected_transport\x18\x06 \x01(\tR\x11selectedTransport\x12\x14\n" +
	"\x05codec\x18\a \x01(\tR\x05codec\x12\x14\n" +
	"\x05width\x18\b \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\t \x01(\rR\x06height\x12\x10\n" +
	"\x03fps\x18\n" +
	" \x01(\x01R\x03fps\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\v \x01(\x04R\telapsedMs*\x91\x01\n" +
	"\x11DetectionRuleRole\x12#\n" +
	"\x1fDETECTION_RULE_ROLE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DETECTION_RULE_ROLE_ROI\x10\x01\x12\x1c\n" +
	"\x18DETECTION_RULE_ROLE_MASK\x10\x02\x12\x1c\n" +
	"\x18DETECTION_RULE_ROLE_LINE\x10\x03*\x85\x01\n" +
	"\x16DetectionLineDirection\x12!\n" +
	"\x1dDETECTION_LINE_DIRECTION_BOTH\x10\x00\x12#\n" +
	"\x1fDETECTION_LINE_DIRECTION_A_TO_B\x10\x01\x12#\n" +
	"\x1fDETECTION_LINE_DIRECTION_B_TO_A\x10\x02*\x99\x01\n" +
	"\x11ReconcileItemKind\x12#\n" +
	"\x1fRECONCILE_ITEM_KIND_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18RECONCILE_ITEM_KIND_TASK\x10\x01\x12 \n" +
	"\x1cRECONCILE_ITEM_KIND_INSTANCE\x10\x02\x12\x1f\n" +
	"\x1bRECONCILE_ITEM_KIND_PACKAGE\x10\x03*|\n" +
	"\x13ReconcileItemStatus\x12%\n" +
	"!RECONCILE_ITEM_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18RECONCILE_ITEM_STATUS_OK\x10\x01\x12 \n" +
	"\x1cRECONCILE_ITEM_STATUS_FAILED\x10\x02*\x99\x01\n" +
	"\x10CapabilityStatus\x12!\n" +
	"\x1dCAPABILITY_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bCAPABILITY_STATUS_AVAILABLE\x10\x01\x12\x1e\n" +
	"\x1aCAPABILITY_STATUS_DEGRADED\x10\x02\x12!\n" +
	"\x1dCAPABILITY_STATUS_UNSUPPORTED\x10\x032\xb4\t\n" +
	"\rEngineService\x12P\n" +
	"\vProbeCamera\x12\x1f.aivision.v1.ProbeCameraRequest\x1a .aivision.v1.ProbeCameraResponse\x12b\n" +
	"\x11ApplyDesiredState\x12%.aivision.v1.ApplyDesiredStateRequest\x1a&.aivision.v1.ApplyDesiredStateResponse\x12M\n" +
	"\n" +
	"UpsertTask\x12\x1e.aivision.v1.UpsertTaskRequest\x1a\x1f.aivision.v1.UpsertTaskResponse\x12_\n" +
	"\x10SetInstanceState\x12$.aivision.v1.SetInstanceStateRequest\x1a%.aivision.v1.SetInstanceStateResponse\x12k\n" +
	"\x14UpdateInstanceConfig\x12(.aivision.v1.UpdateInstanceConfigRequest\x1a).aivision.v1.UpdateInstanceConfigResponse\x12Y\n" +
	"\x0eInstallPackage\x12\".aivision.v1.InstallPackageRequest\x1a#.aivision.v1.InstallPackageResponse\x12Y\n" +
	"\x0eUpgradePackage\x12\".aivision.v1.UpgradePackageRequest\x1a#.aivision.v1.UpgradePackageResponse\x12\\\n" +
	"\x0fRollbackPackage\x12#.aivision.v1.RollbackPackageRequest\x1a$.aivision.v1.RollbackPackageResponse\x12_\n" +
	"\x10UninstallPackage\x12$.aivision.v1.UninstallPackageRequest\x1a%.aivision.v1.UninstallPackageResponse\x12S\n" +
	"\fDeleteImages\x12 .aivision.v1.DeleteImagesRequest\x1a!.aivision.v1.DeleteImagesResponse\x12\\\n" +
	"\x0fReconcileImages\x12#.aivision.v1.ReconcileImagesRequest\x1a$.aivision.v1.ReconcileImagesResponse\x12S\n" +
	"\fQueryProfile\x12 .aivision.v1.QueryProfileRequest\x1a!.aivision.v1.QueryProfileResponse\x12S\n" +
	"\fQueryMetrics\x12 .aivision.v1.QueryMetricsRequest\x1a!.aivision.v1.QueryMetricsResponseB:Z8niko-vue-admin/app/internal/proto/aivision/v1;aivisionv1b\x06proto3"

var (
	file_aivision_v1_engine_proto_rawDescOnce sync.Once
	file_aivision_v1_engine_proto_rawDescData []byte
)

func file_aivision_v1_engine_proto_rawDescGZIP() []byte {
	file_aivision_v1_engine_proto_rawDescOnce.Do(func() {
		file_aivision_v1_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aivision_v1_engine_proto_rawDesc), len(file_aivision_v1_engine_proto_rawDesc)))
	})
	return file_aivision_v1_engine_proto_rawDescData
}

var file_aivision_v1_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_aivision_v1_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_aivision_v1_engine_proto_goTypes = []any{
	(DetectionRuleRole)(0),               // 0: aivision.v1.DetectionRuleRole
	(DetectionLineDirection)(0),          // 1: aivision.v1.DetectionLineDirection
	(ReconcileItemKind)(0),               // 2: aivision.v1.ReconcileItemKind
	(ReconcileItemStatus)(0),             // 3: aivision.v1.ReconcileItemStatus
	(CapabilityStatus)(0),                // 4: aivision.v1.CapabilityStatus
	(*CameraTaskConfig)(nil),             // 5: aivision.v1.CameraTaskConfig
	(*DetectionPoint)(nil),               // 6: aivision.v1.DetectionPoint
	(*DetectionRule)(nil),                // 7: aivision.v1.DetectionRule
	(*AlgorithmInstanceConfig)(nil),      // 8: aivision.v1.AlgorithmInstanceConfig
	(*ActivePackageVersion)(nil),         // 9: aivision.v1.ActivePackageVersion
	(*DesiredState)(nil),                 // 10: aivision.v1.DesiredState
	(*ApplyDesiredStateRequest)(nil),     // 11: aivision.v1.ApplyDesiredStateRequest
	(*ReconcileItemResult)(nil),          // 12: aivision.v1.ReconcileItemResult
	(*ApplyDesiredStateResponse)(nil),    // 13: aivision.v1.ApplyDesiredStateResponse
	(*UpsertTaskRequest)(nil),            // 14: aivision.v1.UpsertTaskRequest
	(*UpsertTaskResponse)(nil),           // 15: aivision.v1.UpsertTaskResponse
	(*SetInstanceStateRequest)(nil),      // 16: aivision.v1.SetInstanceStateRequest
	(*SetInstanceStateResponse)(nil),     // 17: aivision.v1.SetInstanceStateResponse
	(*UpdateInstanceConfigRequest)(nil),  // 18: aivision.v1.UpdateInstanceConfigRequest
	(*UpdateInstanceConfigResponse)(nil), // 19: aivision.v1.UpdateInstanceConfigResponse
	(*InstallPackageRequest)(nil),        // 20: aivision.v1.InstallPackageRequest
	(*InstallPackageResponse)(nil),       // 21: aivision.v1.InstallPackageResponse
	(*UpgradePackageRequest)(nil),        // 22: aivision.v1.UpgradePackageRequest
	(*UpgradePackageResponse)(nil),       // 23: aivision.v1.UpgradePackageResponse
	(*RollbackPackageRequest)(nil),       // 24: aivision.v1.RollbackPackageRequest
	(*RollbackPackageResponse)(nil),      // 25: aivision.v1.RollbackPackageResponse
	(*UninstallPackageRequest)(nil),      // 26: aivision.v1.UninstallPackageRequest
	(*UninstallPackageResponse)(nil),     // 27: aivision.v1.UninstallPackageResponse
	(*DeleteImagesRequest)(nil),          // 28: aivision.v1.DeleteImagesRequest
	(*DeleteImagesResponse)(nil),         // 29: aivision.v1.DeleteImagesResponse
	(*ReconcileImagesRequest)(nil),       // 30: aivision.v1.ReconcileImagesRequest
	(*ReconcileImagesResponse)(nil),      // 31: aivision.v1.ReconcileImagesResponse
	(*QueryProfileRequest)(nil),          // 32: aivision.v1.QueryProfileRequest
	(*CapabilityState)(nil),              // 33: aivision.v1.CapabilityState
	(*PlatformProfileInfo)(nil),          // 34: aivision.v1.PlatformProfileInfo
	(*QueryProfileResponse)(nil),         // 35: aivision.v1.QueryProfileResponse
	(*QueryMetricsRequest)(nil),          // 36: aivision.v1.QueryMetricsRequest
	(*QueryMetricsResponse)(nil),         // 37: aivision.v1.QueryMetricsResponse
	(*ProbeCameraRequest)(nil),           // 38: aivision.v1.ProbeCameraRequest
	(*ProbeAttempt)(nil),                 // 39: aivision.v1.ProbeAttempt
	(*ProbeCameraResponse)(nil),          // 40: aivision.v1.ProbeCameraResponse
	(*DeleteImageResult)(nil),            // 41: aivision.v1.DeleteImageResult
	(FramePixelFormat)(0),                // 42: aivision.v1.FramePixelFormat
	(*DeviceTelemetry)(nil),              // 43: aivision.v1.DeviceTelemetry
}
var file_aivision_v1_engine_proto_depIdxs = []int32{
	0,  // 0: aivision.v1.DetectionRule.role:type_name -> aivision.v1.DetectionRuleRole
	1,  // 1: aivision.v1.DetectionRule.line_direction:type_name -> aivision.v1.DetectionLineDirection
	6,  // 2: aivision.v1.DetectionRule.points:type_name -> aivision.v1.DetectionPoint
	7,  // 3: aivision.v1.AlgorithmInstanceConfig.rules:type_name -> aivision.v1.DetectionRule
	5,  // 4: aivision.v1.DesiredState.tasks:type_name -> aivision.v1.CameraTaskConfig
	8,  // 5: aivision.v1.DesiredState.instances:type_name -> aivision.v1.AlgorithmInstanceConfig
	9,  // 6: aivision.v1.DesiredState.active_package_versions:type_name -> aivision.v1.ActivePackageVersion
	10, // 7: aivision.v1.ApplyDesiredStateRequest.desired_state:type_name -> aivision.v1.DesiredState
	2,  // 8: aivision.v1.ReconcileItemResult.kind:type_name -> aivision.v1.ReconcileItemKind
	3,  // 9: aivision.v1.ReconcileItemResult.status:type_name -> aivision.v1.ReconcileItemStatus
	12, // 10: aivision.v1.ApplyDesiredStateResponse.results:type_name -> aivision.v1.ReconcileItemResult
	5,  // 11: aivision.v1.UpsertTaskRequest.task:type_name -> aivision.v1.CameraTaskConfig
	41, // 12: aivision.v1.DeleteImagesResponse.results:type_name -> aivision.v1.DeleteImageResult
	41, // 13: aivision.v1.ReconcileImagesResponse.results:type_name -> aivision.v1.DeleteImageResult
	4,  // 14: aivision.v1.CapabilityState.status:type_name -> aivision.v1.CapabilityStatus
	42, // 15: aivision.v1.PlatformProfileInfo.frame_caps:type_name -> aivision.v1.FramePixelFormat
	33, // 16: aivision.v1.PlatformProfileInfo.capabilities:type_name -> aivision.v1.CapabilityState
	34, // 17: aivision.v1.QueryProfileResponse.profile:type_name -> aivision.v1.PlatformProfileInfo
	43, // 18: aivision.v1.QueryMetricsResponse.telemetry:type_name -> aivision.v1.DeviceTelemetry
	39, // 19: aivision.v1.ProbeCameraResponse.attempts:type_name -> aivision.v1.ProbeAttempt
	38, // 20: aivision.v1.EngineService.ProbeCamera:input_type -> aivision.v1.ProbeCameraRequest
	11, // 21: aivision.v1.EngineService.ApplyDesiredState:input_type -> aivision.v1.ApplyDesiredStateRequest
	14, // 22: aivision.v1.EngineService.UpsertTask:input_type -> aivision.v1.UpsertTaskRequest
	16, // 23: aivision.v1.EngineService.SetInstanceState:input_type -> aivision.v1.SetInstanceStateRequest
	18, // 24: aivision.v1.EngineService.UpdateInstanceConfig:input_type -> aivision.v1.UpdateInstanceConfigRequest
	20, // 25: aivision.v1.EngineService.InstallPackage:input_type -> aivision.v1.InstallPackageRequest
	22, // 26: aivision.v1.EngineService.UpgradePackage:input_type -> aivision.v1.UpgradePackageRequest
	24, // 27: aivision.v1.EngineService.RollbackPackage:input_type -> aivision.v1.RollbackPackageRequest
	26, // 28: aivision.v1.EngineService.UninstallPackage:input_type -> aivision.v1.UninstallPackageRequest
	28, // 29: aivision.v1.EngineService.DeleteImages:input_type -> aivision.v1.DeleteImagesRequest
	30, // 30: aivision.v1.EngineService.ReconcileImages:input_type -> aivision.v1.ReconcileImagesRequest
	32, // 31: aivision.v1.EngineService.QueryProfile:input_type -> aivision.v1.QueryProfileRequest
	36, // 32: aivision.v1.EngineService.QueryMetrics:input_type -> aivision.v1.QueryMetricsRequest
	40, // 33: aivision.v1.EngineService.ProbeCamera:output_type -> aivision.v1.ProbeCameraResponse
	13, // 34: aivision.v1.EngineService.ApplyDesiredState:output_type -> aivision.v1.ApplyDesiredStateResponse
	15, // 35: aivision.v1.EngineService.UpsertTask:output_type -> aivision.v1.UpsertTaskResponse
	17, // 36: aivision.v1.EngineService.SetInstanceState:output_type -> aivision.v1.SetInstanceStateResponse
	19, // 37: aivision.v1.EngineService.UpdateInstanceConfig:output_type -> aivision.v1.UpdateInstanceConfigResponse
	21, // 38: aivision.v1.EngineService.InstallPackage:output_type -> aivision.v1.InstallPackageResponse
	23, // 39: aivision.v1.EngineService.UpgradePackage:output_type -> aivision.v1.UpgradePackageResponse
	25, // 40: aivision.v1.EngineService.RollbackPackage:output_type -> aivision.v1.RollbackPackageResponse
	27, // 41: aivision.v1.EngineService.UninstallPackage:output_type -> aivision.v1.UninstallPackageResponse
	29, // 42: aivision.v1.EngineService.DeleteImages:output_type -> aivision.v1.DeleteImagesResponse
	31, // 43: aivision.v1.EngineService.ReconcileImages:output_type -> aivision.v1.ReconcileImagesResponse
	35, // 44: aivision.v1.EngineService.QueryProfile:output_type -> aivision.v1.QueryProfileResponse
	37, // 45: aivision.v1.EngineService.QueryMetrics:output_type -> aivision.v1.QueryMetricsResponse
	33, // [33:46] is the sub-list for method output_type
	20, // [20:33] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_aivision_v1_engine_proto_init() }
func file_aivision_v1_engine_proto_init() {
	if File_aivision_v1_engine_proto != nil {
		return
	}
	file_aivision_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aivision_v1_engine_proto_rawDesc), len(file_aivision_v1_engine_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aivision_v1_engine_proto_goTypes,
		DependencyIndexes: file_aivision_v1_engine_proto_depIdxs,
		EnumInfos:         file_aivision_v1_engine_proto_enumTypes,
		MessageInfos:      file_aivision_v1_engine_proto_msgTypes,
	}.Build()
	File_aivision_v1_engine_proto = out.File
	file_aivision_v1_engine_proto_goTypes = nil
	file_aivision_v1_engine_proto_depIdxs = nil
}
