// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: aivision/v1/engine.proto

package aivisionv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EngineService_ProbeCamera_FullMethodName          = "/aivision.v1.EngineService/ProbeCamera"
	EngineService_StartCameraPreview_FullMethodName   = "/aivision.v1.EngineService/StartCameraPreview"
	EngineService_StopCameraPreview_FullMethodName    = "/aivision.v1.EngineService/StopCameraPreview"
	EngineService_ApplyDesiredState_FullMethodName    = "/aivision.v1.EngineService/ApplyDesiredState"
	EngineService_UpsertTask_FullMethodName           = "/aivision.v1.EngineService/UpsertTask"
	EngineService_SetInstanceState_FullMethodName     = "/aivision.v1.EngineService/SetInstanceState"
	EngineService_UpdateInstanceConfig_FullMethodName = "/aivision.v1.EngineService/UpdateInstanceConfig"
	EngineService_InstallPackage_FullMethodName       = "/aivision.v1.EngineService/InstallPackage"
	EngineService_UpgradePackage_FullMethodName       = "/aivision.v1.EngineService/UpgradePackage"
	EngineService_RollbackPackage_FullMethodName      = "/aivision.v1.EngineService/RollbackPackage"
	EngineService_UninstallPackage_FullMethodName     = "/aivision.v1.EngineService/UninstallPackage"
	EngineService_DeleteImages_FullMethodName         = "/aivision.v1.EngineService/DeleteImages"
	EngineService_ReconcileImages_FullMethodName      = "/aivision.v1.EngineService/ReconcileImages"
	EngineService_QueryProfile_FullMethodName         = "/aivision.v1.EngineService/QueryProfile"
	EngineService_QueryMetrics_FullMethodName         = "/aivision.v1.EngineService/QueryMetrics"
)

// EngineServiceClient is the client API for EngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EngineService: 运行在 C++ 引擎（绑定 engine.sock），供 Go 控制面调用
type EngineServiceClient interface {
	ProbeCamera(ctx context.Context, in *ProbeCameraRequest, opts ...grpc.CallOption) (*ProbeCameraResponse, error)
	StartCameraPreview(ctx context.Context, in *StartCameraPreviewRequest, opts ...grpc.CallOption) (*StartCameraPreviewResponse, error)
	StopCameraPreview(ctx context.Context, in *StopCameraPreviewRequest, opts ...grpc.CallOption) (*StopCameraPreviewResponse, error)
	ApplyDesiredState(ctx context.Context, in *ApplyDesiredStateRequest, opts ...grpc.CallOption) (*ApplyDesiredStateResponse, error)
	UpsertTask(ctx context.Context, in *UpsertTaskRequest, opts ...grpc.CallOption) (*UpsertTaskResponse, error)
	SetInstanceState(ctx context.Context, in *SetInstanceStateRequest, opts ...grpc.CallOption) (*SetInstanceStateResponse, error)
	UpdateInstanceConfig(ctx context.Context, in *UpdateInstanceConfigRequest, opts ...grpc.CallOption) (*UpdateInstanceConfigResponse, error)
	InstallPackage(ctx context.Context, in *InstallPackageRequest, opts ...grpc.CallOption) (*InstallPackageResponse, error)
	UpgradePackage(ctx context.Context, in *UpgradePackageRequest, opts ...grpc.CallOption) (*UpgradePackageResponse, error)
	RollbackPackage(ctx context.Context, in *RollbackPackageRequest, opts ...grpc.CallOption) (*RollbackPackageResponse, error)
	UninstallPackage(ctx context.Context, in *UninstallPackageRequest, opts ...grpc.CallOption) (*UninstallPackageResponse, error)
	DeleteImages(ctx context.Context, in *DeleteImagesRequest, opts ...grpc.CallOption) (*DeleteImagesResponse, error)
	ReconcileImages(ctx context.Context, in *ReconcileImagesRequest, opts ...grpc.CallOption) (*ReconcileImagesResponse, error)
	QueryProfile(ctx context.Context, in *QueryProfileRequest, opts ...grpc.CallOption) (*QueryProfileResponse, error)
	QueryMetrics(ctx context.Context, in *QueryMetricsRequest, opts ...grpc.CallOption) (*QueryMetricsResponse, error)
}

type engineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineServiceClient(cc grpc.ClientConnInterface) EngineServiceClient {
	return &engineServiceClient{cc}
}

func (c *engineServiceClient) ProbeCamera(ctx context.Context, in *ProbeCameraRequest, opts ...grpc.CallOption) (*ProbeCameraResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeCameraResponse)
	err := c.cc.Invoke(ctx, EngineService_ProbeCamera_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) StartCameraPreview(ctx context.Context, in *StartCameraPreviewRequest, opts ...grpc.CallOption) (*StartCameraPreviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartCameraPreviewResponse)
	err := c.cc.Invoke(ctx, EngineService_StartCameraPreview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) StopCameraPreview(ctx context.Context, in *StopCameraPreviewRequest, opts ...grpc.CallOption) (*StopCameraPreviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopCameraPreviewResponse)
	err := c.cc.Invoke(ctx, EngineService_StopCameraPreview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) ApplyDesiredState(ctx context.Context, in *ApplyDesiredStateRequest, opts ...grpc.CallOption) (*ApplyDesiredStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyDesiredStateResponse)
	err := c.cc.Invoke(ctx, EngineService_ApplyDesiredState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) UpsertTask(ctx context.Context, in *UpsertTaskRequest, opts ...grpc.CallOption) (*UpsertTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertTaskResponse)
	err := c.cc.Invoke(ctx, EngineService_UpsertTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) SetInstanceState(ctx context.Context, in *SetInstanceStateRequest, opts ...grpc.CallOption) (*SetInstanceStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetInstanceStateResponse)
	err := c.cc.Invoke(ctx, EngineService_SetInstanceState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) UpdateInstanceConfig(ctx context.Context, in *UpdateInstanceConfigRequest, opts ...grpc.CallOption) (*UpdateInstanceConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateInstanceConfigResponse)
	err := c.cc.Invoke(ctx, EngineService_UpdateInstanceConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) InstallPackage(ctx context.Context, in *InstallPackageRequest, opts ...grpc.CallOption) (*InstallPackageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallPackageResponse)
	err := c.cc.Invoke(ctx, EngineService_InstallPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) UpgradePackage(ctx context.Context, in *UpgradePackageRequest, opts ...grpc.CallOption) (*UpgradePackageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradePackageResponse)
	err := c.cc.Invoke(ctx, EngineService_UpgradePackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) RollbackPackage(ctx context.Context, in *RollbackPackageRequest, opts ...grpc.CallOption) (*RollbackPackageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackPackageResponse)
	err := c.cc.Invoke(ctx, EngineService_RollbackPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) UninstallPackage(ctx context.Context, in *UninstallPackageRequest, opts ...grpc.CallOption) (*UninstallPackageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UninstallPackageResponse)
	err := c.cc.Invoke(ctx, EngineService_UninstallPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) DeleteImages(ctx context.Context, in *DeleteImagesRequest, opts ...grpc.CallOption) (*DeleteImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteImagesResponse)
	err := c.cc.Invoke(ctx, EngineService_DeleteImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) ReconcileImages(ctx context.Context, in *ReconcileImagesRequest, opts ...grpc.CallOption) (*ReconcileImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconcileImagesResponse)
	err := c.cc.Invoke(ctx, EngineService_ReconcileImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) QueryProfile(ctx context.Context, in *QueryProfileRequest, opts ...grpc.CallOption) (*QueryProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryProfileResponse)
	err := c.cc.Invoke(ctx, EngineService_QueryProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) QueryMetrics(ctx context.Context, in *QueryMetricsRequest, opts ...grpc.CallOption) (*QueryMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryMetricsResponse)
	err := c.cc.Invoke(ctx, EngineService_QueryMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineServiceServer is the server API for EngineService service.
// All implementations must embed UnimplementedEngineServiceServer
// for forward compatibility.
//
// EngineService: 运行在 C++ 引擎（绑定 engine.sock），供 Go 控制面调用
type EngineServiceServer interface {
	ProbeCamera(context.Context, *ProbeCameraRequest) (*ProbeCameraResponse, error)
	StartCameraPreview(context.Context, *StartCameraPreviewRequest) (*StartCameraPreviewResponse, error)
	StopCameraPreview(context.Context, *StopCameraPreviewRequest) (*StopCameraPreviewResponse, error)
	ApplyDesiredState(context.Context, *ApplyDesiredStateRequest) (*ApplyDesiredStateResponse, error)
	UpsertTask(context.Context, *UpsertTaskRequest) (*UpsertTaskResponse, error)
	SetInstanceState(context.Context, *SetInstanceStateRequest) (*SetInstanceStateResponse, error)
	UpdateInstanceConfig(context.Context, *UpdateInstanceConfigRequest) (*UpdateInstanceConfigResponse, error)
	InstallPackage(context.Context, *InstallPackageRequest) (*InstallPackageResponse, error)
	UpgradePackage(context.Context, *UpgradePackageRequest) (*UpgradePackageResponse, error)
	RollbackPackage(context.Context, *RollbackPackageRequest) (*RollbackPackageResponse, error)
	UninstallPackage(context.Context, *UninstallPackageRequest) (*UninstallPackageResponse, error)
	DeleteImages(context.Context, *DeleteImagesRequest) (*DeleteImagesResponse, error)
	ReconcileImages(context.Context, *ReconcileImagesRequest) (*ReconcileImagesResponse, error)
	QueryProfile(context.Context, *QueryProfileRequest) (*QueryProfileResponse, error)
	QueryMetrics(context.Context, *QueryMetricsRequest) (*QueryMetricsResponse, error)
	mustEmbedUnimplementedEngineServiceServer()
}

// UnimplementedEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngineServiceServer struct{}

func (UnimplementedEngineServiceServer) ProbeCamera(context.Context, *ProbeCameraRequest) (*ProbeCameraResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProbeCamera not implemented")
}
func (UnimplementedEngineServiceServer) StartCameraPreview(context.Context, *StartCameraPreviewRequest) (*StartCameraPreviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartCameraPreview not implemented")
}
func (UnimplementedEngineServiceServer) StopCameraPreview(context.Context, *StopCameraPreviewRequest) (*StopCameraPreviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopCameraPreview not implemented")
}
func (UnimplementedEngineServiceServer) ApplyDesiredState(context.Context, *ApplyDesiredStateRequest) (*ApplyDesiredStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyDesiredState not implemented")
}
func (UnimplementedEngineServiceServer) UpsertTask(context.Context, *UpsertTaskRequest) (*UpsertTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertTask not implemented")
}
func (UnimplementedEngineServiceServer) SetInstanceState(context.Context, *SetInstanceStateRequest) (*SetInstanceStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetInstanceState not implemented")
}
func (UnimplementedEngineServiceServer) UpdateInstanceConfig(context.Context, *UpdateInstanceConfigRequest) (*UpdateInstanceConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateInstanceConfig not implemented")
}
func (UnimplementedEngineServiceServer) InstallPackage(context.Context, *InstallPackageRequest) (*InstallPackageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallPackage not implemented")
}
func (UnimplementedEngineServiceServer) UpgradePackage(context.Context, *UpgradePackageRequest) (*UpgradePackageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpgradePackage not implemented")
}
func (UnimplementedEngineServiceServer) RollbackPackage(context.Context, *RollbackPackageRequest) (*RollbackPackageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackPackage not implemented")
}
func (UnimplementedEngineServiceServer) UninstallPackage(context.Context, *UninstallPackageRequest) (*UninstallPackageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UninstallPackage not implemented")
}
func (UnimplementedEngineServiceServer) DeleteImages(context.Context, *DeleteImagesRequest) (*DeleteImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteImages not implemented")
}
func (UnimplementedEngineServiceServer) ReconcileImages(context.Context, *ReconcileImagesRequest) (*ReconcileImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReconcileImages not implemented")
}
func (UnimplementedEngineServiceServer) QueryProfile(context.Context, *QueryProfileRequest) (*QueryProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryProfile not implemented")
}
func (UnimplementedEngineServiceServer) QueryMetrics(context.Context, *QueryMetricsRequest) (*QueryMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryMetrics not implemented")
}
func (UnimplementedEngineServiceServer) mustEmbedUnimplementedEngineServiceServer() {}
func (UnimplementedEngineServiceServer) testEmbeddedByValue()                       {}

// UnsafeEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngineServiceServer will
// result in compilation errors.
type UnsafeEngineServiceServer interface {
	mustEmbedUnimplementedEngineServiceServer()
}

func RegisterEngineServiceServer(s grpc.ServiceRegistrar, srv EngineServiceServer) {
	// If the following call panics, it indicates UnimplementedEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EngineService_ServiceDesc, srv)
}

func _EngineService_ProbeCamera_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeCameraRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).ProbeCamera(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_ProbeCamera_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).ProbeCamera(ctx, req.(*ProbeCameraRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_StartCameraPreview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartCameraPreviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).StartCameraPreview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_StartCameraPreview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).StartCameraPreview(ctx, req.(*StartCameraPreviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_StopCameraPreview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopCameraPreviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).StopCameraPreview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_StopCameraPreview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).StopCameraPreview(ctx, req.(*StopCameraPreviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_ApplyDesiredState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyDesiredStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).ApplyDesiredState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_ApplyDesiredState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).ApplyDesiredState(ctx, req.(*ApplyDesiredStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_UpsertTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).UpsertTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_UpsertTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).UpsertTask(ctx, req.(*UpsertTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_SetInstanceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetInstanceStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).SetInstanceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_SetInstanceState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).SetInstanceState(ctx, req.(*SetInstanceStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_UpdateInstanceConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInstanceConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).UpdateInstanceConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_UpdateInstanceConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).UpdateInstanceConfig(ctx, req.(*UpdateInstanceConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_InstallPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).InstallPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_InstallPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).InstallPackage(ctx, req.(*InstallPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_UpgradePackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradePackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).UpgradePackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_UpgradePackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).UpgradePackage(ctx, req.(*UpgradePackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_RollbackPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).RollbackPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_RollbackPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).RollbackPackage(ctx, req.(*RollbackPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_UninstallPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UninstallPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).UninstallPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_UninstallPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).UninstallPackage(ctx, req.(*UninstallPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_DeleteImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).DeleteImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_DeleteImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).DeleteImages(ctx, req.(*DeleteImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_ReconcileImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconcileImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).ReconcileImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_ReconcileImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).ReconcileImages(ctx, req.(*ReconcileImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_QueryProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).QueryProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_QueryProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).QueryProfile(ctx, req.(*QueryProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_QueryMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).QueryMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_QueryMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).QueryMetrics(ctx, req.(*QueryMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EngineService_ServiceDesc is the grpc.ServiceDesc for EngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aivision.v1.EngineService",
	HandlerType: (*EngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProbeCamera",
			Handler:    _EngineService_ProbeCamera_Handler,
		},
		{
			MethodName: "StartCameraPreview",
			Handler:    _EngineService_StartCameraPreview_Handler,
		},
		{
			MethodName: "StopCameraPreview",
			Handler:    _EngineService_StopCameraPreview_Handler,
		},
		{
			MethodName: "ApplyDesiredState",
			Handler:    _EngineService_ApplyDesiredState_Handler,
		},
		{
			MethodName: "UpsertTask",
			Handler:    _EngineService_UpsertTask_Handler,
		},
		{
			MethodName: "SetInstanceState",
			Handler:    _EngineService_SetInstanceState_Handler,
		},
		{
			MethodName: "UpdateInstanceConfig",
			Handler:    _EngineService_UpdateInstanceConfig_Handler,
		},
		{
			MethodName: "InstallPackage",
			Handler:    _EngineService_InstallPackage_Handler,
		},
		{
			MethodName: "UpgradePackage",
			Handler:    _EngineService_UpgradePackage_Handler,
		},
		{
			MethodName: "RollbackPackage",
			Handler:    _EngineService_RollbackPackage_Handler,
		},
		{
			MethodName: "UninstallPackage",
			Handler:    _EngineService_UninstallPackage_Handler,
		},
		{
			MethodName: "DeleteImages",
			Handler:    _EngineService_DeleteImages_Handler,
		},
		{
			MethodName: "ReconcileImages",
			Handler:    _EngineService_ReconcileImages_Handler,
		},
		{
			MethodName: "QueryProfile",
			Handler:    _EngineService_QueryProfile_Handler,
		},
		{
			MethodName: "QueryMetrics",
			Handler:    _EngineService_QueryMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aivision/v1/engine.proto",
}
