// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: aivision/v1/person.proto

package aivisionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 人员档案（预留）
type PersonRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PersonId       string                 `protobuf:"bytes,1,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FeatureVersion string                 `protobuf:"bytes,3,opt,name=feature_version,json=featureVersion,proto3" json:"feature_version,omitempty"` // 特征提取模型版本
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PersonRecord) Reset() {
	*x = PersonRecord{}
	mi := &file_aivision_v1_person_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonRecord) ProtoMessage() {}

func (x *PersonRecord) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_person_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonRecord.ProtoReflect.Descriptor instead.
func (*PersonRecord) Descriptor() ([]byte, []int) {
	return file_aivision_v1_person_proto_rawDescGZIP(), []int{0}
}

func (x *PersonRecord) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *PersonRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonRecord) GetFeatureVersion() string {
	if x != nil {
		return x.FeatureVersion
	}
	return ""
}

type SyncPersonsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Persons       []*PersonRecord        `protobuf:"bytes,1,rep,name=persons,proto3" json:"persons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPersonsRequest) Reset() {
	*x = SyncPersonsRequest{}
	mi := &file_aivision_v1_person_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPersonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPersonsRequest) ProtoMessage() {}

func (x *SyncPersonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_person_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPersonsRequest.ProtoReflect.Descriptor instead.
func (*SyncPersonsRequest) Descriptor() ([]byte, []int) {
	return file_aivision_v1_person_proto_rawDescGZIP(), []int{1}
}

func (x *SyncPersonsRequest) GetPersons() []*PersonRecord {
	if x != nil {
		return x.Persons
	}
	return nil
}

type SyncPersonsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalIndexed  int32                  `protobuf:"varint,1,opt,name=total_indexed,json=totalIndexed,proto3" json:"total_indexed,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`                                     // 空串表示成功
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 诊断信息，客户端不得解析其文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncPersonsResponse) Reset() {
	*x = SyncPersonsResponse{}
	mi := &file_aivision_v1_person_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPersonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPersonsResponse) ProtoMessage() {}

func (x *SyncPersonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aivision_v1_person_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPersonsResponse.ProtoReflect.Descriptor instead.
func (*SyncPersonsResponse) Descriptor() ([]byte, []int) {
	return file_aivision_v1_person_proto_rawDescGZIP(), []int{2}
}

func (x *SyncPersonsResponse) GetTotalIndexed() int32 {
	if x != nil {
		return x.TotalIndexed
	}
	return 0
}

func (x *SyncPersonsResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SyncPersonsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_aivision_v1_person_proto protoreflect.FileDescriptor

const file_aivision_v1_person_proto_rawDesc = "" +
	"\n" +
	"\x18aivision/v1/person.proto\x12\vaivision.v1\"h\n" +
	"\fPersonRecord\x12\x1b\n" +
	"\tperson_id\x18\x01 \x01(\tR\bpersonId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0ffeature_version\x18\x03 \x01(\tR\x0efeatureVersion\"I\n" +
	"\x12SyncPersonsRequest\x123\n" +
	"\apersons\x18\x01 \x03(\v2\x19.aivision.v1.PersonRecordR\apersons\"s\n" +
	"\x13SyncPersonsResponse\x12#\n" +
	"\rtotal_indexed\x18\x01 \x01(\x05R\ftotalIndexed\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2a\n" +
	"\rPersonService\x12P\n" +
	"\vSyncPersons\x12\x1f.aivision.v1.SyncPersonsRequest\x1a .aivision.v1.SyncPersonsResponseB:Z8niko-vue-admin/app/internal/proto/aivision/v1;aivisionv1b\x06proto3"

var (
	file_aivision_v1_person_proto_rawDescOnce sync.Once
	file_aivision_v1_person_proto_rawDescData []byte
)

func file_aivision_v1_person_proto_rawDescGZIP() []byte {
	file_aivision_v1_person_proto_rawDescOnce.Do(func() {
		file_aivision_v1_person_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aivision_v1_person_proto_rawDesc), len(file_aivision_v1_person_proto_rawDesc)))
	})
	return file_aivision_v1_person_proto_rawDescData
}

var file_aivision_v1_person_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_aivision_v1_person_proto_goTypes = []any{
	(*PersonRecord)(nil),        // 0: aivision.v1.PersonRecord
	(*SyncPersonsRequest)(nil),  // 1: aivision.v1.SyncPersonsRequest
	(*SyncPersonsResponse)(nil), // 2: aivision.v1.SyncPersonsResponse
}
var file_aivision_v1_person_proto_depIdxs = []int32{
	0, // 0: aivision.v1.SyncPersonsRequest.persons:type_name -> aivision.v1.PersonRecord
	1, // 1: aivision.v1.PersonService.SyncPersons:input_type -> aivision.v1.SyncPersonsRequest
	2, // 2: aivision.v1.PersonService.SyncPersons:output_type -> aivision.v1.SyncPersonsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_aivision_v1_person_proto_init() }
func file_aivision_v1_person_proto_init() {
	if File_aivision_v1_person_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aivision_v1_person_proto_rawDesc), len(file_aivision_v1_person_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aivision_v1_person_proto_goTypes,
		DependencyIndexes: file_aivision_v1_person_proto_depIdxs,
		MessageInfos:      file_aivision_v1_person_proto_msgTypes,
	}.Build()
	File_aivision_v1_person_proto = out.File
	file_aivision_v1_person_proto_goTypes = nil
	file_aivision_v1_person_proto_depIdxs = nil
}
