// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"argus/app/internal/api"
	"argus/app/internal/middleware"
	"argus/app/internal/pkg/config"
	"argus/app/internal/pkg/db"
	"argus/app/internal/pkg/engineipc"
	"argus/app/internal/pkg/logger"
	"argus/app/internal/pkg/ntp"
	"argus/app/internal/pkg/storage"
	"argus/app/internal/repository"
	"argus/app/internal/router"
	"argus/app/internal/service"
)

// Injectors from wire.go:

// InitializeApp 装配启动依赖链：config → db → logger → engine。
func InitializeApp(cfg *config.Config) (*App, error) {
	zapLogger, err := logger.New(cfg)
	if err != nil {
		return nil, err
	}
	gormDB, err := db.New(cfg, zapLogger)
	if err != nil {
		return nil, err
	}
	handlerFunc := middleware.ErrorHandler()
	authRepository := repository.NewAuthRepository(gormDB)
	authMiddleware := middleware.NewAuthMiddleware(authRepository, cfg)
	menuRepository := repository.NewMenuRepository(gormDB)
	permMiddleware := middleware.NewPermMiddleware(menuRepository)
	operationLogRepository := repository.NewOperationLogRepository(gormDB)
	operationLogService := service.NewOperationLogService(operationLogRepository)
	oplogMiddleware := middleware.NewOplogMiddleware(operationLogService, zapLogger)
	openPersonIPWhitelistMiddleware := middleware.NewOpenPersonIPWhitelistMiddleware(cfg)
	menuService := service.NewMenuService(menuRepository)
	menuHandler := api.NewMenuHandler(menuService)
	roleRepository := repository.NewRoleRepository(gormDB)
	roleService := service.NewRoleService(roleRepository, menuRepository)
	roleHandler := api.NewRoleHandler(roleService)
	departmentRepository := repository.NewDepartmentRepository(gormDB)
	deptService := service.NewDeptService(departmentRepository)
	departmentHandler := api.NewDepartmentHandler(deptService)
	operationLogHandler := api.NewOperationLogHandler(operationLogService)
	userRepository := repository.NewUserRepository(gormDB)
	userService := service.NewUserService(userRepository, departmentRepository, roleRepository)
	userHandler := api.NewUserHandler(userService)
	authService := service.NewAuthService(authRepository, userRepository, menuRepository, cfg)
	authHandler := api.NewAuthHandler(authService, authMiddleware, cfg)
	fileStorage, err := storage.New(cfg)
	if err != nil {
		return nil, err
	}
	fileService := service.NewFileService(fileStorage, cfg)
	fileHandler := api.NewFileHandler(fileService, cfg)
	systemConfigRepository := repository.NewSystemConfigRepository(gormDB)
	executor := ntp.NewExecutor()
	ntpService := service.NewNTPService(systemConfigRepository, executor, zapLogger)
	ntpHandler := api.NewNTPHandler(ntpService)
	networkService, err := service.NewNetworkService(cfg, operationLogService, zapLogger)
	if err != nil {
		return nil, err
	}
	networkHandler := api.NewNetworkHandler(networkService)
	cameraRepository := repository.NewCameraRepository(gormDB)
	taskRepository := repository.NewTaskRepository(gormDB)
	engineClient, err := engineipc.NewEngineClient(cfg)
	if err != nil {
		return nil, err
	}
	cameraService := service.NewCameraService(cameraRepository, taskRepository, engineClient)
	cameraHandler := api.NewCameraHandler(cameraService)
	personRepository := repository.NewPersonRepository(gormDB)
	personFaceRepository := repository.NewPersonFaceRepository(gormDB)
	personService := service.NewPersonService(personRepository, personFaceRepository, fileStorage, engineClient)
	personHandler := api.NewPersonHandler(personService)
	algorithmRepository := repository.NewAlgorithmRepository(gormDB)
	algorithmService := service.NewAlgorithmService(algorithmRepository, engineClient, zapLogger)
	algorithmHandler := api.NewAlgorithmHandler(algorithmService)
	alarmRecordRepository := repository.NewAlarmRecordRepository(gormDB)
	plateObservationRepository := repository.NewPlateObservationRepository(gormDB)
	faceObservationRepository := repository.NewFaceObservationRepository(gormDB)
	faceCaptureRepository := repository.NewFaceCaptureRepository(gormDB)
	reportAdapter := service.NewReportAdapterWithAlarm(taskRepository, alarmRecordRepository, plateObservationRepository, faceObservationRepository, faceCaptureRepository, zapLogger)
	taskService := service.NewTaskService(taskRepository, cameraRepository, algorithmRepository, reportAdapter, engineClient, zapLogger)
	taskHandler := api.NewTaskHandler(taskService)
	alarmRecordService := service.NewAlarmRecordService(alarmRecordRepository, cameraRepository, algorithmRepository, taskRepository, cfg)
	alarmRecordHandler := api.NewAlarmRecordHandler(alarmRecordService)
	plateObservationService := service.NewPlateObservationService(plateObservationRepository, cameraRepository, cfg)
	plateObservationHandler := api.NewPlateObservationHandler(plateObservationService)
	faceObservationService := service.NewFaceObservationService(faceObservationRepository, cameraRepository, cfg)
	faceObservationHandler := api.NewFaceObservationHandler(faceObservationService)
	faceCaptureService := service.NewFaceCaptureService(faceCaptureRepository, cameraRepository, cfg)
	faceCaptureHandler := api.NewFaceCaptureHandler(faceCaptureService)
	deps := router.Deps{
		ErrorHandler:            handlerFunc,
		AuthMiddleware:          authMiddleware,
		PermMiddleware:          permMiddleware,
		OplogMiddleware:         oplogMiddleware,
		OpenPersonIPMiddleware:  openPersonIPWhitelistMiddleware,
		MenuHandler:             menuHandler,
		RoleHandler:             roleHandler,
		DepartmentHandler:       departmentHandler,
		OperationLogHandler:     operationLogHandler,
		UserHandler:             userHandler,
		AuthHandler:             authHandler,
		FileHandler:             fileHandler,
		NTPHandler:              ntpHandler,
		NetworkHandler:          networkHandler,
		CameraHandler:           cameraHandler,
		PersonHandler:           personHandler,
		AlgorithmHandler:        algorithmHandler,
		TaskHandler:             taskHandler,
		AlarmRecordHandler:      alarmRecordHandler,
		PlateObservationHandler: plateObservationHandler,
		FaceObservationHandler:  faceObservationHandler,
		FaceCaptureHandler:      faceCaptureHandler,
	}
	engine := router.New(cfg, deps)
	desiredStateAdapter := service.NewDesiredStateAdapter(taskRepository, personFaceRepository, zapLogger)
	runtime := engineipc.NewRuntime(zapLogger, desiredStateAdapter, reportAdapter)
	app := &App{
		DB:           gormDB,
		Logger:       zapLogger,
		Engine:       engine,
		NTPService:   ntpService,
		Network:      networkService,
		IPCRuntime:   runtime,
		EngineClient: engineClient,
		TaskService:  taskService,
	}
	return app, nil
}
