// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: argus/v1/app.proto

package argusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 任务运行状态
type TaskStatusCode int32

const (
	TaskStatusCode_TASK_STATUS_UNSPECIFIED  TaskStatusCode = 0
	TaskStatusCode_TASK_STATUS_STARTING     TaskStatusCode = 1
	TaskStatusCode_TASK_STATUS_RUNNING      TaskStatusCode = 2
	TaskStatusCode_TASK_STATUS_DEGRADED     TaskStatusCode = 3
	TaskStatusCode_TASK_STATUS_RECONNECTING TaskStatusCode = 4
	TaskStatusCode_TASK_STATUS_STOPPED      TaskStatusCode = 5
	TaskStatusCode_TASK_STATUS_ERROR        TaskStatusCode = 6
)

// Enum value maps for TaskStatusCode.
var (
	TaskStatusCode_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_STARTING",
		2: "TASK_STATUS_RUNNING",
		3: "TASK_STATUS_DEGRADED",
		4: "TASK_STATUS_RECONNECTING",
		5: "TASK_STATUS_STOPPED",
		6: "TASK_STATUS_ERROR",
	}
	TaskStatusCode_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED":  0,
		"TASK_STATUS_STARTING":     1,
		"TASK_STATUS_RUNNING":      2,
		"TASK_STATUS_DEGRADED":     3,
		"TASK_STATUS_RECONNECTING": 4,
		"TASK_STATUS_STOPPED":      5,
		"TASK_STATUS_ERROR":        6,
	}
)

func (x TaskStatusCode) Enum() *TaskStatusCode {
	p := new(TaskStatusCode)
	*p = x
	return p
}

func (x TaskStatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_argus_v1_app_proto_enumTypes[0].Descriptor()
}

func (TaskStatusCode) Type() protoreflect.EnumType {
	return &file_argus_v1_app_proto_enumTypes[0]
}

func (x TaskStatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatusCode.Descriptor instead.
func (TaskStatusCode) EnumDescriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{0}
}

// 实例运行状态
type InstanceStatusCode int32

const (
	InstanceStatusCode_INSTANCE_STATUS_UNSPECIFIED InstanceStatusCode = 0
	InstanceStatusCode_INSTANCE_STATUS_STARTING    InstanceStatusCode = 1
	InstanceStatusCode_INSTANCE_STATUS_RUNNING     InstanceStatusCode = 2
	InstanceStatusCode_INSTANCE_STATUS_DEGRADED    InstanceStatusCode = 3
	InstanceStatusCode_INSTANCE_STATUS_STOPPED     InstanceStatusCode = 4
	InstanceStatusCode_INSTANCE_STATUS_ERROR       InstanceStatusCode = 5
)

// Enum value maps for InstanceStatusCode.
var (
	InstanceStatusCode_name = map[int32]string{
		0: "INSTANCE_STATUS_UNSPECIFIED",
		1: "INSTANCE_STATUS_STARTING",
		2: "INSTANCE_STATUS_RUNNING",
		3: "INSTANCE_STATUS_DEGRADED",
		4: "INSTANCE_STATUS_STOPPED",
		5: "INSTANCE_STATUS_ERROR",
	}
	InstanceStatusCode_value = map[string]int32{
		"INSTANCE_STATUS_UNSPECIFIED": 0,
		"INSTANCE_STATUS_STARTING":    1,
		"INSTANCE_STATUS_RUNNING":     2,
		"INSTANCE_STATUS_DEGRADED":    3,
		"INSTANCE_STATUS_STOPPED":     4,
		"INSTANCE_STATUS_ERROR":       5,
	}
)

func (x InstanceStatusCode) Enum() *InstanceStatusCode {
	p := new(InstanceStatusCode)
	*p = x
	return p
}

func (x InstanceStatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstanceStatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_argus_v1_app_proto_enumTypes[1].Descriptor()
}

func (InstanceStatusCode) Type() protoreflect.EnumType {
	return &file_argus_v1_app_proto_enumTypes[1]
}

func (x InstanceStatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstanceStatusCode.Descriptor instead.
func (InstanceStatusCode) EnumDescriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{1}
}

// 告警事件上报
type AlarmEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 目标级全局事件 ID = "<instance_run_id>/<batch_event_id>-<target_sequence>"（Engine 生成）；
	// 一个检测批次会被 Engine fan-out 为多条 AlarmEvent，因此该 ID 不能复用批次 ID，
	// Go 必须按本字段幂等去重（对齐 runtime-guidelines §6）
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// 稳定实例配置 ID（对应 AlgorithmInstanceConfig.instance_id）
	InstanceId       string `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	CameraId         string `protobuf:"bytes,3,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	AlgorithmId      string `protobuf:"bytes,4,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	AlgorithmVersion string `protobuf:"bytes,5,opt,name=algorithm_version,json=algorithmVersion,proto3" json:"algorithm_version,omitempty"`
	AlarmTypeId      string `protobuf:"bytes,6,opt,name=alarm_type_id,json=alarmTypeId,proto3" json:"alarm_type_id,omitempty"`
	WallTimeNs       int64  `protobuf:"varint,7,opt,name=wall_time_ns,json=wallTimeNs,proto3" json:"wall_time_ns,omitempty"`
	TimeSynced       bool   `protobuf:"varint,8,opt,name=time_synced,json=timeSynced,proto3" json:"time_synced,omitempty"`
	// 目标级事件恰好包含一个检测目标；同一批次的事件可共享 image_id。
	Objects             []*DetectedObject `protobuf:"bytes,9,rep,name=objects,proto3" json:"objects,omitempty"`
	ImageId             string            `protobuf:"bytes,10,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	ImageRelPath        string            `protobuf:"bytes,11,opt,name=image_rel_path,json=imageRelPath,proto3" json:"image_rel_path,omitempty"` // 规范化相对路径；禁止绝对路径；同批次事件可复用
	InferenceDurationUs int64             `protobuf:"varint,12,opt,name=inference_duration_us,json=inferenceDurationUs,proto3" json:"inference_duration_us,omitempty"`
	E2EDurationUs       int64             `protobuf:"varint,13,opt,name=e2e_duration_us,json=e2eDurationUs,proto3" json:"e2e_duration_us,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AlarmEvent) Reset() {
	*x = AlarmEvent{}
	mi := &file_argus_v1_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmEvent) ProtoMessage() {}

func (x *AlarmEvent) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmEvent.ProtoReflect.Descriptor instead.
func (*AlarmEvent) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{0}
}

func (x *AlarmEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AlarmEvent) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *AlarmEvent) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *AlarmEvent) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *AlarmEvent) GetAlgorithmVersion() string {
	if x != nil {
		return x.AlgorithmVersion
	}
	return ""
}

func (x *AlarmEvent) GetAlarmTypeId() string {
	if x != nil {
		return x.AlarmTypeId
	}
	return ""
}

func (x *AlarmEvent) GetWallTimeNs() int64 {
	if x != nil {
		return x.WallTimeNs
	}
	return 0
}

func (x *AlarmEvent) GetTimeSynced() bool {
	if x != nil {
		return x.TimeSynced
	}
	return false
}

func (x *AlarmEvent) GetObjects() []*DetectedObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *AlarmEvent) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *AlarmEvent) GetImageRelPath() string {
	if x != nil {
		return x.ImageRelPath
	}
	return ""
}

func (x *AlarmEvent) GetInferenceDurationUs() int64 {
	if x != nil {
		return x.InferenceDurationUs
	}
	return 0
}

func (x *AlarmEvent) GetE2EDurationUs() int64 {
	if x != nil {
		return x.E2EDurationUs
	}
	return 0
}

type ReportAlarmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alarm         *AlarmEvent            `protobuf:"bytes,1,opt,name=alarm,proto3" json:"alarm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAlarmRequest) Reset() {
	*x = ReportAlarmRequest{}
	mi := &file_argus_v1_app_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAlarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAlarmRequest) ProtoMessage() {}

func (x *ReportAlarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAlarmRequest.ProtoReflect.Descriptor instead.
func (*ReportAlarmRequest) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{1}
}

func (x *ReportAlarmRequest) GetAlarm() *AlarmEvent {
	if x != nil {
		return x.Alarm
	}
	return nil
}

type ReportAlarmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                     // 空串表示接受
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 诊断信息，客户端不得解析其文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportAlarmResponse) Reset() {
	*x = ReportAlarmResponse{}
	mi := &file_argus_v1_app_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportAlarmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportAlarmResponse) ProtoMessage() {}

func (x *ReportAlarmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportAlarmResponse.ProtoReflect.Descriptor instead.
func (*ReportAlarmResponse) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{2}
}

func (x *ReportAlarmResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ReportAlarmResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 车牌识别通行观测事件上报
type PlateObservation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 目标级全局事件 ID = "<instance_run_id>/<batch_event_id>-<track_id>"
	EventId           string       `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	InstanceId        string       `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	CameraId          string       `protobuf:"bytes,3,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	AlgorithmId       string       `protobuf:"bytes,4,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	AlgorithmVersion  string       `protobuf:"bytes,5,opt,name=algorithm_version,json=algorithmVersion,proto3" json:"algorithm_version,omitempty"`
	WallTimeNs        int64        `protobuf:"varint,6,opt,name=wall_time_ns,json=wallTimeNs,proto3" json:"wall_time_ns,omitempty"`
	TimeSynced        bool         `protobuf:"varint,7,opt,name=time_synced,json=timeSynced,proto3" json:"time_synced,omitempty"`
	TrackId           int64        `protobuf:"varint,8,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	PlateText         string       `protobuf:"bytes,9,opt,name=plate_text,json=plateText,proto3" json:"plate_text,omitempty"`
	NormalizedText    string       `protobuf:"bytes,10,opt,name=normalized_text,json=normalizedText,proto3" json:"normalized_text,omitempty"`
	PlateColor        string       `protobuf:"bytes,11,opt,name=plate_color,json=plateColor,proto3" json:"plate_color,omitempty"`
	PlateType         string       `protobuf:"bytes,12,opt,name=plate_type,json=plateType,proto3" json:"plate_type,omitempty"`
	Confidence        float32      `protobuf:"fixed32,13,opt,name=confidence,proto3" json:"confidence,omitempty"`
	OcrConfidence     float32      `protobuf:"fixed32,14,opt,name=ocr_confidence,json=ocrConfidence,proto3" json:"ocr_confidence,omitempty"`
	PlateBbox         *BoundingBox `protobuf:"bytes,15,opt,name=plate_bbox,json=plateBbox,proto3" json:"plate_bbox,omitempty"`
	VehicleBbox       *BoundingBox `protobuf:"bytes,16,opt,name=vehicle_bbox,json=vehicleBbox,proto3" json:"vehicle_bbox,omitempty"`
	ImageId           string       `protobuf:"bytes,17,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	ImageRelPath      string       `protobuf:"bytes,18,opt,name=image_rel_path,json=imageRelPath,proto3" json:"image_rel_path,omitempty"`
	PlateImageId      string       `protobuf:"bytes,19,opt,name=plate_image_id,json=plateImageId,proto3" json:"plate_image_id,omitempty"`
	PlateImageRelPath string       `protobuf:"bytes,20,opt,name=plate_image_rel_path,json=plateImageRelPath,proto3" json:"plate_image_rel_path,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlateObservation) Reset() {
	*x = PlateObservation{}
	mi := &file_argus_v1_app_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlateObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlateObservation) ProtoMessage() {}

func (x *PlateObservation) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlateObservation.ProtoReflect.Descriptor instead.
func (*PlateObservation) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{3}
}

func (x *PlateObservation) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PlateObservation) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *PlateObservation) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *PlateObservation) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *PlateObservation) GetAlgorithmVersion() string {
	if x != nil {
		return x.AlgorithmVersion
	}
	return ""
}

func (x *PlateObservation) GetWallTimeNs() int64 {
	if x != nil {
		return x.WallTimeNs
	}
	return 0
}

func (x *PlateObservation) GetTimeSynced() bool {
	if x != nil {
		return x.TimeSynced
	}
	return false
}

func (x *PlateObservation) GetTrackId() int64 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

func (x *PlateObservation) GetPlateText() string {
	if x != nil {
		return x.PlateText
	}
	return ""
}

func (x *PlateObservation) GetNormalizedText() string {
	if x != nil {
		return x.NormalizedText
	}
	return ""
}

func (x *PlateObservation) GetPlateColor() string {
	if x != nil {
		return x.PlateColor
	}
	return ""
}

func (x *PlateObservation) GetPlateType() string {
	if x != nil {
		return x.PlateType
	}
	return ""
}

func (x *PlateObservation) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *PlateObservation) GetOcrConfidence() float32 {
	if x != nil {
		return x.OcrConfidence
	}
	return 0
}

func (x *PlateObservation) GetPlateBbox() *BoundingBox {
	if x != nil {
		return x.PlateBbox
	}
	return nil
}

func (x *PlateObservation) GetVehicleBbox() *BoundingBox {
	if x != nil {
		return x.VehicleBbox
	}
	return nil
}

func (x *PlateObservation) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *PlateObservation) GetImageRelPath() string {
	if x != nil {
		return x.ImageRelPath
	}
	return ""
}

func (x *PlateObservation) GetPlateImageId() string {
	if x != nil {
		return x.PlateImageId
	}
	return ""
}

func (x *PlateObservation) GetPlateImageRelPath() string {
	if x != nil {
		return x.PlateImageRelPath
	}
	return ""
}

type ReportPlateObservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observation   *PlateObservation      `protobuf:"bytes,1,opt,name=observation,proto3" json:"observation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportPlateObservationRequest) Reset() {
	*x = ReportPlateObservationRequest{}
	mi := &file_argus_v1_app_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportPlateObservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportPlateObservationRequest) ProtoMessage() {}

func (x *ReportPlateObservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportPlateObservationRequest.ProtoReflect.Descriptor instead.
func (*ReportPlateObservationRequest) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{4}
}

func (x *ReportPlateObservationRequest) GetObservation() *PlateObservation {
	if x != nil {
		return x.Observation
	}
	return nil
}

type ReportPlateObservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                     // 空串表示接受
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 诊断信息，客户端不得解析其文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportPlateObservationResponse) Reset() {
	*x = ReportPlateObservationResponse{}
	mi := &file_argus_v1_app_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportPlateObservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportPlateObservationResponse) ProtoMessage() {}

func (x *ReportPlateObservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportPlateObservationResponse.ProtoReflect.Descriptor instead.
func (*ReportPlateObservationResponse) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{5}
}

func (x *ReportPlateObservationResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ReportPlateObservationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 人脸比对候选条目（用于 Top-K 候选匹配排查与溯源）
type FaceCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FaceId        string                 `protobuf:"bytes,1,opt,name=face_id,json=faceId,proto3" json:"face_id,omitempty"`
	PersonId      string                 `protobuf:"bytes,2,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	PersonName    string                 `protobuf:"bytes,3,opt,name=person_name,json=personName,proto3" json:"person_name,omitempty"` // 底库快照
	Similarity    float32                `protobuf:"fixed32,4,opt,name=similarity,proto3" json:"similarity,omitempty"`                 // 归一化 [0,1]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaceCandidate) Reset() {
	*x = FaceCandidate{}
	mi := &file_argus_v1_app_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaceCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceCandidate) ProtoMessage() {}

func (x *FaceCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceCandidate.ProtoReflect.Descriptor instead.
func (*FaceCandidate) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{6}
}

func (x *FaceCandidate) GetFaceId() string {
	if x != nil {
		return x.FaceId
	}
	return ""
}

func (x *FaceCandidate) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *FaceCandidate) GetPersonName() string {
	if x != nil {
		return x.PersonName
	}
	return ""
}

func (x *FaceCandidate) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

// 人脸识别通行观测事件上报
type FaceObservation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 目标级全局事件 ID = "<instance_run_id>/<track_id>"，track 稳定，覆盖上报时不变
	EventId          string           `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	InstanceId       string           `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	CameraId         string           `protobuf:"bytes,3,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	AlgorithmId      string           `protobuf:"bytes,4,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	AlgorithmVersion string           `protobuf:"bytes,5,opt,name=algorithm_version,json=algorithmVersion,proto3" json:"algorithm_version,omitempty"`
	WallTimeNs       int64            `protobuf:"varint,6,opt,name=wall_time_ns,json=wallTimeNs,proto3" json:"wall_time_ns,omitempty"`
	TimeSynced       bool             `protobuf:"varint,7,opt,name=time_synced,json=timeSynced,proto3" json:"time_synced,omitempty"`
	TrackId          int64            `protobuf:"varint,8,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	FaceId           string           `protobuf:"bytes,9,opt,name=face_id,json=faceId,proto3" json:"face_id,omitempty"` // 命中的底库条目
	PersonId         string           `protobuf:"bytes,10,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	PersonName       string           `protobuf:"bytes,11,opt,name=person_name,json=personName,proto3" json:"person_name,omitempty"` // 底库快照，Go 侧直接落库不再回查
	Similarity       float32          `protobuf:"fixed32,12,opt,name=similarity,proto3" json:"similarity,omitempty"`                 // 归一化 [0,1]
	FaceBbox         *BoundingBox     `protobuf:"bytes,13,opt,name=face_bbox,json=faceBbox,proto3" json:"face_bbox,omitempty"`
	ImageId          string           `protobuf:"bytes,14,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"` // 全景图
	ImageRelPath     string           `protobuf:"bytes,15,opt,name=image_rel_path,json=imageRelPath,proto3" json:"image_rel_path,omitempty"`
	FaceImageId      string           `protobuf:"bytes,16,opt,name=face_image_id,json=faceImageId,proto3" json:"face_image_id,omitempty"` // 人脸特写图
	FaceImageRelPath string           `protobuf:"bytes,17,opt,name=face_image_rel_path,json=faceImageRelPath,proto3" json:"face_image_rel_path,omitempty"`
	CameraName       string           `protobuf:"bytes,18,opt,name=camera_name,json=cameraName,proto3" json:"camera_name,omitempty"` // 摄像头名称快照，可为空
	Candidates       []*FaceCandidate `protobuf:"bytes,19,rep,name=candidates,proto3" json:"candidates,omitempty"`                   // Top-K 候选识别结果（通常 Top-5，降序）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FaceObservation) Reset() {
	*x = FaceObservation{}
	mi := &file_argus_v1_app_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaceObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceObservation) ProtoMessage() {}

func (x *FaceObservation) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceObservation.ProtoReflect.Descriptor instead.
func (*FaceObservation) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{7}
}

func (x *FaceObservation) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *FaceObservation) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *FaceObservation) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *FaceObservation) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *FaceObservation) GetAlgorithmVersion() string {
	if x != nil {
		return x.AlgorithmVersion
	}
	return ""
}

func (x *FaceObservation) GetWallTimeNs() int64 {
	if x != nil {
		return x.WallTimeNs
	}
	return 0
}

func (x *FaceObservation) GetTimeSynced() bool {
	if x != nil {
		return x.TimeSynced
	}
	return false
}

func (x *FaceObservation) GetTrackId() int64 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

func (x *FaceObservation) GetFaceId() string {
	if x != nil {
		return x.FaceId
	}
	return ""
}

func (x *FaceObservation) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *FaceObservation) GetPersonName() string {
	if x != nil {
		return x.PersonName
	}
	return ""
}

func (x *FaceObservation) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

func (x *FaceObservation) GetFaceBbox() *BoundingBox {
	if x != nil {
		return x.FaceBbox
	}
	return nil
}

func (x *FaceObservation) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *FaceObservation) GetImageRelPath() string {
	if x != nil {
		return x.ImageRelPath
	}
	return ""
}

func (x *FaceObservation) GetFaceImageId() string {
	if x != nil {
		return x.FaceImageId
	}
	return ""
}

func (x *FaceObservation) GetFaceImageRelPath() string {
	if x != nil {
		return x.FaceImageRelPath
	}
	return ""
}

func (x *FaceObservation) GetCameraName() string {
	if x != nil {
		return x.CameraName
	}
	return ""
}

func (x *FaceObservation) GetCandidates() []*FaceCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type ReportFaceObservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observation   *FaceObservation       `protobuf:"bytes,1,opt,name=observation,proto3" json:"observation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportFaceObservationRequest) Reset() {
	*x = ReportFaceObservationRequest{}
	mi := &file_argus_v1_app_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportFaceObservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportFaceObservationRequest) ProtoMessage() {}

func (x *ReportFaceObservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportFaceObservationRequest.ProtoReflect.Descriptor instead.
func (*ReportFaceObservationRequest) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{8}
}

func (x *ReportFaceObservationRequest) GetObservation() *FaceObservation {
	if x != nil {
		return x.Observation
	}
	return nil
}

type ReportFaceObservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                     // 空串表示接受
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 诊断信息，客户端不得解析其文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportFaceObservationResponse) Reset() {
	*x = ReportFaceObservationResponse{}
	mi := &file_argus_v1_app_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportFaceObservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportFaceObservationResponse) ProtoMessage() {}

func (x *ReportFaceObservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportFaceObservationResponse.ProtoReflect.Descriptor instead.
func (*ReportFaceObservationResponse) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{9}
}

func (x *ReportFaceObservationResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ReportFaceObservationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 通用抓拍事件上报（统一承载人脸、人体、机动车/车牌等多态目标，支持自适应人脸-人体联合抓拍）
type CaptureEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 目标级全局事件 ID = "<instance_run_id>/<track_id>" 或 "<instance_run_id>/<batch_event_id>-<target_seq>"
	EventId             string       `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	InstanceId          string       `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	CameraId            string       `protobuf:"bytes,3,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	CameraName          string       `protobuf:"bytes,4,opt,name=camera_name,json=cameraName,proto3" json:"camera_name,omitempty"`
	AlgorithmId         string       `protobuf:"bytes,5,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	AlgorithmVersion    string       `protobuf:"bytes,6,opt,name=algorithm_version,json=algorithmVersion,proto3" json:"algorithm_version,omitempty"`
	TargetType          string       `protobuf:"bytes,7,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"` // 目标类型: "face" | "person" | "vehicle" | "non_motor" | "generic"
	TrackId             int64        `protobuf:"varint,8,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	WallTimeNs          int64        `protobuf:"varint,9,opt,name=wall_time_ns,json=wallTimeNs,proto3" json:"wall_time_ns,omitempty"`
	TimeSynced          bool         `protobuf:"varint,10,opt,name=time_synced,json=timeSynced,proto3" json:"time_synced,omitempty"`
	Bbox                *BoundingBox `protobuf:"bytes,11,opt,name=bbox,proto3" json:"bbox,omitempty"`                                                                // 主目标归一化坐标框（如人脸框或人体框）
	SubBbox             *BoundingBox `protobuf:"bytes,12,opt,name=sub_bbox,json=subBbox,proto3" json:"sub_bbox,omitempty"`                                           // 附属目标归一化坐标框（如联合抓拍中的人脸框）
	Confidence          float32      `protobuf:"fixed32,13,opt,name=confidence,proto3" json:"confidence,omitempty"`                                                  // 检测置信度 [0, 1]
	QualityScore        float32      `protobuf:"fixed32,14,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`                          // 综合质量分 [0, 1]
	ImageId             string       `protobuf:"bytes,15,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`                                           // 全景大图 ID
	ImageRelPath        string       `protobuf:"bytes,16,opt,name=image_rel_path,json=imageRelPath,proto3" json:"image_rel_path,omitempty"`                          // 全景大图相对路径
	CropImageId         string       `protobuf:"bytes,17,opt,name=crop_image_id,json=cropImageId,proto3" json:"crop_image_id,omitempty"`                             // 主特写切图 ID
	CropImageRelPath    string       `protobuf:"bytes,18,opt,name=crop_image_rel_path,json=cropImageRelPath,proto3" json:"crop_image_rel_path,omitempty"`            // 主特写切图相对路径
	SubCropImageId      string       `protobuf:"bytes,19,opt,name=sub_crop_image_id,json=subCropImageId,proto3" json:"sub_crop_image_id,omitempty"`                  // 附属特写切图 ID (如人脸特写)
	SubCropImageRelPath string       `protobuf:"bytes,20,opt,name=sub_crop_image_rel_path,json=subCropImageRelPath,proto3" json:"sub_crop_image_rel_path,omitempty"` // 附属特写切图相对路径
	IsRecognized        bool         `protobuf:"varint,21,opt,name=is_recognized,json=isRecognized,proto3" json:"is_recognized,omitempty"`                           // 是否同时比中底库（用于存储优先级削峰）
	AttributesJson      string       `protobuf:"bytes,22,opt,name=attributes_json,json=attributesJson,proto3" json:"attributes_json,omitempty"`                      // 异构目标特征属性 JSON
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CaptureEvent) Reset() {
	*x = CaptureEvent{}
	mi := &file_argus_v1_app_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureEvent) ProtoMessage() {}

func (x *CaptureEvent) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureEvent.ProtoReflect.Descriptor instead.
func (*CaptureEvent) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{10}
}

func (x *CaptureEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CaptureEvent) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CaptureEvent) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *CaptureEvent) GetCameraName() string {
	if x != nil {
		return x.CameraName
	}
	return ""
}

func (x *CaptureEvent) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *CaptureEvent) GetAlgorithmVersion() string {
	if x != nil {
		return x.AlgorithmVersion
	}
	return ""
}

func (x *CaptureEvent) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *CaptureEvent) GetTrackId() int64 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

func (x *CaptureEvent) GetWallTimeNs() int64 {
	if x != nil {
		return x.WallTimeNs
	}
	return 0
}

func (x *CaptureEvent) GetTimeSynced() bool {
	if x != nil {
		return x.TimeSynced
	}
	return false
}

func (x *CaptureEvent) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *CaptureEvent) GetSubBbox() *BoundingBox {
	if x != nil {
		return x.SubBbox
	}
	return nil
}

func (x *CaptureEvent) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *CaptureEvent) GetQualityScore() float32 {
	if x != nil {
		return x.QualityScore
	}
	return 0
}

func (x *CaptureEvent) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *CaptureEvent) GetImageRelPath() string {
	if x != nil {
		return x.ImageRelPath
	}
	return ""
}

func (x *CaptureEvent) GetCropImageId() string {
	if x != nil {
		return x.CropImageId
	}
	return ""
}

func (x *CaptureEvent) GetCropImageRelPath() string {
	if x != nil {
		return x.CropImageRelPath
	}
	return ""
}

func (x *CaptureEvent) GetSubCropImageId() string {
	if x != nil {
		return x.SubCropImageId
	}
	return ""
}

func (x *CaptureEvent) GetSubCropImageRelPath() string {
	if x != nil {
		return x.SubCropImageRelPath
	}
	return ""
}

func (x *CaptureEvent) GetIsRecognized() bool {
	if x != nil {
		return x.IsRecognized
	}
	return false
}

func (x *CaptureEvent) GetAttributesJson() string {
	if x != nil {
		return x.AttributesJson
	}
	return ""
}

type ReportCaptureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capture       *CaptureEvent          `protobuf:"bytes,1,opt,name=capture,proto3" json:"capture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportCaptureRequest) Reset() {
	*x = ReportCaptureRequest{}
	mi := &file_argus_v1_app_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCaptureRequest) ProtoMessage() {}

func (x *ReportCaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCaptureRequest.ProtoReflect.Descriptor instead.
func (*ReportCaptureRequest) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{11}
}

func (x *ReportCaptureRequest) GetCapture() *CaptureEvent {
	if x != nil {
		return x.Capture
	}
	return nil
}

type ReportCaptureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                     // 空串表示接受
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 诊断信息，客户端不得解析其文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportCaptureResponse) Reset() {
	*x = ReportCaptureResponse{}
	mi := &file_argus_v1_app_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCaptureResponse) ProtoMessage() {}

func (x *ReportCaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCaptureResponse.ProtoReflect.Descriptor instead.
func (*ReportCaptureResponse) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{12}
}

func (x *ReportCaptureResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ReportCaptureResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 单张时序人脸抓拍快照
type FaceCaptureSnapshot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SnapshotIndex    int32                  `protobuf:"varint,1,opt,name=snapshot_index,json=snapshotIndex,proto3" json:"snapshot_index,omitempty"`
	WallTimeNs       int64                  `protobuf:"varint,2,opt,name=wall_time_ns,json=wallTimeNs,proto3" json:"wall_time_ns,omitempty"`
	TimeSynced       bool                   `protobuf:"varint,3,opt,name=time_synced,json=timeSynced,proto3" json:"time_synced,omitempty"`
	FaceBbox         *BoundingBox           `protobuf:"bytes,4,opt,name=face_bbox,json=faceBbox,proto3" json:"face_bbox,omitempty"`
	QualityScore     float32                `protobuf:"fixed32,5,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`
	Similarity       float32                `protobuf:"fixed32,6,opt,name=similarity,proto3" json:"similarity,omitempty"`
	FaceId           string                 `protobuf:"bytes,7,opt,name=face_id,json=faceId,proto3" json:"face_id,omitempty"`
	PersonId         string                 `protobuf:"bytes,8,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	PersonName       string                 `protobuf:"bytes,9,opt,name=person_name,json=personName,proto3" json:"person_name,omitempty"`
	ImageId          string                 `protobuf:"bytes,10,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	ImageRelPath     string                 `protobuf:"bytes,11,opt,name=image_rel_path,json=imageRelPath,proto3" json:"image_rel_path,omitempty"`
	FaceImageId      string                 `protobuf:"bytes,12,opt,name=face_image_id,json=faceImageId,proto3" json:"face_image_id,omitempty"`
	FaceImageRelPath string                 `protobuf:"bytes,13,opt,name=face_image_rel_path,json=faceImageRelPath,proto3" json:"face_image_rel_path,omitempty"`
	Candidates       []*FaceCandidate       `protobuf:"bytes,14,rep,name=candidates,proto3" json:"candidates,omitempty"` // Top-K 候选识别结果（通常 Top-5，降序）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FaceCaptureSnapshot) Reset() {
	*x = FaceCaptureSnapshot{}
	mi := &file_argus_v1_app_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaceCaptureSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceCaptureSnapshot) ProtoMessage() {}

func (x *FaceCaptureSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceCaptureSnapshot.ProtoReflect.Descriptor instead.
func (*FaceCaptureSnapshot) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{13}
}

func (x *FaceCaptureSnapshot) GetSnapshotIndex() int32 {
	if x != nil {
		return x.SnapshotIndex
	}
	return 0
}

func (x *FaceCaptureSnapshot) GetWallTimeNs() int64 {
	if x != nil {
		return x.WallTimeNs
	}
	return 0
}

func (x *FaceCaptureSnapshot) GetTimeSynced() bool {
	if x != nil {
		return x.TimeSynced
	}
	return false
}

func (x *FaceCaptureSnapshot) GetFaceBbox() *BoundingBox {
	if x != nil {
		return x.FaceBbox
	}
	return nil
}

func (x *FaceCaptureSnapshot) GetQualityScore() float32 {
	if x != nil {
		return x.QualityScore
	}
	return 0
}

func (x *FaceCaptureSnapshot) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

func (x *FaceCaptureSnapshot) GetFaceId() string {
	if x != nil {
		return x.FaceId
	}
	return ""
}

func (x *FaceCaptureSnapshot) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *FaceCaptureSnapshot) GetPersonName() string {
	if x != nil {
		return x.PersonName
	}
	return ""
}

func (x *FaceCaptureSnapshot) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *FaceCaptureSnapshot) GetImageRelPath() string {
	if x != nil {
		return x.ImageRelPath
	}
	return ""
}

func (x *FaceCaptureSnapshot) GetFaceImageId() string {
	if x != nil {
		return x.FaceImageId
	}
	return ""
}

func (x *FaceCaptureSnapshot) GetFaceImageRelPath() string {
	if x != nil {
		return x.FaceImageRelPath
	}
	return ""
}

func (x *FaceCaptureSnapshot) GetCandidates() []*FaceCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

// 人脸抓拍全量事件上报（包含陌生人与已知人，单 Track 支持 1~5 组增量上报）
type FaceCapture struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 目标级全局事件 ID = "<instance_run_id>/<track_id>"
	EventId          string               `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	InstanceId       string               `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	CameraId         string               `protobuf:"bytes,3,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	CameraName       string               `protobuf:"bytes,4,opt,name=camera_name,json=cameraName,proto3" json:"camera_name,omitempty"`
	AlgorithmId      string               `protobuf:"bytes,5,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	AlgorithmVersion string               `protobuf:"bytes,6,opt,name=algorithm_version,json=algorithmVersion,proto3" json:"algorithm_version,omitempty"`
	TrackId          int64                `protobuf:"varint,7,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Snapshot         *FaceCaptureSnapshot `protobuf:"bytes,8,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FaceCapture) Reset() {
	*x = FaceCapture{}
	mi := &file_argus_v1_app_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaceCapture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceCapture) ProtoMessage() {}

func (x *FaceCapture) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceCapture.ProtoReflect.Descriptor instead.
func (*FaceCapture) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{14}
}

func (x *FaceCapture) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *FaceCapture) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *FaceCapture) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *FaceCapture) GetCameraName() string {
	if x != nil {
		return x.CameraName
	}
	return ""
}

func (x *FaceCapture) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *FaceCapture) GetAlgorithmVersion() string {
	if x != nil {
		return x.AlgorithmVersion
	}
	return ""
}

func (x *FaceCapture) GetTrackId() int64 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

func (x *FaceCapture) GetSnapshot() *FaceCaptureSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type ReportFaceCaptureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capture       *FaceCapture           `protobuf:"bytes,1,opt,name=capture,proto3" json:"capture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportFaceCaptureRequest) Reset() {
	*x = ReportFaceCaptureRequest{}
	mi := &file_argus_v1_app_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportFaceCaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportFaceCaptureRequest) ProtoMessage() {}

func (x *ReportFaceCaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportFaceCaptureRequest.ProtoReflect.Descriptor instead.
func (*ReportFaceCaptureRequest) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{15}
}

func (x *ReportFaceCaptureRequest) GetCapture() *FaceCapture {
	if x != nil {
		return x.Capture
	}
	return nil
}

type ReportFaceCaptureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                     // 空串表示接受
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 诊断信息，客户端不得解析其文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportFaceCaptureResponse) Reset() {
	*x = ReportFaceCaptureResponse{}
	mi := &file_argus_v1_app_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportFaceCaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportFaceCaptureResponse) ProtoMessage() {}

func (x *ReportFaceCaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportFaceCaptureResponse.ProtoReflect.Descriptor instead.
func (*ReportFaceCaptureResponse) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{16}
}

func (x *ReportFaceCaptureResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ReportFaceCaptureResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type TaskState struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CameraId            string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	Status              TaskStatusCode         `protobuf:"varint,2,opt,name=status,proto3,enum=argus.v1.TaskStatusCode" json:"status,omitempty"`
	Message             string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	LastFrameWallTimeNs int64                  `protobuf:"varint,4,opt,name=last_frame_wall_time_ns,json=lastFrameWallTimeNs,proto3" json:"last_frame_wall_time_ns,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TaskState) Reset() {
	*x = TaskState{}
	mi := &file_argus_v1_app_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskState) ProtoMessage() {}

func (x *TaskState) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskState.ProtoReflect.Descriptor instead.
func (*TaskState) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{17}
}

func (x *TaskState) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *TaskState) GetStatus() TaskStatusCode {
	if x != nil {
		return x.Status
	}
	return TaskStatusCode_TASK_STATUS_UNSPECIFIED
}

func (x *TaskState) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskState) GetLastFrameWallTimeNs() int64 {
	if x != nil {
		return x.LastFrameWallTimeNs
	}
	return 0
}

type ReportTaskStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskState     *TaskState             `protobuf:"bytes,1,opt,name=task_state,json=taskState,proto3" json:"task_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskStateRequest) Reset() {
	*x = ReportTaskStateRequest{}
	mi := &file_argus_v1_app_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskStateRequest) ProtoMessage() {}

func (x *ReportTaskStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskStateRequest.ProtoReflect.Descriptor instead.
func (*ReportTaskStateRequest) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{18}
}

func (x *ReportTaskStateRequest) GetTaskState() *TaskState {
	if x != nil {
		return x.TaskState
	}
	return nil
}

type ReportTaskStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                     // 空串表示接受
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 诊断信息，客户端不得解析其文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTaskStateResponse) Reset() {
	*x = ReportTaskStateResponse{}
	mi := &file_argus_v1_app_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTaskStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTaskStateResponse) ProtoMessage() {}

func (x *ReportTaskStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTaskStateResponse.ProtoReflect.Descriptor instead.
func (*ReportTaskStateResponse) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{19}
}

func (x *ReportTaskStateResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ReportTaskStateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type InstanceState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Status        InstanceStatusCode     `protobuf:"varint,2,opt,name=status,proto3,enum=argus.v1.InstanceStatusCode" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	CurrentFps    float32                `protobuf:"fixed32,4,opt,name=current_fps,json=currentFps,proto3" json:"current_fps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceState) Reset() {
	*x = InstanceState{}
	mi := &file_argus_v1_app_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceState) ProtoMessage() {}

func (x *InstanceState) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceState.ProtoReflect.Descriptor instead.
func (*InstanceState) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{20}
}

func (x *InstanceState) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *InstanceState) GetStatus() InstanceStatusCode {
	if x != nil {
		return x.Status
	}
	return InstanceStatusCode_INSTANCE_STATUS_UNSPECIFIED
}

func (x *InstanceState) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InstanceState) GetCurrentFps() float32 {
	if x != nil {
		return x.CurrentFps
	}
	return 0
}

type ReportInstanceStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceState *InstanceState         `protobuf:"bytes,1,opt,name=instance_state,json=instanceState,proto3" json:"instance_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportInstanceStateRequest) Reset() {
	*x = ReportInstanceStateRequest{}
	mi := &file_argus_v1_app_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportInstanceStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportInstanceStateRequest) ProtoMessage() {}

func (x *ReportInstanceStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInstanceStateRequest.ProtoReflect.Descriptor instead.
func (*ReportInstanceStateRequest) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{21}
}

func (x *ReportInstanceStateRequest) GetInstanceState() *InstanceState {
	if x != nil {
		return x.InstanceState
	}
	return nil
}

type ReportInstanceStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                     // 空串表示接受
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 诊断信息，客户端不得解析其文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportInstanceStateResponse) Reset() {
	*x = ReportInstanceStateResponse{}
	mi := &file_argus_v1_app_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportInstanceStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportInstanceStateResponse) ProtoMessage() {}

func (x *ReportInstanceStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportInstanceStateResponse.ProtoReflect.Descriptor instead.
func (*ReportInstanceStateResponse) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{22}
}

func (x *ReportInstanceStateResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ReportInstanceStateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 设备遥测指标上报
type ReportMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Telemetry     *DeviceTelemetry       `protobuf:"bytes,1,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportMetricsRequest) Reset() {
	*x = ReportMetricsRequest{}
	mi := &file_argus_v1_app_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportMetricsRequest) ProtoMessage() {}

func (x *ReportMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportMetricsRequest.ProtoReflect.Descriptor instead.
func (*ReportMetricsRequest) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{23}
}

func (x *ReportMetricsRequest) GetTelemetry() *DeviceTelemetry {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

type ReportMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                     // 空串表示接受
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 诊断信息，客户端不得解析其文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportMetricsResponse) Reset() {
	*x = ReportMetricsResponse{}
	mi := &file_argus_v1_app_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportMetricsResponse) ProtoMessage() {}

func (x *ReportMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportMetricsResponse.ProtoReflect.Descriptor instead.
func (*ReportMetricsResponse) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{24}
}

func (x *ReportMetricsResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ReportMetricsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 孤儿图片元数据与对账上报
type OrphanImageEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 全局事件 ID，与 AlarmEvent.event_id 同形（<instance_run_id>/<algo_event_id>）
	EventId       string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ImageId       string `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	RelativePath  string `protobuf:"bytes,3,opt,name=relative_path,json=relativePath,proto3" json:"relative_path,omitempty"`
	CreatedAtNs   int64  `protobuf:"varint,4,opt,name=created_at_ns,json=createdAtNs,proto3" json:"created_at_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrphanImageEntry) Reset() {
	*x = OrphanImageEntry{}
	mi := &file_argus_v1_app_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrphanImageEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrphanImageEntry) ProtoMessage() {}

func (x *OrphanImageEntry) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrphanImageEntry.ProtoReflect.Descriptor instead.
func (*OrphanImageEntry) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{25}
}

func (x *OrphanImageEntry) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *OrphanImageEntry) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *OrphanImageEntry) GetRelativePath() string {
	if x != nil {
		return x.RelativePath
	}
	return ""
}

func (x *OrphanImageEntry) GetCreatedAtNs() int64 {
	if x != nil {
		return x.CreatedAtNs
	}
	return 0
}

type ReportOrphanImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrphanImages  []*OrphanImageEntry    `protobuf:"bytes,1,rep,name=orphan_images,json=orphanImages,proto3" json:"orphan_images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportOrphanImagesRequest) Reset() {
	*x = ReportOrphanImagesRequest{}
	mi := &file_argus_v1_app_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportOrphanImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportOrphanImagesRequest) ProtoMessage() {}

func (x *ReportOrphanImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportOrphanImagesRequest.ProtoReflect.Descriptor instead.
func (*ReportOrphanImagesRequest) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{26}
}

func (x *ReportOrphanImagesRequest) GetOrphanImages() []*OrphanImageEntry {
	if x != nil {
		return x.OrphanImages
	}
	return nil
}

type ReportOrphanImagesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RetainImageIds []string               `protobuf:"bytes,1,rep,name=retain_image_ids,json=retainImageIds,proto3" json:"retain_image_ids,omitempty"` // Go 告知 Engine 需要保留的已引用图片 ID
	DeleteImageIds []string               `protobuf:"bytes,2,rep,name=delete_image_ids,json=deleteImageIds,proto3" json:"delete_image_ids,omitempty"` // Go 告知 Engine 可以安全物理删除的孤儿图片 ID
	Code           string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`                                             // 空串表示接受
	ErrorMessage   string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`         // 诊断信息，客户端不得解析其文本
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportOrphanImagesResponse) Reset() {
	*x = ReportOrphanImagesResponse{}
	mi := &file_argus_v1_app_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportOrphanImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportOrphanImagesResponse) ProtoMessage() {}

func (x *ReportOrphanImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportOrphanImagesResponse.ProtoReflect.Descriptor instead.
func (*ReportOrphanImagesResponse) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{27}
}

func (x *ReportOrphanImagesResponse) GetRetainImageIds() []string {
	if x != nil {
		return x.RetainImageIds
	}
	return nil
}

func (x *ReportOrphanImagesResponse) GetDeleteImageIds() []string {
	if x != nil {
		return x.DeleteImageIds
	}
	return nil
}

func (x *ReportOrphanImagesResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ReportOrphanImagesResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 期望状态拉取请求
type GetDesiredStateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentRevision uint64                 `protobuf:"varint,1,opt,name=current_revision,json=currentRevision,proto3" json:"current_revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetDesiredStateRequest) Reset() {
	*x = GetDesiredStateRequest{}
	mi := &file_argus_v1_app_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDesiredStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDesiredStateRequest) ProtoMessage() {}

func (x *GetDesiredStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDesiredStateRequest.ProtoReflect.Descriptor instead.
func (*GetDesiredStateRequest) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{28}
}

func (x *GetDesiredStateRequest) GetCurrentRevision() uint64 {
	if x != nil {
		return x.CurrentRevision
	}
	return 0
}

type GetDesiredStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DesiredState  *DesiredState          `protobuf:"bytes,1,opt,name=desired_state,json=desiredState,proto3" json:"desired_state,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`                                     // 空串表示成功
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 诊断信息，客户端不得解析其文本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDesiredStateResponse) Reset() {
	*x = GetDesiredStateResponse{}
	mi := &file_argus_v1_app_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDesiredStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDesiredStateResponse) ProtoMessage() {}

func (x *GetDesiredStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDesiredStateResponse.ProtoReflect.Descriptor instead.
func (*GetDesiredStateResponse) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{29}
}

func (x *GetDesiredStateResponse) GetDesiredState() *DesiredState {
	if x != nil {
		return x.DesiredState
	}
	return nil
}

func (x *GetDesiredStateResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetDesiredStateResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 单条人脸底库条目
type FaceGalleryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FaceId        string                 `protobuf:"bytes,1,opt,name=face_id,json=faceId,proto3" json:"face_id,omitempty"`
	PersonId      string                 `protobuf:"bytes,2,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	PersonName    string                 `protobuf:"bytes,3,opt,name=person_name,json=personName,proto3" json:"person_name,omitempty"` // 冗余，供 Engine 上报时携带历史快照
	Embedding     []byte                 `protobuf:"bytes,4,opt,name=embedding,proto3" json:"embedding,omitempty"`                     // 512 维 L2 归一化 float32 小端字节流（精确 2048 字节）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaceGalleryEntry) Reset() {
	*x = FaceGalleryEntry{}
	mi := &file_argus_v1_app_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaceGalleryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceGalleryEntry) ProtoMessage() {}

func (x *FaceGalleryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceGalleryEntry.ProtoReflect.Descriptor instead.
func (*FaceGalleryEntry) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{30}
}

func (x *FaceGalleryEntry) GetFaceId() string {
	if x != nil {
		return x.FaceId
	}
	return ""
}

func (x *FaceGalleryEntry) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *FaceGalleryEntry) GetPersonName() string {
	if x != nil {
		return x.PersonName
	}
	return ""
}

func (x *FaceGalleryEntry) GetEmbedding() []byte {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type GetFaceGalleryRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CurrentGalleryRevision uint64                 `protobuf:"varint,1,opt,name=current_gallery_revision,json=currentGalleryRevision,proto3" json:"current_gallery_revision,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetFaceGalleryRequest) Reset() {
	*x = GetFaceGalleryRequest{}
	mi := &file_argus_v1_app_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFaceGalleryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFaceGalleryRequest) ProtoMessage() {}

func (x *GetFaceGalleryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFaceGalleryRequest.ProtoReflect.Descriptor instead.
func (*GetFaceGalleryRequest) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{31}
}

func (x *GetFaceGalleryRequest) GetCurrentGalleryRevision() uint64 {
	if x != nil {
		return x.CurrentGalleryRevision
	}
	return 0
}

type GetFaceGalleryResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GalleryRevision uint64                 `protobuf:"varint,1,opt,name=gallery_revision,json=galleryRevision,proto3" json:"gallery_revision,omitempty"`
	Changed         bool                   `protobuf:"varint,2,opt,name=changed,proto3" json:"changed,omitempty"` // false 时 entries 必为空
	Entries         []*FaceGalleryEntry    `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`  // changed=true 时为全量快照
	Code            string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetFaceGalleryResponse) Reset() {
	*x = GetFaceGalleryResponse{}
	mi := &file_argus_v1_app_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFaceGalleryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFaceGalleryResponse) ProtoMessage() {}

func (x *GetFaceGalleryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_app_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFaceGalleryResponse.ProtoReflect.Descriptor instead.
func (*GetFaceGalleryResponse) Descriptor() ([]byte, []int) {
	return file_argus_v1_app_proto_rawDescGZIP(), []int{32}
}

func (x *GetFaceGalleryResponse) GetGalleryRevision() uint64 {
	if x != nil {
		return x.GalleryRevision
	}
	return 0
}

func (x *GetFaceGalleryResponse) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *GetFaceGalleryResponse) GetEntries() []*FaceGalleryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetFaceGalleryResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GetFaceGalleryResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_argus_v1_app_proto protoreflect.FileDescriptor

const file_argus_v1_app_proto_rawDesc = "" +
	"\n" +
	"\x12argus/v1/app.proto\x12\bargus.v1\x1a\x15argus/v1/common.proto\x1a\x15argus/v1/engine.proto\"\xed\x03\n" +
	"\n" +
	"AlarmEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1b\n" +
	"\tcamera_id\x18\x03 \x01(\tR\bcameraId\x12!\n" +
	"\falgorithm_id\x18\x04 \x01(\tR\valgorithmId\x12+\n" +
	"\x11algorithm_version\x18\x05 \x01(\tR\x10algorithmVersion\x12\"\n" +
	"\ralarm_type_id\x18\x06 \x01(\tR\valarmTypeId\x12 \n" +
	"\fwall_time_ns\x18\a \x01(\x03R\n" +
	"wallTimeNs\x12\x1f\n" +
	"\vtime_synced\x18\b \x01(\bR\n" +
	"timeSynced\x122\n" +
	"\aobjects\x18\t \x03(\v2\x18.argus.v1.DetectedObjectR\aobjects\x12\x19\n" +
	"\bimage_id\x18\n" +
	" \x01(\tR\aimageId\x12$\n" +
	"\x0eimage_rel_path\x18\v \x01(\tR\fimageRelPath\x122\n" +
	"\x15inference_duration_us\x18\f \x01(\x03R\x13inferenceDurationUs\x12&\n" +
	"\x0fe2e_duration_us\x18\r \x01(\x03R\re2eDurationUs\"@\n" +
	"\x12ReportAlarmRequest\x12*\n" +
	"\x05alarm\x18\x01 \x01(\v2\x14.argus.v1.AlarmEventR\x05alarm\"N\n" +
	"\x13ReportAlarmResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xf0\x05\n" +
	"\x10PlateObservation\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1b\n" +
	"\tcamera_id\x18\x03 \x01(\tR\bcameraId\x12!\n" +
	"\falgorithm_id\x18\x04 \x01(\tR\valgorithmId\x12+\n" +
	"\x11algorithm_version\x18\x05 \x01(\tR\x10algorithmVersion\x12 \n" +
	"\fwall_time_ns\x18\x06 \x01(\x03R\n" +
	"wallTimeNs\x12\x1f\n" +
	"\vtime_synced\x18\a \x01(\bR\n" +
	"timeSynced\x12\x19\n" +
	"\btrack_id\x18\b \x01(\x03R\atrackId\x12\x1d\n" +
	"\n" +
	"plate_text\x18\t \x01(\tR\tplateText\x12'\n" +
	"\x0fnormalized_text\x18\n" +
	" \x01(\tR\x0enormalizedText\x12\x1f\n" +
	"\vplate_color\x18\v \x01(\tR\n" +
	"plateColor\x12\x1d\n" +
	"\n" +
	"plate_type\x18\f \x01(\tR\tplateType\x12\x1e\n" +
	"\n" +
	"confidence\x18\r \x01(\x02R\n" +
	"confidence\x12%\n" +
	"\x0eocr_confidence\x18\x0e \x01(\x02R\rocrConfidence\x124\n" +
	"\n" +
	"plate_bbox\x18\x0f \x01(\v2\x15.argus.v1.BoundingBoxR\tplateBbox\x128\n" +
	"\fvehicle_bbox\x18\x10 \x01(\v2\x15.argus.v1.BoundingBoxR\vvehicleBbox\x12\x19\n" +
	"\bimage_id\x18\x11 \x01(\tR\aimageId\x12$\n" +
	"\x0eimage_rel_path\x18\x12 \x01(\tR\fimageRelPath\x12$\n" +
	"\x0eplate_image_id\x18\x13 \x01(\tR\fplateImageId\x12/\n" +
	"\x14plate_image_rel_path\x18\x14 \x01(\tR\x11plateImageRelPath\"]\n" +
	"\x1dReportPlateObservationRequest\x12<\n" +
	"\vobservation\x18\x01 \x01(\v2\x1a.argus.v1.PlateObservationR\vobservation\"Y\n" +
	"\x1eReportPlateObservationResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x86\x01\n" +
	"\rFaceCandidate\x12\x17\n" +
	"\aface_id\x18\x01 \x01(\tR\x06faceId\x12\x1b\n" +
	"\tperson_id\x18\x02 \x01(\tR\bpersonId\x12\x1f\n" +
	"\vperson_name\x18\x03 \x01(\tR\n" +
	"personName\x12\x1e\n" +
	"\n" +
	"similarity\x18\x04 \x01(\x02R\n" +
	"similarity\"\xb1\x05\n" +
	"\x0fFaceObservation\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1b\n" +
	"\tcamera_id\x18\x03 \x01(\tR\bcameraId\x12!\n" +
	"\falgorithm_id\x18\x04 \x01(\tR\valgorithmId\x12+\n" +
	"\x11algorithm_version\x18\x05 \x01(\tR\x10algorithmVersion\x12 \n" +
	"\fwall_time_ns\x18\x06 \x01(\x03R\n" +
	"wallTimeNs\x12\x1f\n" +
	"\vtime_synced\x18\a \x01(\bR\n" +
	"timeSynced\x12\x19\n" +
	"\btrack_id\x18\b \x01(\x03R\atrackId\x12\x17\n" +
	"\aface_id\x18\t \x01(\tR\x06faceId\x12\x1b\n" +
	"\tperson_id\x18\n" +
	" \x01(\tR\bpersonId\x12\x1f\n" +
	"\vperson_name\x18\v \x01(\tR\n" +
	"personName\x12\x1e\n" +
	"\n" +
	"similarity\x18\f \x01(\x02R\n" +
	"similarity\x122\n" +
	"\tface_bbox\x18\r \x01(\v2\x15.argus.v1.BoundingBoxR\bfaceBbox\x12\x19\n" +
	"\bimage_id\x18\x0e \x01(\tR\aimageId\x12$\n" +
	"\x0eimage_rel_path\x18\x0f \x01(\tR\fimageRelPath\x12\"\n" +
	"\rface_image_id\x18\x10 \x01(\tR\vfaceImageId\x12-\n" +
	"\x13face_image_rel_path\x18\x11 \x01(\tR\x10faceImageRelPath\x12\x1f\n" +
	"\vcamera_name\x18\x12 \x01(\tR\n" +
	"cameraName\x127\n" +
	"\n" +
	"candidates\x18\x13 \x03(\v2\x17.argus.v1.FaceCandidateR\n" +
	"candidates\"[\n" +
	"\x1cReportFaceObservationRequest\x12;\n" +
	"\vobservation\x18\x01 \x01(\v2\x19.argus.v1.FaceObservationR\vobservation\"X\n" +
	"\x1dReportFaceObservationResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xbc\x06\n" +
	"\fCaptureEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1b\n" +
	"\tcamera_id\x18\x03 \x01(\tR\bcameraId\x12\x1f\n" +
	"\vcamera_name\x18\x04 \x01(\tR\n" +
	"cameraName\x12!\n" +
	"\falgorithm_id\x18\x05 \x01(\tR\valgorithmId\x12+\n" +
	"\x11algorithm_version\x18\x06 \x01(\tR\x10algorithmVersion\x12\x1f\n" +
	"\vtarget_type\x18\a \x01(\tR\n" +
	"targetType\x12\x19\n" +
	"\btrack_id\x18\b \x01(\x03R\atrackId\x12 \n" +
	"\fwall_time_ns\x18\t \x01(\x03R\n" +
	"wallTimeNs\x12\x1f\n" +
	"\vtime_synced\x18\n" +
	" \x01(\bR\n" +
	"timeSynced\x12)\n" +
	"\x04bbox\x18\v \x01(\v2\x15.argus.v1.BoundingBoxR\x04bbox\x120\n" +
	"\bsub_bbox\x18\f \x01(\v2\x15.argus.v1.BoundingBoxR\asubBbox\x12\x1e\n" +
	"\n" +
	"confidence\x18\r \x01(\x02R\n" +
	"confidence\x12#\n" +
	"\rquality_score\x18\x0e \x01(\x02R\fqualityScore\x12\x19\n" +
	"\bimage_id\x18\x0f \x01(\tR\aimageId\x12$\n" +
	"\x0eimage_rel_path\x18\x10 \x01(\tR\fimageRelPath\x12\"\n" +
	"\rcrop_image_id\x18\x11 \x01(\tR\vcropImageId\x12-\n" +
	"\x13crop_image_rel_path\x18\x12 \x01(\tR\x10cropImageRelPath\x12)\n" +
	"\x11sub_crop_image_id\x18\x13 \x01(\tR\x0esubCropImageId\x124\n" +
	"\x17sub_crop_image_rel_path\x18\x14 \x01(\tR\x13subCropImageRelPath\x12#\n" +
	"\ris_recognized\x18\x15 \x01(\bR\fisRecognized\x12'\n" +
	"\x0fattributes_json\x18\x16 \x01(\tR\x0eattributesJson\"H\n" +
	"\x14ReportCaptureRequest\x120\n" +
	"\acapture\x18\x01 \x01(\v2\x16.argus.v1.CaptureEventR\acapture\"P\n" +
	"\x15ReportCaptureResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x9c\x04\n" +
	"\x13FaceCaptureSnapshot\x12%\n" +
	"\x0esnapshot_index\x18\x01 \x01(\x05R\rsnapshotIndex\x12 \n" +
	"\fwall_time_ns\x18\x02 \x01(\x03R\n" +
	"wallTimeNs\x12\x1f\n" +
	"\vtime_synced\x18\x03 \x01(\bR\n" +
	"timeSynced\x122\n" +
	"\tface_bbox\x18\x04 \x01(\v2\x15.argus.v1.BoundingBoxR\bfaceBbox\x12#\n" +
	"\rquality_score\x18\x05 \x01(\x02R\fqualityScore\x12\x1e\n" +
	"\n" +
	"similarity\x18\x06 \x01(\x02R\n" +
	"similarity\x12\x17\n" +
	"\aface_id\x18\a \x01(\tR\x06faceId\x12\x1b\n" +
	"\tperson_id\x18\b \x01(\tR\bpersonId\x12\x1f\n" +
	"\vperson_name\x18\t \x01(\tR\n" +
	"personName\x12\x19\n" +
	"\bimage_id\x18\n" +
	" \x01(\tR\aimageId\x12$\n" +
	"\x0eimage_rel_path\x18\v \x01(\tR\fimageRelPath\x12\"\n" +
	"\rface_image_id\x18\f \x01(\tR\vfaceImageId\x12-\n" +
	"\x13face_image_rel_path\x18\r \x01(\tR\x10faceImageRelPath\x127\n" +
	"\n" +
	"candidates\x18\x0e \x03(\v2\x17.argus.v1.FaceCandidateR\n" +
	"candidates\"\xad\x02\n" +
	"\vFaceCapture\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1b\n" +
	"\tcamera_id\x18\x03 \x01(\tR\bcameraId\x12\x1f\n" +
	"\vcamera_name\x18\x04 \x01(\tR\n" +
	"cameraName\x12!\n" +
	"\falgorithm_id\x18\x05 \x01(\tR\valgorithmId\x12+\n" +
	"\x11algorithm_version\x18\x06 \x01(\tR\x10algorithmVersion\x12\x19\n" +
	"\btrack_id\x18\a \x01(\x03R\atrackId\x129\n" +
	"\bsnapshot\x18\b \x01(\v2\x1d.argus.v1.FaceCaptureSnapshotR\bsnapshot\"K\n" +
	"\x18ReportFaceCaptureRequest\x12/\n" +
	"\acapture\x18\x01 \x01(\v2\x15.argus.v1.FaceCaptureR\acapture\"T\n" +
	"\x19ReportFaceCaptureResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xaa\x01\n" +
	"\tTaskState\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.argus.v1.TaskStatusCodeR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x124\n" +
	"\x17last_frame_wall_time_ns\x18\x04 \x01(\x03R\x13lastFrameWallTimeNs\"L\n" +
	"\x16ReportTaskStateRequest\x122\n" +
	"\n" +
	"task_state\x18\x01 \x01(\v2\x13.argus.v1.TaskStateR\ttaskState\"R\n" +
	"\x17ReportTaskStateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xa1\x01\n" +
	"\rInstanceState\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.argus.v1.InstanceStatusCodeR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1f\n" +
	"\vcurrent_fps\x18\x04 \x01(\x02R\n" +
	"currentFps\"\\\n" +
	"\x1aReportInstanceStateRequest\x12>\n" +
	"\x0einstance_state\x18\x01 \x01(\v2\x17.argus.v1.InstanceStateR\rinstanceState\"V\n" +
	"\x1bReportInstanceStateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"O\n" +
	"\x14ReportMetricsRequest\x127\n" +
	"\ttelemetry\x18\x01 \x01(\v2\x19.argus.v1.DeviceTelemetryR\ttelemetry\"P\n" +
	"\x15ReportMetricsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x91\x01\n" +
	"\x10OrphanImageEntry\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x19\n" +
	"\bimage_id\x18\x02 \x01(\tR\aimageId\x12#\n" +
	"\rrelative_path\x18\x03 \x01(\tR\frelativePath\x12\"\n" +
	"\rcreated_at_ns\x18\x04 \x01(\x03R\vcreatedAtNs\"\\\n" +
	"\x19ReportOrphanImagesRequest\x12?\n" +
	"\rorphan_images\x18\x01 \x03(\v2\x1a.argus.v1.OrphanImageEntryR\forphanImages\"\xa9\x01\n" +
	"\x1aReportOrphanImagesResponse\x12(\n" +
	"\x10retain_image_ids\x18\x01 \x03(\tR\x0eretainImageIds\x12(\n" +
	"\x10delete_image_ids\x18\x02 \x03(\tR\x0edeleteImageIds\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"C\n" +
	"\x16GetDesiredStateRequest\x12)\n" +
	"\x10current_revision\x18\x01 \x01(\x04R\x0fcurrentRevision\"\x8f\x01\n" +
	"\x17GetDesiredStateResponse\x12;\n" +
	"\rdesired_state\x18\x01 \x01(\v2\x16.argus.v1.DesiredStateR\fdesiredState\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x87\x01\n" +
	"\x10FaceGalleryEntry\x12\x17\n" +
	"\aface_id\x18\x01 \x01(\tR\x06faceId\x12\x1b\n" +
	"\tperson_id\x18\x02 \x01(\tR\bpersonId\x12\x1f\n" +
	"\vperson_name\x18\x03 \x01(\tR\n" +
	"personName\x12\x1c\n" +
	"\tembedding\x18\x04 \x01(\fR\tembedding\"Q\n" +
	"\x15GetFaceGalleryRequest\x128\n" +
	"\x18current_gallery_revision\x18\x01 \x01(\x04R\x16currentGalleryRevision\"\xcc\x01\n" +
	"\x16GetFaceGalleryResponse\x12)\n" +
	"\x10gallery_revision\x18\x01 \x01(\x04R\x0fgalleryRevision\x12\x18\n" +
	"\achanged\x18\x02 \x01(\bR\achanged\x124\n" +
	"\aentries\x18\x03 \x03(\v2\x1a.argus.v1.FaceGalleryEntryR\aentries\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage*\xc8\x01\n" +
	"\x0eTaskStatusCode\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TASK_STATUS_STARTING\x10\x01\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x02\x12\x18\n" +
	"\x14TASK_STATUS_DEGRADED\x10\x03\x12\x1c\n" +
	"\x18TASK_STATUS_RECONNECTING\x10\x04\x12\x17\n" +
	"\x13TASK_STATUS_STOPPED\x10\x05\x12\x15\n" +
	"\x11TASK_STATUS_ERROR\x10\x06*\xc6\x01\n" +
	"\x12InstanceStatusCode\x12\x1f\n" +
	"\x1bINSTANCE_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18INSTANCE_STATUS_STARTING\x10\x01\x12\x1b\n" +
	"\x17INSTANCE_STATUS_RUNNING\x10\x02\x12\x1c\n" +
	"\x18INSTANCE_STATUS_DEGRADED\x10\x03\x12\x1b\n" +
	"\x17INSTANCE_STATUS_STOPPED\x10\x04\x12\x19\n" +
	"\x15INSTANCE_STATUS_ERROR\x10\x052\xc2\x01\n" +
	"\x13ControlPlaneService\x12V\n" +
	"\x0fGetDesiredState\x12 .argus.v1.GetDesiredStateRequest\x1a!.argus.v1.GetDesiredStateResponse\x12S\n" +
	"\x0eGetFaceGallery\x12\x1f.argus.v1.GetFaceGalleryRequest\x1a .argus.v1.GetFaceGalleryResponse2\xd1\x06\n" +
	"\rReportService\x12J\n" +
	"\vReportAlarm\x12\x1c.argus.v1.ReportAlarmRequest\x1a\x1d.argus.v1.ReportAlarmResponse\x12k\n" +
	"\x16ReportPlateObservation\x12'.argus.v1.ReportPlateObservationRequest\x1a(.argus.v1.ReportPlateObservationResponse\x12h\n" +
	"\x15ReportFaceObservation\x12&.argus.v1.ReportFaceObservationRequest\x1a'.argus.v1.ReportFaceObservationResponse\x12\\\n" +
	"\x11ReportFaceCapture\x12\".argus.v1.ReportFaceCaptureRequest\x1a#.argus.v1.ReportFaceCaptureResponse\x12P\n" +
	"\rReportCapture\x12\x1e.argus.v1.ReportCaptureRequest\x1a\x1f.argus.v1.ReportCaptureResponse\x12V\n" +
	"\x0fReportTaskState\x12 .argus.v1.ReportTaskStateRequest\x1a!.argus.v1.ReportTaskStateResponse\x12b\n" +
	"\x13ReportInstanceState\x12$.argus.v1.ReportInstanceStateRequest\x1a%.argus.v1.ReportInstanceStateResponse\x12P\n" +
	"\rReportMetrics\x12\x1e.argus.v1.ReportMetricsRequest\x1a\x1f.argus.v1.ReportMetricsResponse\x12_\n" +
	"\x12ReportOrphanImages\x12#.argus.v1.ReportOrphanImagesRequest\x1a$.argus.v1.ReportOrphanImagesResponseB+Z)argus/app/internal/proto/argus/v1;argusv1b\x06proto3"

var (
	file_argus_v1_app_proto_rawDescOnce sync.Once
	file_argus_v1_app_proto_rawDescData []byte
)

func file_argus_v1_app_proto_rawDescGZIP() []byte {
	file_argus_v1_app_proto_rawDescOnce.Do(func() {
		file_argus_v1_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_argus_v1_app_proto_rawDesc), len(file_argus_v1_app_proto_rawDesc)))
	})
	return file_argus_v1_app_proto_rawDescData
}

var file_argus_v1_app_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_argus_v1_app_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_argus_v1_app_proto_goTypes = []any{
	(TaskStatusCode)(0),                    // 0: argus.v1.TaskStatusCode
	(InstanceStatusCode)(0),                // 1: argus.v1.InstanceStatusCode
	(*AlarmEvent)(nil),                     // 2: argus.v1.AlarmEvent
	(*ReportAlarmRequest)(nil),             // 3: argus.v1.ReportAlarmRequest
	(*ReportAlarmResponse)(nil),            // 4: argus.v1.ReportAlarmResponse
	(*PlateObservation)(nil),               // 5: argus.v1.PlateObservation
	(*ReportPlateObservationRequest)(nil),  // 6: argus.v1.ReportPlateObservationRequest
	(*ReportPlateObservationResponse)(nil), // 7: argus.v1.ReportPlateObservationResponse
	(*FaceCandidate)(nil),                  // 8: argus.v1.FaceCandidate
	(*FaceObservation)(nil),                // 9: argus.v1.FaceObservation
	(*ReportFaceObservationRequest)(nil),   // 10: argus.v1.ReportFaceObservationRequest
	(*ReportFaceObservationResponse)(nil),  // 11: argus.v1.ReportFaceObservationResponse
	(*CaptureEvent)(nil),                   // 12: argus.v1.CaptureEvent
	(*ReportCaptureRequest)(nil),           // 13: argus.v1.ReportCaptureRequest
	(*ReportCaptureResponse)(nil),          // 14: argus.v1.ReportCaptureResponse
	(*FaceCaptureSnapshot)(nil),            // 15: argus.v1.FaceCaptureSnapshot
	(*FaceCapture)(nil),                    // 16: argus.v1.FaceCapture
	(*ReportFaceCaptureRequest)(nil),       // 17: argus.v1.ReportFaceCaptureRequest
	(*ReportFaceCaptureResponse)(nil),      // 18: argus.v1.ReportFaceCaptureResponse
	(*TaskState)(nil),                      // 19: argus.v1.TaskState
	(*ReportTaskStateRequest)(nil),         // 20: argus.v1.ReportTaskStateRequest
	(*ReportTaskStateResponse)(nil),        // 21: argus.v1.ReportTaskStateResponse
	(*InstanceState)(nil),                  // 22: argus.v1.InstanceState
	(*ReportInstanceStateRequest)(nil),     // 23: argus.v1.ReportInstanceStateRequest
	(*ReportInstanceStateResponse)(nil),    // 24: argus.v1.ReportInstanceStateResponse
	(*ReportMetricsRequest)(nil),           // 25: argus.v1.ReportMetricsRequest
	(*ReportMetricsResponse)(nil),          // 26: argus.v1.ReportMetricsResponse
	(*OrphanImageEntry)(nil),               // 27: argus.v1.OrphanImageEntry
	(*ReportOrphanImagesRequest)(nil),      // 28: argus.v1.ReportOrphanImagesRequest
	(*ReportOrphanImagesResponse)(nil),     // 29: argus.v1.ReportOrphanImagesResponse
	(*GetDesiredStateRequest)(nil),         // 30: argus.v1.GetDesiredStateRequest
	(*GetDesiredStateResponse)(nil),        // 31: argus.v1.GetDesiredStateResponse
	(*FaceGalleryEntry)(nil),               // 32: argus.v1.FaceGalleryEntry
	(*GetFaceGalleryRequest)(nil),          // 33: argus.v1.GetFaceGalleryRequest
	(*GetFaceGalleryResponse)(nil),         // 34: argus.v1.GetFaceGalleryResponse
	(*DetectedObject)(nil),                 // 35: argus.v1.DetectedObject
	(*BoundingBox)(nil),                    // 36: argus.v1.BoundingBox
	(*DeviceTelemetry)(nil),                // 37: argus.v1.DeviceTelemetry
	(*DesiredState)(nil),                   // 38: argus.v1.DesiredState
}
var file_argus_v1_app_proto_depIdxs = []int32{
	35, // 0: argus.v1.AlarmEvent.objects:type_name -> argus.v1.DetectedObject
	2,  // 1: argus.v1.ReportAlarmRequest.alarm:type_name -> argus.v1.AlarmEvent
	36, // 2: argus.v1.PlateObservation.plate_bbox:type_name -> argus.v1.BoundingBox
	36, // 3: argus.v1.PlateObservation.vehicle_bbox:type_name -> argus.v1.BoundingBox
	5,  // 4: argus.v1.ReportPlateObservationRequest.observation:type_name -> argus.v1.PlateObservation
	36, // 5: argus.v1.FaceObservation.face_bbox:type_name -> argus.v1.BoundingBox
	8,  // 6: argus.v1.FaceObservation.candidates:type_name -> argus.v1.FaceCandidate
	9,  // 7: argus.v1.ReportFaceObservationRequest.observation:type_name -> argus.v1.FaceObservation
	36, // 8: argus.v1.CaptureEvent.bbox:type_name -> argus.v1.BoundingBox
	36, // 9: argus.v1.CaptureEvent.sub_bbox:type_name -> argus.v1.BoundingBox
	12, // 10: argus.v1.ReportCaptureRequest.capture:type_name -> argus.v1.CaptureEvent
	36, // 11: argus.v1.FaceCaptureSnapshot.face_bbox:type_name -> argus.v1.BoundingBox
	8,  // 12: argus.v1.FaceCaptureSnapshot.candidates:type_name -> argus.v1.FaceCandidate
	15, // 13: argus.v1.FaceCapture.snapshot:type_name -> argus.v1.FaceCaptureSnapshot
	16, // 14: argus.v1.ReportFaceCaptureRequest.capture:type_name -> argus.v1.FaceCapture
	0,  // 15: argus.v1.TaskState.status:type_name -> argus.v1.TaskStatusCode
	19, // 16: argus.v1.ReportTaskStateRequest.task_state:type_name -> argus.v1.TaskState
	1,  // 17: argus.v1.InstanceState.status:type_name -> argus.v1.InstanceStatusCode
	22, // 18: argus.v1.ReportInstanceStateRequest.instance_state:type_name -> argus.v1.InstanceState
	37, // 19: argus.v1.ReportMetricsRequest.telemetry:type_name -> argus.v1.DeviceTelemetry
	27, // 20: argus.v1.ReportOrphanImagesRequest.orphan_images:type_name -> argus.v1.OrphanImageEntry
	38, // 21: argus.v1.GetDesiredStateResponse.desired_state:type_name -> argus.v1.DesiredState
	32, // 22: argus.v1.GetFaceGalleryResponse.entries:type_name -> argus.v1.FaceGalleryEntry
	30, // 23: argus.v1.ControlPlaneService.GetDesiredState:input_type -> argus.v1.GetDesiredStateRequest
	33, // 24: argus.v1.ControlPlaneService.GetFaceGallery:input_type -> argus.v1.GetFaceGalleryRequest
	3,  // 25: argus.v1.ReportService.ReportAlarm:input_type -> argus.v1.ReportAlarmRequest
	6,  // 26: argus.v1.ReportService.ReportPlateObservation:input_type -> argus.v1.ReportPlateObservationRequest
	10, // 27: argus.v1.ReportService.ReportFaceObservation:input_type -> argus.v1.ReportFaceObservationRequest
	17, // 28: argus.v1.ReportService.ReportFaceCapture:input_type -> argus.v1.ReportFaceCaptureRequest
	13, // 29: argus.v1.ReportService.ReportCapture:input_type -> argus.v1.ReportCaptureRequest
	20, // 30: argus.v1.ReportService.ReportTaskState:input_type -> argus.v1.ReportTaskStateRequest
	23, // 31: argus.v1.ReportService.ReportInstanceState:input_type -> argus.v1.ReportInstanceStateRequest
	25, // 32: argus.v1.ReportService.ReportMetrics:input_type -> argus.v1.ReportMetricsRequest
	28, // 33: argus.v1.ReportService.ReportOrphanImages:input_type -> argus.v1.ReportOrphanImagesRequest
	31, // 34: argus.v1.ControlPlaneService.GetDesiredState:output_type -> argus.v1.GetDesiredStateResponse
	34, // 35: argus.v1.ControlPlaneService.GetFaceGallery:output_type -> argus.v1.GetFaceGalleryResponse
	4,  // 36: argus.v1.ReportService.ReportAlarm:output_type -> argus.v1.ReportAlarmResponse
	7,  // 37: argus.v1.ReportService.ReportPlateObservation:output_type -> argus.v1.ReportPlateObservationResponse
	11, // 38: argus.v1.ReportService.ReportFaceObservation:output_type -> argus.v1.ReportFaceObservationResponse
	18, // 39: argus.v1.ReportService.ReportFaceCapture:output_type -> argus.v1.ReportFaceCaptureResponse
	14, // 40: argus.v1.ReportService.ReportCapture:output_type -> argus.v1.ReportCaptureResponse
	21, // 41: argus.v1.ReportService.ReportTaskState:output_type -> argus.v1.ReportTaskStateResponse
	24, // 42: argus.v1.ReportService.ReportInstanceState:output_type -> argus.v1.ReportInstanceStateResponse
	26, // 43: argus.v1.ReportService.ReportMetrics:output_type -> argus.v1.ReportMetricsResponse
	29, // 44: argus.v1.ReportService.ReportOrphanImages:output_type -> argus.v1.ReportOrphanImagesResponse
	34, // [34:45] is the sub-list for method output_type
	23, // [23:34] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_argus_v1_app_proto_init() }
func file_argus_v1_app_proto_init() {
	if File_argus_v1_app_proto != nil {
		return
	}
	file_argus_v1_common_proto_init()
	file_argus_v1_engine_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_argus_v1_app_proto_rawDesc), len(file_argus_v1_app_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_argus_v1_app_proto_goTypes,
		DependencyIndexes: file_argus_v1_app_proto_depIdxs,
		EnumInfos:         file_argus_v1_app_proto_enumTypes,
		MessageInfos:      file_argus_v1_app_proto_msgTypes,
	}.Build()
	File_argus_v1_app_proto = out.File
	file_argus_v1_app_proto_goTypes = nil
	file_argus_v1_app_proto_depIdxs = nil
}
