// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: argus/v1/app.proto

package argusv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlaneService_GetDesiredState_FullMethodName = "/argus.v1.ControlPlaneService/GetDesiredState"
)

// ControlPlaneServiceClient is the client API for ControlPlaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ControlPlaneService: 运行在 Go 服务（绑定 app.sock），供 C++ 引擎拉取期望状态
type ControlPlaneServiceClient interface {
	GetDesiredState(ctx context.Context, in *GetDesiredStateRequest, opts ...grpc.CallOption) (*GetDesiredStateResponse, error)
}

type controlPlaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneServiceClient(cc grpc.ClientConnInterface) ControlPlaneServiceClient {
	return &controlPlaneServiceClient{cc}
}

func (c *controlPlaneServiceClient) GetDesiredState(ctx context.Context, in *GetDesiredStateRequest, opts ...grpc.CallOption) (*GetDesiredStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDesiredStateResponse)
	err := c.cc.Invoke(ctx, ControlPlaneService_GetDesiredState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneServiceServer is the server API for ControlPlaneService service.
// All implementations must embed UnimplementedControlPlaneServiceServer
// for forward compatibility.
//
// ControlPlaneService: 运行在 Go 服务（绑定 app.sock），供 C++ 引擎拉取期望状态
type ControlPlaneServiceServer interface {
	GetDesiredState(context.Context, *GetDesiredStateRequest) (*GetDesiredStateResponse, error)
	mustEmbedUnimplementedControlPlaneServiceServer()
}

// UnimplementedControlPlaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneServiceServer struct{}

func (UnimplementedControlPlaneServiceServer) GetDesiredState(context.Context, *GetDesiredStateRequest) (*GetDesiredStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDesiredState not implemented")
}
func (UnimplementedControlPlaneServiceServer) mustEmbedUnimplementedControlPlaneServiceServer() {}
func (UnimplementedControlPlaneServiceServer) testEmbeddedByValue()                             {}

// UnsafeControlPlaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneServiceServer will
// result in compilation errors.
type UnsafeControlPlaneServiceServer interface {
	mustEmbedUnimplementedControlPlaneServiceServer()
}

func RegisterControlPlaneServiceServer(s grpc.ServiceRegistrar, srv ControlPlaneServiceServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlaneService_ServiceDesc, srv)
}

func _ControlPlaneService_GetDesiredState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDesiredStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneServiceServer).GetDesiredState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneService_GetDesiredState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneServiceServer).GetDesiredState(ctx, req.(*GetDesiredStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlaneService_ServiceDesc is the grpc.ServiceDesc for ControlPlaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "argus.v1.ControlPlaneService",
	HandlerType: (*ControlPlaneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDesiredState",
			Handler:    _ControlPlaneService_GetDesiredState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "argus/v1/app.proto",
}

const (
	ReportService_ReportAlarm_FullMethodName            = "/argus.v1.ReportService/ReportAlarm"
	ReportService_ReportPlateObservation_FullMethodName = "/argus.v1.ReportService/ReportPlateObservation"
	ReportService_ReportTaskState_FullMethodName        = "/argus.v1.ReportService/ReportTaskState"
	ReportService_ReportInstanceState_FullMethodName    = "/argus.v1.ReportService/ReportInstanceState"
	ReportService_ReportMetrics_FullMethodName          = "/argus.v1.ReportService/ReportMetrics"
	ReportService_ReportOrphanImages_FullMethodName     = "/argus.v1.ReportService/ReportOrphanImages"
)

// ReportServiceClient is the client API for ReportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ReportService: 运行在 Go 服务（绑定 app.sock），供 C++ 引擎异步上报事件与指标
type ReportServiceClient interface {
	ReportAlarm(ctx context.Context, in *ReportAlarmRequest, opts ...grpc.CallOption) (*ReportAlarmResponse, error)
	ReportPlateObservation(ctx context.Context, in *ReportPlateObservationRequest, opts ...grpc.CallOption) (*ReportPlateObservationResponse, error)
	ReportTaskState(ctx context.Context, in *ReportTaskStateRequest, opts ...grpc.CallOption) (*ReportTaskStateResponse, error)
	ReportInstanceState(ctx context.Context, in *ReportInstanceStateRequest, opts ...grpc.CallOption) (*ReportInstanceStateResponse, error)
	ReportMetrics(ctx context.Context, in *ReportMetricsRequest, opts ...grpc.CallOption) (*ReportMetricsResponse, error)
	ReportOrphanImages(ctx context.Context, in *ReportOrphanImagesRequest, opts ...grpc.CallOption) (*ReportOrphanImagesResponse, error)
}

type reportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReportServiceClient(cc grpc.ClientConnInterface) ReportServiceClient {
	return &reportServiceClient{cc}
}

func (c *reportServiceClient) ReportAlarm(ctx context.Context, in *ReportAlarmRequest, opts ...grpc.CallOption) (*ReportAlarmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportAlarmResponse)
	err := c.cc.Invoke(ctx, ReportService_ReportAlarm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) ReportPlateObservation(ctx context.Context, in *ReportPlateObservationRequest, opts ...grpc.CallOption) (*ReportPlateObservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportPlateObservationResponse)
	err := c.cc.Invoke(ctx, ReportService_ReportPlateObservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) ReportTaskState(ctx context.Context, in *ReportTaskStateRequest, opts ...grpc.CallOption) (*ReportTaskStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportTaskStateResponse)
	err := c.cc.Invoke(ctx, ReportService_ReportTaskState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) ReportInstanceState(ctx context.Context, in *ReportInstanceStateRequest, opts ...grpc.CallOption) (*ReportInstanceStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportInstanceStateResponse)
	err := c.cc.Invoke(ctx, ReportService_ReportInstanceState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) ReportMetrics(ctx context.Context, in *ReportMetricsRequest, opts ...grpc.CallOption) (*ReportMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportMetricsResponse)
	err := c.cc.Invoke(ctx, ReportService_ReportMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reportServiceClient) ReportOrphanImages(ctx context.Context, in *ReportOrphanImagesRequest, opts ...grpc.CallOption) (*ReportOrphanImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportOrphanImagesResponse)
	err := c.cc.Invoke(ctx, ReportService_ReportOrphanImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportServiceServer is the server API for ReportService service.
// All implementations must embed UnimplementedReportServiceServer
// for forward compatibility.
//
// ReportService: 运行在 Go 服务（绑定 app.sock），供 C++ 引擎异步上报事件与指标
type ReportServiceServer interface {
	ReportAlarm(context.Context, *ReportAlarmRequest) (*ReportAlarmResponse, error)
	ReportPlateObservation(context.Context, *ReportPlateObservationRequest) (*ReportPlateObservationResponse, error)
	ReportTaskState(context.Context, *ReportTaskStateRequest) (*ReportTaskStateResponse, error)
	ReportInstanceState(context.Context, *ReportInstanceStateRequest) (*ReportInstanceStateResponse, error)
	ReportMetrics(context.Context, *ReportMetricsRequest) (*ReportMetricsResponse, error)
	ReportOrphanImages(context.Context, *ReportOrphanImagesRequest) (*ReportOrphanImagesResponse, error)
	mustEmbedUnimplementedReportServiceServer()
}

// UnimplementedReportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReportServiceServer struct{}

func (UnimplementedReportServiceServer) ReportAlarm(context.Context, *ReportAlarmRequest) (*ReportAlarmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportAlarm not implemented")
}
func (UnimplementedReportServiceServer) ReportPlateObservation(context.Context, *ReportPlateObservationRequest) (*ReportPlateObservationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportPlateObservation not implemented")
}
func (UnimplementedReportServiceServer) ReportTaskState(context.Context, *ReportTaskStateRequest) (*ReportTaskStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTaskState not implemented")
}
func (UnimplementedReportServiceServer) ReportInstanceState(context.Context, *ReportInstanceStateRequest) (*ReportInstanceStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportInstanceState not implemented")
}
func (UnimplementedReportServiceServer) ReportMetrics(context.Context, *ReportMetricsRequest) (*ReportMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportMetrics not implemented")
}
func (UnimplementedReportServiceServer) ReportOrphanImages(context.Context, *ReportOrphanImagesRequest) (*ReportOrphanImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportOrphanImages not implemented")
}
func (UnimplementedReportServiceServer) mustEmbedUnimplementedReportServiceServer() {}
func (UnimplementedReportServiceServer) testEmbeddedByValue()                       {}

// UnsafeReportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReportServiceServer will
// result in compilation errors.
type UnsafeReportServiceServer interface {
	mustEmbedUnimplementedReportServiceServer()
}

func RegisterReportServiceServer(s grpc.ServiceRegistrar, srv ReportServiceServer) {
	// If the following call panics, it indicates UnimplementedReportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReportService_ServiceDesc, srv)
}

func _ReportService_ReportAlarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportAlarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).ReportAlarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_ReportAlarm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).ReportAlarm(ctx, req.(*ReportAlarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_ReportPlateObservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportPlateObservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).ReportPlateObservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_ReportPlateObservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).ReportPlateObservation(ctx, req.(*ReportPlateObservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_ReportTaskState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportTaskStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).ReportTaskState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_ReportTaskState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).ReportTaskState(ctx, req.(*ReportTaskStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_ReportInstanceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportInstanceStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).ReportInstanceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_ReportInstanceState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).ReportInstanceState(ctx, req.(*ReportInstanceStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_ReportMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).ReportMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_ReportMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).ReportMetrics(ctx, req.(*ReportMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReportService_ReportOrphanImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportOrphanImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServiceServer).ReportOrphanImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReportService_ReportOrphanImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServiceServer).ReportOrphanImages(ctx, req.(*ReportOrphanImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReportService_ServiceDesc is the grpc.ServiceDesc for ReportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "argus.v1.ReportService",
	HandlerType: (*ReportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportAlarm",
			Handler:    _ReportService_ReportAlarm_Handler,
		},
		{
			MethodName: "ReportPlateObservation",
			Handler:    _ReportService_ReportPlateObservation_Handler,
		},
		{
			MethodName: "ReportTaskState",
			Handler:    _ReportService_ReportTaskState_Handler,
		},
		{
			MethodName: "ReportInstanceState",
			Handler:    _ReportService_ReportInstanceState_Handler,
		},
		{
			MethodName: "ReportMetrics",
			Handler:    _ReportService_ReportMetrics_Handler,
		},
		{
			MethodName: "ReportOrphanImages",
			Handler:    _ReportService_ReportOrphanImages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "argus/v1/app.proto",
}
