// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: argus/v1/common.proto

package argusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 像素格式枚举（对齐 C ABI av_pixel_format，sdk/include/argus/types.h）
type FramePixelFormat int32

const (
	FramePixelFormat_FRAME_PIX_UNSPECIFIED FramePixelFormat = 0
	FramePixelFormat_FRAME_PIX_NV12        FramePixelFormat = 1
	FramePixelFormat_FRAME_PIX_BGRA        FramePixelFormat = 2
	FramePixelFormat_FRAME_PIX_RGB24       FramePixelFormat = 3
	FramePixelFormat_FRAME_PIX_I420        FramePixelFormat = 4
)

// Enum value maps for FramePixelFormat.
var (
	FramePixelFormat_name = map[int32]string{
		0: "FRAME_PIX_UNSPECIFIED",
		1: "FRAME_PIX_NV12",
		2: "FRAME_PIX_BGRA",
		3: "FRAME_PIX_RGB24",
		4: "FRAME_PIX_I420",
	}
	FramePixelFormat_value = map[string]int32{
		"FRAME_PIX_UNSPECIFIED": 0,
		"FRAME_PIX_NV12":        1,
		"FRAME_PIX_BGRA":        2,
		"FRAME_PIX_RGB24":       3,
		"FRAME_PIX_I420":        4,
	}
)

func (x FramePixelFormat) Enum() *FramePixelFormat {
	p := new(FramePixelFormat)
	*p = x
	return p
}

func (x FramePixelFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FramePixelFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_argus_v1_common_proto_enumTypes[0].Descriptor()
}

func (FramePixelFormat) Type() protoreflect.EnumType {
	return &file_argus_v1_common_proto_enumTypes[0]
}

func (x FramePixelFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FramePixelFormat.Descriptor instead.
func (FramePixelFormat) EnumDescriptor() ([]byte, []int) {
	return file_argus_v1_common_proto_rawDescGZIP(), []int{0}
}

// 色彩空间与转换枚举（对齐 C ABI av_color_*）
type ColorPrimaries int32

const (
	ColorPrimaries_COLOR_PRIM_UNSPECIFIED ColorPrimaries = 0
	ColorPrimaries_COLOR_PRIM_BT709       ColorPrimaries = 1
	ColorPrimaries_COLOR_PRIM_BT2020      ColorPrimaries = 2
)

// Enum value maps for ColorPrimaries.
var (
	ColorPrimaries_name = map[int32]string{
		0: "COLOR_PRIM_UNSPECIFIED",
		1: "COLOR_PRIM_BT709",
		2: "COLOR_PRIM_BT2020",
	}
	ColorPrimaries_value = map[string]int32{
		"COLOR_PRIM_UNSPECIFIED": 0,
		"COLOR_PRIM_BT709":       1,
		"COLOR_PRIM_BT2020":      2,
	}
)

func (x ColorPrimaries) Enum() *ColorPrimaries {
	p := new(ColorPrimaries)
	*p = x
	return p
}

func (x ColorPrimaries) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColorPrimaries) Descriptor() protoreflect.EnumDescriptor {
	return file_argus_v1_common_proto_enumTypes[1].Descriptor()
}

func (ColorPrimaries) Type() protoreflect.EnumType {
	return &file_argus_v1_common_proto_enumTypes[1]
}

func (x ColorPrimaries) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColorPrimaries.Descriptor instead.
func (ColorPrimaries) EnumDescriptor() ([]byte, []int) {
	return file_argus_v1_common_proto_rawDescGZIP(), []int{1}
}

type ColorTransfer int32

const (
	ColorTransfer_COLOR_TRC_UNSPECIFIED  ColorTransfer = 0
	ColorTransfer_COLOR_TRC_BT709        ColorTransfer = 1
	ColorTransfer_COLOR_TRC_IEC61966_2_1 ColorTransfer = 2
)

// Enum value maps for ColorTransfer.
var (
	ColorTransfer_name = map[int32]string{
		0: "COLOR_TRC_UNSPECIFIED",
		1: "COLOR_TRC_BT709",
		2: "COLOR_TRC_IEC61966_2_1",
	}
	ColorTransfer_value = map[string]int32{
		"COLOR_TRC_UNSPECIFIED":  0,
		"COLOR_TRC_BT709":        1,
		"COLOR_TRC_IEC61966_2_1": 2,
	}
)

func (x ColorTransfer) Enum() *ColorTransfer {
	p := new(ColorTransfer)
	*p = x
	return p
}

func (x ColorTransfer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColorTransfer) Descriptor() protoreflect.EnumDescriptor {
	return file_argus_v1_common_proto_enumTypes[2].Descriptor()
}

func (ColorTransfer) Type() protoreflect.EnumType {
	return &file_argus_v1_common_proto_enumTypes[2]
}

func (x ColorTransfer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColorTransfer.Descriptor instead.
func (ColorTransfer) EnumDescriptor() ([]byte, []int) {
	return file_argus_v1_common_proto_rawDescGZIP(), []int{2}
}

type ColorMatrix int32

const (
	ColorMatrix_COLOR_MAT_UNSPECIFIED ColorMatrix = 0
	ColorMatrix_COLOR_MAT_BT709       ColorMatrix = 1
	ColorMatrix_COLOR_MAT_BT2020_NCL  ColorMatrix = 2
)

// Enum value maps for ColorMatrix.
var (
	ColorMatrix_name = map[int32]string{
		0: "COLOR_MAT_UNSPECIFIED",
		1: "COLOR_MAT_BT709",
		2: "COLOR_MAT_BT2020_NCL",
	}
	ColorMatrix_value = map[string]int32{
		"COLOR_MAT_UNSPECIFIED": 0,
		"COLOR_MAT_BT709":       1,
		"COLOR_MAT_BT2020_NCL":  2,
	}
)

func (x ColorMatrix) Enum() *ColorMatrix {
	p := new(ColorMatrix)
	*p = x
	return p
}

func (x ColorMatrix) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColorMatrix) Descriptor() protoreflect.EnumDescriptor {
	return file_argus_v1_common_proto_enumTypes[3].Descriptor()
}

func (ColorMatrix) Type() protoreflect.EnumType {
	return &file_argus_v1_common_proto_enumTypes[3]
}

func (x ColorMatrix) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColorMatrix.Descriptor instead.
func (ColorMatrix) EnumDescriptor() ([]byte, []int) {
	return file_argus_v1_common_proto_rawDescGZIP(), []int{3}
}

type ColorRange int32

const (
	ColorRange_COLOR_RANGE_UNSPECIFIED ColorRange = 0
	ColorRange_COLOR_RANGE_LIMITED     ColorRange = 1
	ColorRange_COLOR_RANGE_FULL        ColorRange = 2
)

// Enum value maps for ColorRange.
var (
	ColorRange_name = map[int32]string{
		0: "COLOR_RANGE_UNSPECIFIED",
		1: "COLOR_RANGE_LIMITED",
		2: "COLOR_RANGE_FULL",
	}
	ColorRange_value = map[string]int32{
		"COLOR_RANGE_UNSPECIFIED": 0,
		"COLOR_RANGE_LIMITED":     1,
		"COLOR_RANGE_FULL":        2,
	}
)

func (x ColorRange) Enum() *ColorRange {
	p := new(ColorRange)
	*p = x
	return p
}

func (x ColorRange) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColorRange) Descriptor() protoreflect.EnumDescriptor {
	return file_argus_v1_common_proto_enumTypes[4].Descriptor()
}

func (ColorRange) Type() protoreflect.EnumType {
	return &file_argus_v1_common_proto_enumTypes[4]
}

func (x ColorRange) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColorRange.Descriptor instead.
func (ColorRange) EnumDescriptor() ([]byte, []int) {
	return file_argus_v1_common_proto_rawDescGZIP(), []int{4}
}

// 图片删除状态枚举（三态幂等契约）
type ImageDeleteStatus int32

const (
	ImageDeleteStatus_IMAGE_DELETE_STATUS_UNSPECIFIED    ImageDeleteStatus = 0
	ImageDeleteStatus_IMAGE_DELETE_STATUS_DELETED        ImageDeleteStatus = 1 // 成功删除物理文件与 catalog 记录
	ImageDeleteStatus_IMAGE_DELETE_STATUS_ALREADY_ABSENT ImageDeleteStatus = 2 // 文件原本已不存在，视为幂等成功
	ImageDeleteStatus_IMAGE_DELETE_STATUS_FAILED         ImageDeleteStatus = 3 // 删除失败（如 IO 错误、权限不足等）
)

// Enum value maps for ImageDeleteStatus.
var (
	ImageDeleteStatus_name = map[int32]string{
		0: "IMAGE_DELETE_STATUS_UNSPECIFIED",
		1: "IMAGE_DELETE_STATUS_DELETED",
		2: "IMAGE_DELETE_STATUS_ALREADY_ABSENT",
		3: "IMAGE_DELETE_STATUS_FAILED",
	}
	ImageDeleteStatus_value = map[string]int32{
		"IMAGE_DELETE_STATUS_UNSPECIFIED":    0,
		"IMAGE_DELETE_STATUS_DELETED":        1,
		"IMAGE_DELETE_STATUS_ALREADY_ABSENT": 2,
		"IMAGE_DELETE_STATUS_FAILED":         3,
	}
)

func (x ImageDeleteStatus) Enum() *ImageDeleteStatus {
	p := new(ImageDeleteStatus)
	*p = x
	return p
}

func (x ImageDeleteStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageDeleteStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_argus_v1_common_proto_enumTypes[5].Descriptor()
}

func (ImageDeleteStatus) Type() protoreflect.EnumType {
	return &file_argus_v1_common_proto_enumTypes[5]
}

func (x ImageDeleteStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageDeleteStatus.Descriptor instead.
func (ImageDeleteStatus) EnumDescriptor() ([]byte, []int) {
	return file_argus_v1_common_proto_rawDescGZIP(), []int{5}
}

// 边界框（采用 [0.0, 1.0] 相对归一化坐标系）
type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XMin          float32                `protobuf:"fixed32,1,opt,name=x_min,json=xMin,proto3" json:"x_min,omitempty"` // 归一化左边界 [0.0, 1.0]
	YMin          float32                `protobuf:"fixed32,2,opt,name=y_min,json=yMin,proto3" json:"y_min,omitempty"` // 归一化顶边界 [0.0, 1.0]
	XMax          float32                `protobuf:"fixed32,3,opt,name=x_max,json=xMax,proto3" json:"x_max,omitempty"` // 归一化右边界 [0.0, 1.0]
	YMax          float32                `protobuf:"fixed32,4,opt,name=y_max,json=yMax,proto3" json:"y_max,omitempty"` // 归一化底边界 [0.0, 1.0]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_argus_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_argus_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *BoundingBox) GetXMin() float32 {
	if x != nil {
		return x.XMin
	}
	return 0
}

func (x *BoundingBox) GetYMin() float32 {
	if x != nil {
		return x.YMin
	}
	return 0
}

func (x *BoundingBox) GetXMax() float32 {
	if x != nil {
		return x.XMax
	}
	return 0
}

func (x *BoundingBox) GetYMax() float32 {
	if x != nil {
		return x.YMax
	}
	return 0
}

// 检测目标对象
type DetectedObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Bbox          *BoundingBox           `protobuf:"bytes,3,opt,name=bbox,proto3" json:"bbox,omitempty"`
	TrackId       int64                  `protobuf:"varint,4,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"` // 目标追踪 ID；<= 0 或 -1 表示无追踪 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectedObject) Reset() {
	*x = DetectedObject{}
	mi := &file_argus_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectedObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectedObject) ProtoMessage() {}

func (x *DetectedObject) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectedObject.ProtoReflect.Descriptor instead.
func (*DetectedObject) Descriptor() ([]byte, []int) {
	return file_argus_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *DetectedObject) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DetectedObject) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DetectedObject) GetBbox() *BoundingBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *DetectedObject) GetTrackId() int64 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

// 单张图片删除结果
type DeleteImageResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Status        ImageDeleteStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=argus.v1.ImageDeleteStatus" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteImageResult) Reset() {
	*x = DeleteImageResult{}
	mi := &file_argus_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteImageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteImageResult) ProtoMessage() {}

func (x *DeleteImageResult) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteImageResult.ProtoReflect.Descriptor instead.
func (*DeleteImageResult) Descriptor() ([]byte, []int) {
	return file_argus_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteImageResult) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *DeleteImageResult) GetStatus() ImageDeleteStatus {
	if x != nil {
		return x.Status
	}
	return ImageDeleteStatus_IMAGE_DELETE_STATUS_UNSPECIFIED
}

func (x *DeleteImageResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// 通用设备性能遥测数据
type DeviceTelemetry struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	UptimeSeconds             int64                  `protobuf:"varint,1,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	CpuUsagePercent           float32                `protobuf:"fixed32,2,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsagePercent        float32                `protobuf:"fixed32,3,opt,name=memory_usage_percent,json=memoryUsagePercent,proto3" json:"memory_usage_percent,omitempty"`
	DiskUsagePercent          float32                `protobuf:"fixed32,4,opt,name=disk_usage_percent,json=diskUsagePercent,proto3" json:"disk_usage_percent,omitempty"`
	AcceleratorUsagePercent   float32                `protobuf:"fixed32,5,opt,name=accelerator_usage_percent,json=acceleratorUsagePercent,proto3" json:"accelerator_usage_percent,omitempty"` // meaningful only when accelerator_usage_supported=true; otherwise NaN
	AcceleratorUsageSupported bool                   `protobuf:"varint,6,opt,name=accelerator_usage_supported,json=acceleratorUsageSupported,proto3" json:"accelerator_usage_supported,omitempty"`
	TemperatureCelsius        float32                `protobuf:"fixed32,7,opt,name=temperature_celsius,json=temperatureCelsius,proto3" json:"temperature_celsius,omitempty"` // meaningful only when temperature_supported=true; otherwise NaN
	TemperatureSupported      bool                   `protobuf:"varint,8,opt,name=temperature_supported,json=temperatureSupported,proto3" json:"temperature_supported,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *DeviceTelemetry) Reset() {
	*x = DeviceTelemetry{}
	mi := &file_argus_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceTelemetry) ProtoMessage() {}

func (x *DeviceTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceTelemetry.ProtoReflect.Descriptor instead.
func (*DeviceTelemetry) Descriptor() ([]byte, []int) {
	return file_argus_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceTelemetry) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *DeviceTelemetry) GetCpuUsagePercent() float32 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *DeviceTelemetry) GetMemoryUsagePercent() float32 {
	if x != nil {
		return x.MemoryUsagePercent
	}
	return 0
}

func (x *DeviceTelemetry) GetDiskUsagePercent() float32 {
	if x != nil {
		return x.DiskUsagePercent
	}
	return 0
}

func (x *DeviceTelemetry) GetAcceleratorUsagePercent() float32 {
	if x != nil {
		return x.AcceleratorUsagePercent
	}
	return 0
}

func (x *DeviceTelemetry) GetAcceleratorUsageSupported() bool {
	if x != nil {
		return x.AcceleratorUsageSupported
	}
	return false
}

func (x *DeviceTelemetry) GetTemperatureCelsius() float32 {
	if x != nil {
		return x.TemperatureCelsius
	}
	return 0
}

func (x *DeviceTelemetry) GetTemperatureSupported() bool {
	if x != nil {
		return x.TemperatureSupported
	}
	return false
}

var File_argus_v1_common_proto protoreflect.FileDescriptor

const file_argus_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x15argus/v1/common.proto\x12\bargus.v1\"a\n" +
	"\vBoundingBox\x12\x13\n" +
	"\x05x_min\x18\x01 \x01(\x02R\x04xMin\x12\x13\n" +
	"\x05y_min\x18\x02 \x01(\x02R\x04yMin\x12\x13\n" +
	"\x05x_max\x18\x03 \x01(\x02R\x04xMax\x12\x13\n" +
	"\x05y_max\x18\x04 \x01(\x02R\x04yMax\"\x8c\x01\n" +
	"\x0eDetectedObject\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12)\n" +
	"\x04bbox\x18\x03 \x01(\v2\x15.argus.v1.BoundingBoxR\x04bbox\x12\x19\n" +
	"\btrack_id\x18\x04 \x01(\x03R\atrackId\"\x88\x01\n" +
	"\x11DeleteImageResult\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.argus.v1.ImageDeleteStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xa6\x03\n" +
	"\x0fDeviceTelemetry\x12%\n" +
	"\x0euptime_seconds\x18\x01 \x01(\x03R\ruptimeSeconds\x12*\n" +
	"\x11cpu_usage_percent\x18\x02 \x01(\x02R\x0fcpuUsagePercent\x120\n" +
	"\x14memory_usage_percent\x18\x03 \x01(\x02R\x12memoryUsagePercent\x12,\n" +
	"\x12disk_usage_percent\x18\x04 \x01(\x02R\x10diskUsagePercent\x12:\n" +
	"\x19accelerator_usage_percent\x18\x05 \x01(\x02R\x17acceleratorUsagePercent\x12>\n" +
	"\x1baccelerator_usage_supported\x18\x06 \x01(\bR\x19acceleratorUsageSupported\x12/\n" +
	"\x13temperature_celsius\x18\a \x01(\x02R\x12temperatureCelsius\x123\n" +
	"\x15temperature_supported\x18\b \x01(\bR\x14temperatureSupported*~\n" +
	"\x10FramePixelFormat\x12\x19\n" +
	"\x15FRAME_PIX_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eFRAME_PIX_NV12\x10\x01\x12\x12\n" +
	"\x0eFRAME_PIX_BGRA\x10\x02\x12\x13\n" +
	"\x0fFRAME_PIX_RGB24\x10\x03\x12\x12\n" +
	"\x0eFRAME_PIX_I420\x10\x04*Y\n" +
	"\x0eColorPrimaries\x12\x1a\n" +
	"\x16COLOR_PRIM_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10COLOR_PRIM_BT709\x10\x01\x12\x15\n" +
	"\x11COLOR_PRIM_BT2020\x10\x02*[\n" +
	"\rColorTransfer\x12\x19\n" +
	"\x15COLOR_TRC_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCOLOR_TRC_BT709\x10\x01\x12\x1a\n" +
	"\x16COLOR_TRC_IEC61966_2_1\x10\x02*W\n" +
	"\vColorMatrix\x12\x19\n" +
	"\x15COLOR_MAT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fCOLOR_MAT_BT709\x10\x01\x12\x18\n" +
	"\x14COLOR_MAT_BT2020_NCL\x10\x02*X\n" +
	"\n" +
	"ColorRange\x12\x1b\n" +
	"\x17COLOR_RANGE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13COLOR_RANGE_LIMITED\x10\x01\x12\x14\n" +
	"\x10COLOR_RANGE_FULL\x10\x02*\xa1\x01\n" +
	"\x11ImageDeleteStatus\x12#\n" +
	"\x1fIMAGE_DELETE_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bIMAGE_DELETE_STATUS_DELETED\x10\x01\x12&\n" +
	"\"IMAGE_DELETE_STATUS_ALREADY_ABSENT\x10\x02\x12\x1e\n" +
	"\x1aIMAGE_DELETE_STATUS_FAILED\x10\x03B+Z)argus/app/internal/proto/argus/v1;argusv1b\x06proto3"

var (
	file_argus_v1_common_proto_rawDescOnce sync.Once
	file_argus_v1_common_proto_rawDescData []byte
)

func file_argus_v1_common_proto_rawDescGZIP() []byte {
	file_argus_v1_common_proto_rawDescOnce.Do(func() {
		file_argus_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_argus_v1_common_proto_rawDesc), len(file_argus_v1_common_proto_rawDesc)))
	})
	return file_argus_v1_common_proto_rawDescData
}

var file_argus_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_argus_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_argus_v1_common_proto_goTypes = []any{
	(FramePixelFormat)(0),     // 0: argus.v1.FramePixelFormat
	(ColorPrimaries)(0),       // 1: argus.v1.ColorPrimaries
	(ColorTransfer)(0),        // 2: argus.v1.ColorTransfer
	(ColorMatrix)(0),          // 3: argus.v1.ColorMatrix
	(ColorRange)(0),           // 4: argus.v1.ColorRange
	(ImageDeleteStatus)(0),    // 5: argus.v1.ImageDeleteStatus
	(*BoundingBox)(nil),       // 6: argus.v1.BoundingBox
	(*DetectedObject)(nil),    // 7: argus.v1.DetectedObject
	(*DeleteImageResult)(nil), // 8: argus.v1.DeleteImageResult
	(*DeviceTelemetry)(nil),   // 9: argus.v1.DeviceTelemetry
}
var file_argus_v1_common_proto_depIdxs = []int32{
	6, // 0: argus.v1.DetectedObject.bbox:type_name -> argus.v1.BoundingBox
	5, // 1: argus.v1.DeleteImageResult.status:type_name -> argus.v1.ImageDeleteStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_argus_v1_common_proto_init() }
func file_argus_v1_common_proto_init() {
	if File_argus_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_argus_v1_common_proto_rawDesc), len(file_argus_v1_common_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_argus_v1_common_proto_goTypes,
		DependencyIndexes: file_argus_v1_common_proto_depIdxs,
		EnumInfos:         file_argus_v1_common_proto_enumTypes,
		MessageInfos:      file_argus_v1_common_proto_msgTypes,
	}.Build()
	File_argus_v1_common_proto = out.File
	file_argus_v1_common_proto_goTypes = nil
	file_argus_v1_common_proto_depIdxs = nil
}
