// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: argus/v1/person.proto

package argusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 归一化矩形框 [0.0, 1.0]
type NormalizedRect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         float32                `protobuf:"fixed32,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        float32                `protobuf:"fixed32,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NormalizedRect) Reset() {
	*x = NormalizedRect{}
	mi := &file_argus_v1_person_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizedRect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizedRect) ProtoMessage() {}

func (x *NormalizedRect) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_person_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NormalizedRect.ProtoReflect.Descriptor instead.
func (*NormalizedRect) Descriptor() ([]byte, []int) {
	return file_argus_v1_person_proto_rawDescGZIP(), []int{0}
}

func (x *NormalizedRect) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *NormalizedRect) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *NormalizedRect) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *NormalizedRect) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// 人脸特征提取请求
type ExtractFaceFeatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"` // 单张图片原始字节（最大 10MB）
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`    // 提示 MIME 类型（如 image/jpeg, image/png, image/webp）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractFaceFeatureRequest) Reset() {
	*x = ExtractFaceFeatureRequest{}
	mi := &file_argus_v1_person_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractFaceFeatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractFaceFeatureRequest) ProtoMessage() {}

func (x *ExtractFaceFeatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_person_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractFaceFeatureRequest.ProtoReflect.Descriptor instead.
func (*ExtractFaceFeatureRequest) Descriptor() ([]byte, []int) {
	return file_argus_v1_person_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractFaceFeatureRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ExtractFaceFeatureRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

// 人脸特征提取响应
type ExtractFaceFeatureResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                                   // 稳定错误码，空串表示成功
	ErrorMessage     string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`               // 诊断日志（调用方不得解析其文本）
	Embedding        []byte                 `protobuf:"bytes,3,opt,name=embedding,proto3" json:"embedding,omitempty"`                                         // 512 维 L2 归一化 float32 小端字节流 (精确 2048 字节)
	AlignedFaceImage []byte                 `protobuf:"bytes,4,opt,name=aligned_face_image,json=alignedFaceImage,proto3" json:"aligned_face_image,omitempty"` // 112x112 标准化人脸对齐 JPEG 图片字节流
	FaceBox          *NormalizedRect        `protobuf:"bytes,5,opt,name=face_box,json=faceBox,proto3" json:"face_box,omitempty"`                              // 原图中人脸归一化坐标
	QualityScore     float32                `protobuf:"fixed32,6,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`             // 综合人脸质量得分 (0.0 ~ 100.0)
	DetectionScore   float32                `protobuf:"fixed32,7,opt,name=detection_score,json=detectionScore,proto3" json:"detection_score,omitempty"`       // 人脸检测置信度 (0.0 ~ 1.0)
	AlgorithmId      string                 `protobuf:"bytes,8,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`                  // 算法包标识 (如 "face_recognition")
	AlgorithmVersion string                 `protobuf:"bytes,9,opt,name=algorithm_version,json=algorithmVersion,proto3" json:"algorithm_version,omitempty"`   // 算法包版本号 (如 "1.0.0")
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExtractFaceFeatureResponse) Reset() {
	*x = ExtractFaceFeatureResponse{}
	mi := &file_argus_v1_person_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractFaceFeatureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractFaceFeatureResponse) ProtoMessage() {}

func (x *ExtractFaceFeatureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_argus_v1_person_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractFaceFeatureResponse.ProtoReflect.Descriptor instead.
func (*ExtractFaceFeatureResponse) Descriptor() ([]byte, []int) {
	return file_argus_v1_person_proto_rawDescGZIP(), []int{2}
}

func (x *ExtractFaceFeatureResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExtractFaceFeatureResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ExtractFaceFeatureResponse) GetEmbedding() []byte {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *ExtractFaceFeatureResponse) GetAlignedFaceImage() []byte {
	if x != nil {
		return x.AlignedFaceImage
	}
	return nil
}

func (x *ExtractFaceFeatureResponse) GetFaceBox() *NormalizedRect {
	if x != nil {
		return x.FaceBox
	}
	return nil
}

func (x *ExtractFaceFeatureResponse) GetQualityScore() float32 {
	if x != nil {
		return x.QualityScore
	}
	return 0
}

func (x *ExtractFaceFeatureResponse) GetDetectionScore() float32 {
	if x != nil {
		return x.DetectionScore
	}
	return 0
}

func (x *ExtractFaceFeatureResponse) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *ExtractFaceFeatureResponse) GetAlgorithmVersion() string {
	if x != nil {
		return x.AlgorithmVersion
	}
	return ""
}

var File_argus_v1_person_proto protoreflect.FileDescriptor

const file_argus_v1_person_proto_rawDesc = "" +
	"\n" +
	"\x15argus/v1/person.proto\x12\bargus.v1\"Z\n" +
	"\x0eNormalizedRect\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x02R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x02R\x06height\"W\n" +
	"\x19ExtractFaceFeatureRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\"\xf4\x02\n" +
	"\x1aExtractFaceFeatureResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\tembedding\x18\x03 \x01(\fR\tembedding\x12,\n" +
	"\x12aligned_face_image\x18\x04 \x01(\fR\x10alignedFaceImage\x123\n" +
	"\bface_box\x18\x05 \x01(\v2\x18.argus.v1.NormalizedRectR\afaceBox\x12#\n" +
	"\rquality_score\x18\x06 \x01(\x02R\fqualityScore\x12'\n" +
	"\x0fdetection_score\x18\a \x01(\x02R\x0edetectionScore\x12!\n" +
	"\falgorithm_id\x18\b \x01(\tR\valgorithmId\x12+\n" +
	"\x11algorithm_version\x18\t \x01(\tR\x10algorithmVersion2p\n" +
	"\rPersonService\x12_\n" +
	"\x12ExtractFaceFeature\x12#.argus.v1.ExtractFaceFeatureRequest\x1a$.argus.v1.ExtractFaceFeatureResponseB+Z)argus/app/internal/proto/argus/v1;argusv1b\x06proto3"

var (
	file_argus_v1_person_proto_rawDescOnce sync.Once
	file_argus_v1_person_proto_rawDescData []byte
)

func file_argus_v1_person_proto_rawDescGZIP() []byte {
	file_argus_v1_person_proto_rawDescOnce.Do(func() {
		file_argus_v1_person_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_argus_v1_person_proto_rawDesc), len(file_argus_v1_person_proto_rawDesc)))
	})
	return file_argus_v1_person_proto_rawDescData
}

var file_argus_v1_person_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_argus_v1_person_proto_goTypes = []any{
	(*NormalizedRect)(nil),             // 0: argus.v1.NormalizedRect
	(*ExtractFaceFeatureRequest)(nil),  // 1: argus.v1.ExtractFaceFeatureRequest
	(*ExtractFaceFeatureResponse)(nil), // 2: argus.v1.ExtractFaceFeatureResponse
}
var file_argus_v1_person_proto_depIdxs = []int32{
	0, // 0: argus.v1.ExtractFaceFeatureResponse.face_box:type_name -> argus.v1.NormalizedRect
	1, // 1: argus.v1.PersonService.ExtractFaceFeature:input_type -> argus.v1.ExtractFaceFeatureRequest
	2, // 2: argus.v1.PersonService.ExtractFaceFeature:output_type -> argus.v1.ExtractFaceFeatureResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_argus_v1_person_proto_init() }
func file_argus_v1_person_proto_init() {
	if File_argus_v1_person_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_argus_v1_person_proto_rawDesc), len(file_argus_v1_person_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_argus_v1_person_proto_goTypes,
		DependencyIndexes: file_argus_v1_person_proto_depIdxs,
		MessageInfos:      file_argus_v1_person_proto_msgTypes,
	}.Build()
	File_argus_v1_person_proto = out.File
	file_argus_v1_person_proto_goTypes = nil
	file_argus_v1_person_proto_depIdxs = nil
}
