//go:build linux

package netconfig

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"syscall"
)

// validateResolverFile 检查 resolver 路径是否为独占普通文件（非 symlink、非全局可写、root 属主）。
func validateResolverFile(path string) error {
	info, err := os.Lstat(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		return fmt.Errorf("%w: lstat %s: %v", ErrResolverConflict, path, err)
	}

	if info.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("%w: resolver path %s is a symlink (exclusive ownership required)", ErrResolverConflict, path)
	}
	if !info.Mode().IsRegular() {
		return fmt.Errorf("%w: resolver path %s is not a regular file", ErrResolverConflict, path)
	}
	if info.Mode().Perm()&0002 != 0 {
		return fmt.Errorf("%w: resolver path %s is world-writable", ErrResolverConflict, path)
	}
	if stat, ok := info.Sys().(*syscall.Stat_t); ok {
		if os.Geteuid() == 0 && stat.Uid != 0 {
			return fmt.Errorf("%w: resolver path %s owner uid is %d, expected 0 (root)", ErrResolverConflict, path, stat.Uid)
		}
	}
	return nil
}

// atomicWriteFile 原子安全地将数据写入指定文件路径，并同步目录元数据。
func atomicWriteFile(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create dir for %s: %w", path, err)
	}

	tmpFile := filepath.Join(dir, fmt.Sprintf(".%s.%d.tmp", filepath.Base(path), os.Getpid()))
	f, err := os.OpenFile(tmpFile, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, perm)
	if err != nil {
		return fmt.Errorf("create tmp file for %s: %w", path, err)
	}

	if _, err := f.Write(data); err != nil {
		_ = f.Close()
		_ = os.Remove(tmpFile)
		return fmt.Errorf("write tmp file for %s: %w", path, err)
	}
	if err := f.Sync(); err != nil {
		_ = f.Close()
		_ = os.Remove(tmpFile)
		return fmt.Errorf("fsync tmp file for %s: %w", path, err)
	}
	if err := f.Close(); err != nil {
		_ = os.Remove(tmpFile)
		return fmt.Errorf("close tmp file for %s: %w", path, err)
	}

	if err := os.Rename(tmpFile, path); err != nil {
		_ = os.Remove(tmpFile)
		return fmt.Errorf("rename tmp file to %s: %w", path, err)
	}

	if df, err := os.Open(dir); err == nil {
		_ = df.Sync()
		_ = df.Close()
	}
	return nil
}

// writeResolvConf 原子安全地将 nameserver 列表写入 resolver 文件（默认 /etc/resolv.conf）。
func writeResolvConf(path string, nameservers []string) (string, error) {
	if path == "" {
		path = "/etc/resolv.conf"
	}

	// 1. 前置独占安全性校验
	if err := validateResolverFile(path); err != nil {
		return "", err
	}

	// 读取旧内容（用于 undo 回滚）
	var oldContent string
	if oldBytes, err := os.ReadFile(path); err == nil {
		oldContent = string(oldBytes)
	}

	// 2. 最多保留 3 个 nameserver
	limit := min(len(nameservers), 3)

	var sb strings.Builder
	sb.WriteString("# Generated by Argus system daemon\n")
	for i := 0; i < limit; i++ {
		ns := strings.TrimSpace(nameservers[i])
		if ns != "" {
			sb.WriteString(fmt.Sprintf("nameserver %s\n", ns))
		}
	}

	// 3. 原子写入与同步
	if err := atomicWriteFile(path, []byte(sb.String()), 0644); err != nil {
		return oldContent, fmt.Errorf("write resolv file: %w", err)
	}

	return oldContent, nil
}

// restoreResolvConf 将 resolv.conf 恢复为原始内容。
func restoreResolvConf(path string, oldContent string) error {
	if path == "" {
		path = "/etc/resolv.conf"
	}
	if oldContent == "" {
		_ = os.Remove(path)
		return nil
	}
	return atomicWriteFile(path, []byte(oldContent), 0644)
}
