// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"niko-vue-admin/app/internal/api"
	"niko-vue-admin/app/internal/middleware"
	"niko-vue-admin/app/internal/pkg/config"
	"niko-vue-admin/app/internal/pkg/db"
	"niko-vue-admin/app/internal/pkg/engineipc"
	"niko-vue-admin/app/internal/pkg/logger"
	"niko-vue-admin/app/internal/pkg/ntp"
	"niko-vue-admin/app/internal/pkg/storage"
	"niko-vue-admin/app/internal/repository"
	"niko-vue-admin/app/internal/router"
	"niko-vue-admin/app/internal/service"
)

// Injectors from wire.go:

// InitializeApp 装配启动依赖链：config → db → logger → engine。
func InitializeApp(cfg *config.Config) (*App, error) {
	zapLogger, err := logger.New(cfg)
	if err != nil {
		return nil, err
	}
	gormDB, err := db.New(cfg, zapLogger)
	if err != nil {
		return nil, err
	}
	handlerFunc := middleware.ErrorHandler()
	authRepository := repository.NewAuthRepository(gormDB)
	authMiddleware := middleware.NewAuthMiddleware(authRepository, cfg)
	menuRepository := repository.NewMenuRepository(gormDB)
	permMiddleware := middleware.NewPermMiddleware(menuRepository)
	operationLogRepository := repository.NewOperationLogRepository(gormDB)
	operationLogService := service.NewOperationLogService(operationLogRepository)
	oplogMiddleware := middleware.NewOplogMiddleware(operationLogService, zapLogger)
	openPersonIPWhitelistMiddleware := middleware.NewOpenPersonIPWhitelistMiddleware(cfg)
	menuService := service.NewMenuService(menuRepository)
	menuHandler := api.NewMenuHandler(menuService)
	roleRepository := repository.NewRoleRepository(gormDB)
	roleService := service.NewRoleService(roleRepository, menuRepository)
	roleHandler := api.NewRoleHandler(roleService)
	departmentRepository := repository.NewDepartmentRepository(gormDB)
	deptService := service.NewDeptService(departmentRepository)
	departmentHandler := api.NewDepartmentHandler(deptService)
	operationLogHandler := api.NewOperationLogHandler(operationLogService)
	userRepository := repository.NewUserRepository(gormDB)
	userService := service.NewUserService(userRepository, departmentRepository, roleRepository)
	userHandler := api.NewUserHandler(userService)
	authService := service.NewAuthService(authRepository, userRepository, menuRepository, cfg)
	authHandler := api.NewAuthHandler(authService, authMiddleware, cfg)
	fileStorage, err := storage.New(cfg)
	if err != nil {
		return nil, err
	}
	fileService := service.NewFileService(fileStorage, cfg)
	fileHandler := api.NewFileHandler(fileService, cfg)
	systemConfigRepository := repository.NewSystemConfigRepository(gormDB)
	executor := ntp.NewExecutor()
	ntpService := service.NewNTPService(systemConfigRepository, executor, zapLogger)
	ntpHandler := api.NewNTPHandler(ntpService)
	networkService, err := service.NewNetworkService(cfg, operationLogService, zapLogger)
	if err != nil {
		return nil, err
	}
	networkHandler := api.NewNetworkHandler(networkService)
	cameraRepository := repository.NewCameraRepository(gormDB)
	engineClient, err := engineipc.NewEngineClient(cfg)
	if err != nil {
		return nil, err
	}
	cameraService := service.NewCameraService(cameraRepository, engineClient)
	cameraHandler := api.NewCameraHandler(cameraService)
	personRepository := repository.NewPersonRepository(gormDB)
	personService := service.NewPersonService(personRepository)
	personHandler := api.NewPersonHandler(personService)
	deps := router.Deps{
		ErrorHandler:           handlerFunc,
		AuthMiddleware:         authMiddleware,
		PermMiddleware:         permMiddleware,
		OplogMiddleware:        oplogMiddleware,
		OpenPersonIPMiddleware: openPersonIPWhitelistMiddleware,
		MenuHandler:            menuHandler,
		RoleHandler:            roleHandler,
		DepartmentHandler:      departmentHandler,
		OperationLogHandler:    operationLogHandler,
		UserHandler:            userHandler,
		AuthHandler:            authHandler,
		FileHandler:            fileHandler,
		NTPHandler:             ntpHandler,
		NetworkHandler:         networkHandler,
		CameraHandler:          cameraHandler,
		PersonHandler:          personHandler,
	}
	engine := router.New(cfg, deps)
	desiredStateAdapter := engineipc.UnavailableDesiredStateAdapter()
	reportAdapter := engineipc.UnavailableReportAdapter()
	runtime := engineipc.NewRuntime(zapLogger, desiredStateAdapter, reportAdapter)
	app := &App{
		DB:           gormDB,
		Logger:       zapLogger,
		Engine:       engine,
		NTPService:   ntpService,
		Network:      networkService,
		IPCRuntime:   runtime,
		EngineClient: engineClient,
	}
	return app, nil
}
