// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"niko-vue-admin/app/internal/pkg/config"
	"niko-vue-admin/app/internal/pkg/db"
	"niko-vue-admin/app/internal/pkg/logger"
	"niko-vue-admin/app/internal/router"
)

// Injectors from wire.go:

// InitializeApp 装配启动依赖链：config → db → logger → engine。
func InitializeApp(cfg *config.Config) (*App, error) {
	zapLogger, err := logger.New(cfg)
	if err != nil {
		return nil, err
	}
	gormDB, err := db.New(cfg, zapLogger)
	if err != nil {
		return nil, err
	}
	engine := router.New(cfg)
	app := &App{
		DB:     gormDB,
		Logger: zapLogger,
		Engine: engine,
	}
	return app, nil
}
