if(NOT DEFINED STAGING_DIR OR NOT DEFINED SOURCE_MANIFEST OR NOT DEFINED ENTRY_LIBRARY)
    message(FATAL_ERROR "Package validation requires STAGING_DIR, SOURCE_MANIFEST and ENTRY_LIBRARY")
endif()

if(NOT EXISTS "${SOURCE_MANIFEST}")
    message(FATAL_ERROR "Manifest source does not exist: ${SOURCE_MANIFEST}")
endif()

file(READ "${SOURCE_MANIFEST}" manifest)
string(JSON manifest_type ERROR_VARIABLE manifest_type_error TYPE "${manifest}")
if(manifest_type_error OR NOT manifest_type STREQUAL "OBJECT")
    message(FATAL_ERROR "Manifest must be a JSON object")
endif()

# v1 is deliberately closed: a new top-level field requires a manifest version change.
set(allowed_top_level
    manifest_version algorithm_id version name description algorithm_type alarm_type_id
    platform_id min_adapter_version runtime_constraints resource_profile entry_library
    config_schema_file test_image_file self_test files)
string(JSON top_level_count LENGTH "${manifest}")
if(top_level_count GREATER 0)
    math(EXPR top_level_last "${top_level_count} - 1")
    foreach(index RANGE 0 ${top_level_last})
        string(JSON key MEMBER "${manifest}" ${index})
        list(FIND allowed_top_level "${key}" key_index)
        if(key_index EQUAL -1)
            message(FATAL_ERROR "Manifest contains an unknown top-level field: ${key}")
        endif()
    endforeach()
endif()

foreach(required_field IN ITEMS manifest_version algorithm_id version name algorithm_type alarm_type_id
                              platform_id min_adapter_version runtime_constraints resource_profile entry_library
                              config_schema_file test_image_file self_test files)
    string(JSON field_type ERROR_VARIABLE field_error TYPE "${manifest}" "${required_field}")
    if(field_error)
        message(FATAL_ERROR "Manifest is missing required field: ${required_field}")
    endif()
endforeach()

string(JSON manifest_version GET "${manifest}" manifest_version)
if(NOT manifest_version STREQUAL "1")
    message(FATAL_ERROR "Only manifest_version 1 is supported")
endif()

string(JSON algorithm_id GET "${manifest}" algorithm_id)
string(LENGTH "${algorithm_id}" algorithm_id_length)
if(algorithm_id_length LESS 3 OR algorithm_id_length GREATER 32 OR
   NOT algorithm_id MATCHES "^[a-z0-9_-]+$")
    message(FATAL_ERROR "Manifest algorithm_id is invalid")
endif()

string(JSON version GET "${manifest}" version)
if(NOT version MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+([.-][0-9A-Za-z.-]+)?$")
    message(FATAL_ERROR "Manifest version is not SemVer: ${version}")
endif()

string(JSON name GET "${manifest}" name)
string(LENGTH "${name}" name_length)
if(name_length LESS 1 OR name_length GREATER 64)
    message(FATAL_ERROR "Manifest name length is invalid")
endif()
string(JSON description_type ERROR_VARIABLE description_error TYPE "${manifest}" description)
if(NOT description_error STREQUAL "NOTFOUND")
    if(NOT description_type STREQUAL "STRING")
        message(FATAL_ERROR "Manifest description must be a string")
    endif()
    string(JSON description GET "${manifest}" description)
    string(LENGTH "${description}" description_length)
    if(description_length GREATER 256)
        message(FATAL_ERROR "Manifest description is too long")
    endif()
endif()

string(JSON algorithm_type GET "${manifest}" algorithm_type)
if(NOT algorithm_type STREQUAL "object_detection")
    message(FATAL_ERROR "Only object_detection packages are supported")
endif()
string(JSON alarm_type_id GET "${manifest}" alarm_type_id)
string(LENGTH "${alarm_type_id}" alarm_type_id_length)
if(alarm_type_id_length LESS 3 OR alarm_type_id_length GREATER 32 OR
   NOT alarm_type_id MATCHES "^[a-z0-9_]+$")
    message(FATAL_ERROR "Manifest alarm_type_id is invalid")
endif()

string(JSON platform_id GET "${manifest}" platform_id)
if(NOT platform_id MATCHES "^[a-z0-9]+(-[a-z0-9]+)+$")
    message(FATAL_ERROR "Manifest platform_id is invalid")
endif()
string(JSON min_adapter_version GET "${manifest}" min_adapter_version)
if(NOT min_adapter_version MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+([.-][0-9A-Za-z.-]+)?$")
    message(FATAL_ERROR "Manifest min_adapter_version is not SemVer: ${min_adapter_version}")
endif()

string(JSON runtime_type TYPE "${manifest}" runtime_constraints)
if(NOT runtime_type STREQUAL "OBJECT")
    message(FATAL_ERROR "Manifest runtime_constraints must be an object")
endif()
string(JSON runtime_count LENGTH "${manifest}" runtime_constraints)
if(runtime_count GREATER 0)
    math(EXPR runtime_last "${runtime_count} - 1")
    foreach(index RANGE 0 ${runtime_last})
        string(JSON key MEMBER "${manifest}" runtime_constraints ${index})
        if(NOT key STREQUAL "min_os_version")
            message(FATAL_ERROR "Unknown runtime constraint: ${key}")
        endif()
    endforeach()
endif()
string(JSON min_os_version_type ERROR_VARIABLE min_os_error TYPE "${manifest}" runtime_constraints min_os_version)
if(min_os_error OR NOT min_os_version_type STREQUAL "STRING")
    message(FATAL_ERROR "runtime_constraints.min_os_version is required")
endif()
string(JSON min_os_version GET "${manifest}" runtime_constraints min_os_version)
if(NOT min_os_version MATCHES "^[0-9]+\\.[0-9]+$")
    message(FATAL_ERROR "runtime_constraints.min_os_version is invalid: ${min_os_version}")
endif()

string(JSON resource_type TYPE "${manifest}" resource_profile)
if(NOT resource_type STREQUAL "OBJECT")
    message(FATAL_ERROR "Manifest resource_profile must be an object")
endif()
string(JSON resource_count LENGTH "${manifest}" resource_profile)
if(resource_count GREATER 0)
    math(EXPR resource_last "${resource_count} - 1")
    foreach(index RANGE 0 ${resource_last})
        string(JSON key MEMBER "${manifest}" resource_profile ${index})
        if(NOT key STREQUAL "min_free_memory_mb" AND NOT key STREQUAL "fps_tiers")
            message(FATAL_ERROR "Unknown resource_profile field: ${key}")
        endif()
    endforeach()
endif()
string(JSON min_memory GET "${manifest}" resource_profile min_free_memory_mb)
if(NOT min_memory MATCHES "^[1-9][0-9]*$")
    message(FATAL_ERROR "resource_profile.min_free_memory_mb must be a positive integer")
endif()
string(JSON tier_type TYPE "${manifest}" resource_profile fps_tiers)
if(NOT tier_type STREQUAL "ARRAY")
    message(FATAL_ERROR "resource_profile.fps_tiers must be an array")
endif()
string(JSON tier_count LENGTH "${manifest}" resource_profile fps_tiers)
if(tier_count LESS 1)
    message(FATAL_ERROR "resource_profile.fps_tiers must not be empty")
endif()
set(previous_fps 0)
math(EXPR tier_last "${tier_count} - 1")
foreach(index RANGE 0 ${tier_last})
    string(JSON tier_object_type TYPE "${manifest}" resource_profile fps_tiers ${index})
    if(NOT tier_object_type STREQUAL "OBJECT")
        message(FATAL_ERROR "Every fps tier must be an object")
    endif()
    string(JSON tier_fields LENGTH "${manifest}" resource_profile fps_tiers ${index})
    if(NOT tier_fields EQUAL 2)
        message(FATAL_ERROR "Every fps tier must contain only fps and units")
    endif()
    string(JSON fps GET "${manifest}" resource_profile fps_tiers ${index} fps)
    string(JSON units GET "${manifest}" resource_profile fps_tiers ${index} units)
    if(NOT fps MATCHES "^[1-9][0-9]*$" OR NOT units MATCHES "^[1-9][0-9]*$")
        message(FATAL_ERROR "fps tier values must be positive integers")
    endif()
    if(fps LESS_EQUAL previous_fps OR units GREATER 1000)
        message(FATAL_ERROR "fps tiers must be strictly increasing and units <= 1000")
    endif()
    set(previous_fps "${fps}")
endforeach()

string(JSON self_test_type TYPE "${manifest}" self_test)
if(NOT self_test_type STREQUAL "OBJECT")
    message(FATAL_ERROR "Manifest self_test must be an object")
endif()
string(JSON self_test_count LENGTH "${manifest}" self_test)
if(NOT self_test_count EQUAL 2)
    message(FATAL_ERROR "Manifest self_test must contain timeout_ms and input_mode")
endif()
string(JSON timeout_ms GET "${manifest}" self_test timeout_ms)
if(NOT timeout_ms MATCHES "^[1-9][0-9]*$" OR timeout_ms LESS 1 OR timeout_ms GREATER 60000)
    message(FATAL_ERROR "self_test.timeout_ms must be in [1, 60000]")
endif()
string(JSON input_mode GET "${manifest}" self_test input_mode)
if(NOT input_mode STREQUAL "test_image")
    message(FATAL_ERROR "self_test.input_mode must be test_image")
endif()

string(JSON declared_entry GET "${manifest}" entry_library)
string(JSON config_schema_file GET "${manifest}" config_schema_file)
string(JSON test_image_file GET "${manifest}" test_image_file)
if(NOT declared_entry STREQUAL "${ENTRY_LIBRARY}")
    message(FATAL_ERROR "Manifest entry_library '${declared_entry}' does not match '${ENTRY_LIBRARY}'")
endif()

foreach(package_path IN ITEMS "${declared_entry}" "${config_schema_file}" "${test_image_file}")
    if(package_path STREQUAL "" OR IS_ABSOLUTE "${package_path}" OR
       package_path MATCHES "(^|/)[.][.](/|$)" OR package_path MATCHES "(^|/)\./" OR
       package_path MATCHES "\\\\" OR package_path MATCHES "(^|/)//")
        message(FATAL_ERROR "Unsafe manifest path: ${package_path}")
    endif()
endforeach()

if(NOT EXISTS "${STAGING_DIR}/${config_schema_file}" OR IS_DIRECTORY "${STAGING_DIR}/${config_schema_file}" OR
   NOT EXISTS "${STAGING_DIR}/${test_image_file}" OR IS_DIRECTORY "${STAGING_DIR}/${test_image_file}")
    message(FATAL_ERROR "Manifest config_schema_file or test_image_file is missing")
endif()
file(READ "${STAGING_DIR}/${config_schema_file}" config_schema)
string(JSON schema_type ERROR_VARIABLE schema_error TYPE "${config_schema}")
if(schema_error OR NOT schema_type STREQUAL "OBJECT")
    message(FATAL_ERROR "Config schema must be a JSON object schema")
endif()
string(JSON schema_root_type ERROR_VARIABLE schema_root_error TYPE "${config_schema}" type)
if(schema_root_error OR NOT schema_root_type STREQUAL "STRING")
    message(FATAL_ERROR "Config schema type is required")
endif()
string(JSON schema_type_value GET "${config_schema}" type)
if(NOT schema_type_value STREQUAL "object")
    message(FATAL_ERROR "Config schema root type must be object")
endif()
string(JSON additional_properties ERROR_VARIABLE additional_properties_error GET "${config_schema}" additionalProperties)
if(additional_properties_error OR NOT additional_properties STREQUAL "OFF")
    message(FATAL_ERROR "Config schema must set additionalProperties=false")
endif()

string(JSON file_count LENGTH "${manifest}" files)
if(file_count LESS 3)
    message(FATAL_ERROR "Manifest must list library, config_schema and test_image files")
endif()

set(seen_library FALSE)
set(seen_schema FALSE)
set(seen_test_image FALSE)
set(seen_paths)
set(updated_manifest "${manifest}")
math(EXPR file_last "${file_count} - 1")
foreach(index RANGE 0 ${file_last})
    string(JSON file_object_type TYPE "${updated_manifest}" files ${index})
    if(NOT file_object_type STREQUAL "OBJECT")
        message(FATAL_ERROR "Manifest files entries must be objects")
    endif()
    string(JSON file_field_count LENGTH "${updated_manifest}" files ${index})
    if(NOT file_field_count EQUAL 3)
        message(FATAL_ERROR "Manifest file entries must contain path, kind and sha256")
    endif()
    string(JSON path GET "${updated_manifest}" files ${index} path)
    string(JSON kind GET "${updated_manifest}" files ${index} kind)
    if(kind STREQUAL "library" AND DEFINED UPDATE_LIBRARY_HASH AND UPDATE_LIBRARY_HASH)
        if(NOT EXISTS "${STAGING_DIR}/${path}" OR IS_DIRECTORY "${STAGING_DIR}/${path}")
            message(FATAL_ERROR "Library file is missing: ${path}")
        endif()
        file(SHA256 "${STAGING_DIR}/${path}" digest)
        string(JSON updated_manifest SET "${updated_manifest}" files ${index} sha256 "\"${digest}\"")
    endif()
    string(JSON declared_sha GET "${updated_manifest}" files ${index} sha256)
    if(path STREQUAL "" OR IS_ABSOLUTE "${path}" OR path MATCHES "(^|/)[.][.](/|$)" OR
       path MATCHES "(^|/)\./" OR path MATCHES "\\\\" OR path MATCHES "(^|/)//")
        message(FATAL_ERROR "Unsafe manifest path: ${path}")
    endif()
    list(FIND seen_paths "${path}" duplicate_index)
    if(NOT duplicate_index EQUAL -1)
        message(FATAL_ERROR "Manifest contains duplicate path: ${path}")
    endif()
    list(APPEND seen_paths "${path}")
    if(NOT EXISTS "${STAGING_DIR}/${path}" OR IS_DIRECTORY "${STAGING_DIR}/${path}")
        message(FATAL_ERROR "Manifest file is missing or is not a regular file: ${path}")
    endif()
    string(LENGTH "${declared_sha}" sha_length)
    if(NOT sha_length EQUAL 64 OR NOT declared_sha MATCHES "^[0-9a-f]+$")
        message(FATAL_ERROR "Manifest SHA-256 is invalid for ${path}")
    endif()

    file(SHA256 "${STAGING_DIR}/${path}" digest)
    if(NOT declared_sha STREQUAL "${digest}")
        message(FATAL_ERROR "Manifest SHA-256 mismatch for ${path}: declared ${declared_sha}, actual ${digest}")
    endif()
    if(kind STREQUAL "library")
        if(seen_library)
            message(FATAL_ERROR "Manifest contains multiple library entries")
        endif()
        set(seen_library TRUE)
        set(library_path "${path}")
        if(NOT path STREQUAL "${ENTRY_LIBRARY}")
            message(FATAL_ERROR "library entry does not match entry_library")
        endif()
    elseif(kind STREQUAL "config_schema")
        if(seen_schema)
            message(FATAL_ERROR "Manifest contains multiple config_schema entries")
        endif()
        set(seen_schema TRUE)
        if(NOT path STREQUAL "${config_schema_file}")
            message(FATAL_ERROR "config_schema entry does not match config_schema_file")
        endif()
    elseif(kind STREQUAL "test_image")
        if(seen_test_image)
            message(FATAL_ERROR "Manifest contains multiple test_image entries")
        endif()
        set(seen_test_image TRUE)
        if(NOT path STREQUAL "${test_image_file}")
            message(FATAL_ERROR "test_image entry does not match test_image_file")
        endif()
    elseif(NOT kind STREQUAL "model")
        message(FATAL_ERROR "Unknown manifest file kind: ${kind}")
    endif()
endforeach()

if(NOT seen_library OR NOT seen_schema OR NOT seen_test_image)
    message(FATAL_ERROR "Manifest is missing a required file kind")
endif()

find_program(NM_EXECUTABLE nm)
if(NM_EXECUTABLE)
    execute_process(COMMAND "${NM_EXECUTABLE}" --export-symbols "${STAGING_DIR}/${library_path}"
                    RESULT_VARIABLE nm_result OUTPUT_VARIABLE nm_output ERROR_VARIABLE nm_error)
    if(NOT nm_result EQUAL 0)
        message(FATAL_ERROR "Could not inspect exported symbols: ${nm_error}")
    endif()
    string(REPLACE "\n" ";" exported_symbols "${nm_output}")
    list(FILTER exported_symbols EXCLUDE REGEX "^$")
    list(LENGTH exported_symbols exported_count)
    if(NOT exported_count EQUAL 1 OR NOT exported_symbols STREQUAL "_av_algo_get_abi")
        message(FATAL_ERROR "Algorithm library must export only av_algo_get_abi")
    endif()
endif()

file(WRITE "${STAGING_DIR}/manifest.json" "${updated_manifest}\n")
