//go:build linux

package ntp

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"strings"
	"time"
)

const (
	chronyDropInDir  = "/etc/chrony/conf.d"
	chronyDropInFile = "/etc/chrony/conf.d/aivision.conf"
)

type chronyExecutor struct{}

// NewChronyExecutor 创建 Linux chrony 执行器
func NewChronyExecutor() Executor {
	return &chronyExecutor{}
}

func (c *chronyExecutor) GetStatus(ctx context.Context) (*SyncStatus, error) {
	// 执行 chronyc tracking 获取跟踪状态
	cmd := exec.CommandContext(ctx, "chronyc", "tracking")
	out, err := cmd.CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("chronyc tracking failed (%v): %s", err, string(out))
	}

	return parseChronyTracking(string(out)), nil
}

func parseChronyTracking(output string) *SyncStatus {
	status := &SyncStatus{
		Synced: false,
		Source: "",
		Offset: "0.000s",
	}
	var hasLeapStatus bool

	for _, rawLine := range strings.Split(output, "\n") {
		line := strings.TrimSpace(rawLine)
		_, value, ok := strings.Cut(line, ":")
		if !ok {
			continue
		}
		value = strings.TrimSpace(value)

		switch {
		case strings.HasPrefix(line, "Reference ID"):
			if start := strings.LastIndexByte(value, '('); start >= 0 && strings.HasSuffix(value, ")") {
				status.Source = strings.TrimSpace(value[start+1 : len(value)-1])
			}
		case strings.HasPrefix(line, "Last offset"):
			status.Offset = normalizeChronyOffset(value)
		case strings.HasPrefix(line, "Ref time (UTC)"):
			if refTime, err := time.Parse("Mon Jan 2 15:04:05 2006", value); err == nil {
				formatted := refTime.UTC().Format(time.RFC3339)
				status.LastSyncTime = &formatted
			}
		case strings.HasPrefix(line, "Leap status"):
			hasLeapStatus = true
			status.Synced = strings.EqualFold(value, "Normal")
		}
	}

	if !hasLeapStatus {
		status.Synced = status.Source != "" && !strings.Contains(status.Source, "0.0.0.0")
	}
	return status
}

func normalizeChronyOffset(value string) string {
	fields := strings.Fields(value)
	if len(fields) == 2 && strings.EqualFold(fields[1], "seconds") {
		return fields[0] + "s"
	}
	return strings.TrimSpace(value)
}

func (c *chronyExecutor) ApplyNTP(ctx context.Context, servers []string) error {
	if err := os.MkdirAll(chronyDropInDir, 0755); err != nil {
		return fmt.Errorf("failed to create chrony drop-in dir: %w", err)
	}

	var buf bytes.Buffer
	buf.WriteString("# Generated by aivision ntp service\n")
	for _, server := range servers {
		server = strings.TrimSpace(server)
		if server != "" {
			buf.WriteString(fmt.Sprintf("server %s iburst\n", server))
		}
	}

	if err := os.WriteFile(chronyDropInFile, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("failed to write chrony drop-in config: %w", err)
	}

	// 启动 chrony 服务并重载配置（chrony 与 chronyd 单元名因发行版而异，逐个尝试）
	startErr := exec.CommandContext(ctx, "systemctl", "start", "chrony").Run()
	if startErr != nil {
		startErr = exec.CommandContext(ctx, "systemctl", "start", "chronyd").Run()
	}
	if startErr != nil {
		return fmt.Errorf("failed to start chrony service: %w", startErr)
	}
	if out, err := exec.CommandContext(ctx, "chronyc", "reload", "sources").CombinedOutput(); err != nil {
		return fmt.Errorf("chronyc reload sources failed (%v): %s", err, string(out))
	}

	return nil
}

func (c *chronyExecutor) DisableNTP(ctx context.Context) error {
	if err := os.Remove(chronyDropInFile); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("failed to remove chrony drop-in config: %w", err)
	}
	// 停止已停止的服务属幂等操作，失败不影响停用结果，保持 best-effort
	_ = exec.CommandContext(ctx, "systemctl", "stop", "chrony").Run()
	_ = exec.CommandContext(ctx, "systemctl", "stop", "chronyd").Run()
	if out, err := exec.CommandContext(ctx, "timedatectl", "set-ntp", "false").CombinedOutput(); err != nil {
		return fmt.Errorf("timedatectl set-ntp false failed (%v): %s", err, string(out))
	}
	return nil
}

func (c *chronyExecutor) SyncNow(ctx context.Context) error {
	cmd := exec.CommandContext(ctx, "chronyc", "makestep")
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("chronyc makestep failed (%v): %s", err, string(out))
	}
	return nil
}

func (c *chronyExecutor) SetSystemTime(ctx context.Context, t time.Time) error {
	// 先禁用 NTP 避免被覆盖
	if err := c.DisableNTP(ctx); err != nil {
		return fmt.Errorf("disable ntp before set system time: %w", err)
	}
	return setSystemTimeLinux(ctx, t)
}
